/-
# Raw typing and computation judgments for bounded MLTT

This module presents the rules of the source calculus over the independently
scoped syntax from `RawSyntax`.  The judgments are intentionally conservative:
there is no conversion rule that can import a target equality witness, and the
only definitional equalities are generated by the source beta rules and their
source-language congruence closure.

The formation, introduction, elimination, and computation rules cover:

* predicative Tarski universes and decoding;
* dependent products and sums;
* lifted natural numbers and their dependent recursor;
* identity formation/reflexivity; and
* an equality-factored `J` whose motive binds only an endpoint and a source
  identity proof.

`Computation` is the operational layer.  `TypedComputation` records only a
source typing derivation; `subject_reduction` derives target typing for every
primitive rule using the proved renaming/substitution metatheory.  Natural
numbers are indexed by their universe level, so `El (codeNat level)` computes
to `Nat level` without the level mismatch of an unlifted global natural type.
-/

import ComputationalPaths.Path.TypeTheory.RawSyntax

namespace ComputationalPaths
namespace Path
namespace TypeTheory
namespace RawMLTT

/-! ## Derived binder operations -/

/-- Weakening of an expression by one fresh variable. -/
def weaken {n : Nat} (t : Expr n) : Expr (n + 1) :=
  rename (Ren.wk n) t

/-- Weakening by two fresh variables. -/
def weaken₂ {n : Nat} (t : Expr n) : Expr (n + 2) :=
  rename (Ren.comp (Ren.wk n) (Ren.wk (n + 1))) t

/-- Context in which the natural-number successor branch is checked: the first
extension binds the predecessor and the second binds the induction hypothesis. -/
def natStepCtx {n : Nat} (Gamma : Ctx n) (natLevel : Nat)
    (motive : Expr (n + 1)) :
    Ctx (n + 2) :=
  Ctx.extend (Ctx.extend Gamma (.nat natLevel : Expr n)) motive

/-- The target of the natural-number successor branch.  Index zero in `motive`
is replaced by `succ` of the predecessor (index one); ambient variables are
shifted across both branch binders. -/
def natStepTarget {n : Nat} (natLevel : Nat)
    (motive : Expr (n + 1)) : Expr (n + 2) :=
  subst
    (fun i => Fin.cases
      (.succ natLevel (.var (Fin.succ (0 : Fin (n + 1)))))
      (fun j => .var (Fin.succ (Fin.succ j))) i)
    motive

/-- Context for the equality-factored motive.  The first new variable is the
endpoint; the second is a proof of identity from the fixed base point. -/
def eqProofType {n : Nat} (A a : Expr n) : Expr (n + 1) :=
  .id (weaken A) (weaken a) (.var 0)

/-- Context for an equality-factored motive. -/
def eqMotiveCtx {n : Nat} (Gamma : Ctx n) (A a : Expr n) :
    Ctx (n + 2) :=
  Ctx.extend (Ctx.extend Gamma A)
    (eqProofType A a)

@[simp] theorem eqProofType_rename {n m : Nat} (rho : Ren n m)
    (A a : Expr n) :
    rename (Ren.lift rho) (eqProofType A a) =
      eqProofType (rename rho A) (rename rho a) := by
  unfold eqProofType weaken
  simp only [rename]
  rw [rename_comp, rename_comp, Ren.wk_lift_natural]
  simp only [rename_comp, Ren.lift_zero]

@[simp] theorem natStepTarget_rename {n m : Nat} (rho : Ren n m)
    (natLevel : Nat) (motive : Expr (n + 1)) :
    rename (Ren.lift (Ren.lift rho)) (natStepTarget natLevel motive) =
      natStepTarget natLevel (rename (Ren.lift rho) motive) := by
  simp only [natStepTarget, rename_subst, subst_rename]
  apply _root_.congrArg (fun sigma => subst sigma motive)
  funext i
  refine Fin.cases ?_ (fun j => ?_) i
  · rfl
  · rfl

@[simp] theorem subst_lift_weaken {n m : Nat} (sigma : Sub n m)
    (t : Expr n) :
    subst (Sub.lift sigma) (weaken t) =
      weaken (subst sigma t) := by
  unfold weaken
  rw [subst_rename, rename_subst]
  rfl

@[simp] theorem eqProofType_subst {n m : Nat} (sigma : Sub n m)
    (A a : Expr n) :
    subst (Sub.lift sigma) (eqProofType A a) =
      eqProofType (subst sigma A) (subst sigma a) := by
  unfold eqProofType
  simp only [subst]
  rw [subst_lift_weaken, subst_lift_weaken]
  rfl

@[simp] theorem natStepTarget_subst {n m : Nat} (sigma : Sub n m)
    (natLevel : Nat) (motive : Expr (n + 1)) :
    subst (Sub.lift (Sub.lift sigma)) (natStepTarget natLevel motive) =
      natStepTarget natLevel (subst (Sub.lift sigma) motive) := by
  simp only [natStepTarget, subst_comp]
  apply _root_.congrArg (fun tau => subst tau motive)
  funext i
  refine Fin.cases ?_ (fun j => ?_) i
  · rfl
  · simp only [Sub.comp, Sub.lift_succ]
    rw [subst_rename]
    change
      rename (Ren.wk (m + 1)) (rename (Ren.wk m) (sigma j)) =
        subst
          (Sub.ofRen (Ren.comp (Ren.wk m) (Ren.wk (m + 1))))
          (sigma j)
    rw [subst_ofRen, rename_comp]

@[simp] theorem natStepTarget_instantiate {n : Nat}
    (natLevel : Nat) (motive : Expr (n + 1)) (k ih : Expr n) :
    instantiate₂ (natStepTarget natLevel motive) k ih =
      instantiate motive (.succ natLevel k) := by
  unfold natStepTarget instantiate₂ instantiate
  rw [subst_comp]
  apply _root_.congrArg (fun sigma => subst sigma motive)
  funext i
  refine Fin.cases ?_ (fun j => ?_) i
  · rfl
  · rfl

/-! ## Typing judgment -/

/-- Raw typing derivations for the bounded fragment.

Universe levels are natural numbers.  A code in `sort level` decodes to a type
in the same level, while the universe itself lives in its successor.  Product,
sum, and identity formation are level-preserving in this bounded presentation. -/
inductive HasType : {n : Nat} -> Ctx n -> Expr n -> Expr n -> Type where
  | var {n : Nat} {Gamma : Ctx n} (i : Fin n) :
      HasType Gamma (.var i) (Gamma i)
  | sort {n : Nat} {Gamma : Ctx n} (level : Nat) :
      HasType Gamma (.sort level) (.sort (level + 1))
  | piForm {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma A) B (.sort level) ->
      HasType Gamma (.pi A B) (.sort level)
  | sigmaForm {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma A) B (.sort level) ->
      HasType Gamma (.sigma A B) (.sort level)
  | lamIntro {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B body : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma A) B (.sort level) ->
      HasType (Ctx.extend Gamma A) body B ->
      HasType Gamma (.lam body) (.pi A B)
  | appElim {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {f a : Expr n} :
      HasType Gamma f (.pi A B) ->
      HasType Gamma a A ->
      HasType Gamma (.app f a) (instantiate B a)
  | pairIntro {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {a b : Expr n} :
      HasType Gamma a A ->
      HasType Gamma b (instantiate B a) ->
      HasType Gamma (.pair a b) (.sigma A B)
  | fstElim {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {p : Expr n} :
      HasType Gamma p (.sigma A B) ->
      HasType Gamma (.fst p) A
  | sndElim {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {p : Expr n} :
      HasType Gamma p (.sigma A B) ->
      HasType Gamma (.snd p) (instantiate B (.fst p))
  | natForm {n : Nat} {Gamma : Ctx n} (natLevel : Nat) :
      HasType Gamma (.nat natLevel) (.sort natLevel)
  | zeroIntro {n : Nat} {Gamma : Ctx n} (natLevel : Nat) :
      HasType Gamma (.zero natLevel) (.nat natLevel)
  | succIntro {n : Nat} {Gamma : Ctx n} {t : Expr n}
      (natLevel : Nat) :
      HasType Gamma t (.nat natLevel) ->
      HasType Gamma (.succ natLevel t) (.nat natLevel)
  | natElim {n : Nat} {Gamma : Ctx n} {motive : Expr (n + 1)}
      {zeroCase scrutinee : Expr n} {succCase : Expr (n + 2)}
      {level natLevel : Nat} :
      HasType (Ctx.extend Gamma (.nat natLevel)) motive (.sort level) ->
      HasType Gamma zeroCase (instantiate motive (.zero natLevel)) ->
      HasType (natStepCtx Gamma natLevel motive) succCase
        (natStepTarget natLevel motive) ->
      HasType Gamma scrutinee (.nat natLevel) ->
      HasType Gamma
        (.natElim natLevel motive zeroCase succCase scrutinee)
        (instantiate motive scrutinee)
  | codeNatIntro {n : Nat} {Gamma : Ctx n} (level : Nat) :
      HasType Gamma (.codeNat level) (.sort level)
  | codePiIntro {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma (.el A)) B (.sort level) ->
      HasType Gamma (.codePi A B) (.sort level)
  | codeSigmaIntro {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma (.el A)) B (.sort level) ->
      HasType Gamma (.codeSigma A B) (.sort level)
  | codeIdIntro {n : Nat} {Gamma : Ctx n} {A a b : Expr n}
      {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType Gamma a (.el A) ->
      HasType Gamma b (.el A) ->
      HasType Gamma (.codeId A a b) (.sort level)
  | elForm {n : Nat} {Gamma : Ctx n} {code : Expr n} {level : Nat} :
      HasType Gamma code (.sort level) ->
      HasType Gamma (.el code) (.sort level)
  | idForm {n : Nat} {Gamma : Ctx n} {A a b : Expr n}
      {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType Gamma a A ->
      HasType Gamma b A ->
      HasType Gamma (.id A a b) (.sort level)
  | reflIntro {n : Nat} {Gamma : Ctx n} {A a : Expr n} :
      HasType Gamma a A ->
      HasType Gamma (.refl a) (.id A a a)
  | eqJElim {n : Nat} {Gamma : Ctx n} {A a : Expr n}
      {motive : Expr (n + 2)} {reflCase endpoint proof : Expr n}
      {level motiveLevel : Nat} :
      HasType Gamma A (.sort level) ->
      HasType Gamma a A ->
      HasType (eqMotiveCtx Gamma A a) motive (.sort motiveLevel) ->
      HasType Gamma reflCase (instantiate₂ motive a (.refl a)) ->
      HasType Gamma endpoint A ->
      HasType Gamma proof (.id A a endpoint) ->
      HasType Gamma (.eqJ motive reflCase endpoint proof)
        (instantiate₂ motive endpoint proof)

/-! ## Renaming metatheory for typing -/

/-- A renaming sends every declaration in `Gamma` to the declaration selected
in `Delta`. -/
abbrev CtxRen {n m : Nat} (Delta : Ctx m) (Gamma : Ctx n)
    (rho : Ren n m) : Prop :=
  forall i, Delta (rho i) = rename rho (Gamma i)

namespace CtxRen

/-- Context-renaming compatibility lifts through a binder. -/
theorem lift {n m : Nat} {Delta : Ctx m} {Gamma : Ctx n}
    {rho : Ren n m} (h : CtxRen Delta Gamma rho) (A : Expr n) :
    CtxRen (Ctx.extend Delta (rename rho A)) (Ctx.extend Gamma A)
      (Ren.lift rho) := by
  intro i
  refine Fin.cases ?_ (fun j => ?_) i
  · simp [Ctx.extend, rename_comp, Ren.wk_lift_natural]
  · simp [Ctx.extend, h j, rename_comp, Ren.wk_lift_natural]

/-- The natural-number branch context is functorial in renaming. -/
theorem natStep {n m : Nat} {Delta : Ctx m} {Gamma : Ctx n}
    {rho : Ren n m} (h : CtxRen Delta Gamma rho)
    (natLevel : Nat) (motive : Expr (n + 1)) :
    CtxRen
      (natStepCtx Delta natLevel (rename (Ren.lift rho) motive))
      (natStepCtx Gamma natLevel motive)
      (Ren.lift (Ren.lift rho)) :=
  lift (lift h (.nat natLevel)) motive

/-- The equality-motive context is functorial in renaming. -/
theorem eqMotive {n m : Nat} {Delta : Ctx m} {Gamma : Ctx n}
    {rho : Ren n m} (h : CtxRen Delta Gamma rho)
    (A a : Expr n) :
    CtxRen
      (eqMotiveCtx Delta (rename rho A) (rename rho a))
      (eqMotiveCtx Gamma A a)
      (Ren.lift (Ren.lift rho)) := by
  simpa [eqMotiveCtx] using
    (lift (lift h A) (eqProofType A a))

end CtxRen

namespace HasType

/-- Typing is stable under every context-respecting renaming. -/
noncomputable def rename_preserves {n : Nat} {Gamma : Ctx n}
    {t A : Expr n}
    (d : HasType Gamma t A) {m : Nat} {Delta : Ctx m}
    (rho : Ren n m) (hctx : CtxRen Delta Gamma rho) :
    HasType Delta (rename rho t) (rename rho A) := by
  induction d generalizing m with
  | var i =>
      have h := HasType.var (Gamma := Delta) (rho i)
      rw [hctx i] at h
      exact h
  | sort level => exact HasType.sort level
  | piForm _ _ ihA ihB =>
      exact HasType.piForm
        (ihA rho hctx)
        (ihB (Ren.lift rho) (CtxRen.lift hctx _))
  | sigmaForm _ _ ihA ihB =>
      exact HasType.sigmaForm
        (ihA rho hctx)
        (ihB (Ren.lift rho) (CtxRen.lift hctx _))
  | lamIntro _ _ _ ihA ihB ihBody =>
      exact HasType.lamIntro
        (ihA rho hctx)
        (ihB (Ren.lift rho) (CtxRen.lift hctx _))
        (ihBody (Ren.lift rho) (CtxRen.lift hctx _))
  | appElim _ _ ihf iha =>
      simpa using HasType.appElim (ihf rho hctx) (iha rho hctx)
  | pairIntro _ _ iha ihb =>
      have hb := ihb rho hctx
      rw [instantiate_rename] at hb
      exact HasType.pairIntro (iha rho hctx) hb
  | fstElim _ ih =>
      exact HasType.fstElim (ih rho hctx)
  | sndElim _ ih =>
      simpa using HasType.sndElim (ih rho hctx)
  | natForm natLevel => exact HasType.natForm natLevel
  | zeroIntro natLevel => exact HasType.zeroIntro natLevel
  | succIntro natLevel _ ih =>
      exact HasType.succIntro natLevel (ih rho hctx)
  | natElim motive zeroCase succCase scrutinee ihm ihz ihs ihn =>
      have hs := ihs (Ren.lift (Ren.lift rho))
        (CtxRen.natStep hctx _ _)
      rw [natStepTarget_rename] at hs
      have hz := ihz rho hctx
      rw [instantiate_rename] at hz
      simpa using HasType.natElim
        (ihm (Ren.lift rho) (by
          simpa only [rename] using (CtxRen.lift hctx (.nat _))))
        hz
        hs
        (ihn rho hctx)
  | codeNatIntro level => exact HasType.codeNatIntro level
  | codePiIntro _ _ ihA ihB =>
      exact HasType.codePiIntro
        (ihA rho hctx)
        (ihB (Ren.lift rho) (by
          simpa only [rename] using (CtxRen.lift hctx (.el _))))
  | codeSigmaIntro _ _ ihA ihB =>
      exact HasType.codeSigmaIntro
        (ihA rho hctx)
        (ihB (Ren.lift rho) (by
          simpa only [rename] using (CtxRen.lift hctx (.el _))))
  | codeIdIntro _ _ _ ihA iha ihb =>
      exact HasType.codeIdIntro
        (ihA rho hctx) (iha rho hctx) (ihb rho hctx)
  | elForm _ ih =>
      exact HasType.elForm (ih rho hctx)
  | idForm _ _ _ ihA iha ihb =>
      exact HasType.idForm
        (ihA rho hctx) (iha rho hctx) (ihb rho hctx)
  | reflIntro _ ih =>
      exact HasType.reflIntro (ih rho hctx)
  | eqJElim A a motive reflCase endpoint proof
      ihA iha ihm ihr ihe ihp =>
      have hr := ihr rho hctx
      rw [instantiate₂_rename] at hr
      simpa using HasType.eqJElim
        (ihA rho hctx)
        (iha rho hctx)
        (ihm (Ren.lift (Ren.lift rho))
          (CtxRen.eqMotive hctx _ _))
        hr
        (ihe rho hctx)
        (ihp rho hctx)

end HasType

/-! ## Simultaneous substitution metatheory for typing -/

/-- A simultaneous substitution is well typed when every variable image has
the substituted declaration as its type. -/
abbrev CtxSub {n m : Nat} (Delta : Ctx m) (Gamma : Ctx n)
    (sigma : Sub n m) : Type :=
  (i : Fin n) -> HasType Delta (sigma i) (subst sigma (Gamma i))

namespace HasType

/-- Weakening is admissible, derived from the renaming theorem. -/
noncomputable def weaken_preserves {n : Nat} {Gamma : Ctx n}
    {t A : Expr n} (d : HasType Gamma t A) (B : Expr n) :
    HasType (Ctx.extend Gamma B) (weaken t) (weaken A) :=
  rename_preserves d (Ren.wk n) (fun _ => rfl)

end HasType

namespace CtxSub

/-- A typed simultaneous substitution lifts through a binder. -/
noncomputable def lift {n m : Nat} {Delta : Ctx m} {Gamma : Ctx n}
    {sigma : Sub n m} (h : CtxSub Delta Gamma sigma) (A : Expr n) :
    CtxSub
      (Ctx.extend Delta (subst sigma A))
      (Ctx.extend Gamma A)
      (Sub.lift sigma) := by
  intro i
  refine Fin.cases ?_ (fun j => ?_) i
  · have hv := HasType.var
      (Gamma := Ctx.extend Delta (subst sigma A)) (0 : Fin (m + 1))
    change HasType (Ctx.extend Delta (subst sigma A)) (.var 0)
      (subst (Sub.lift sigma) (weaken A))
    rw [subst_lift_weaken]
    exact hv
  · have hj := HasType.weaken_preserves (h j) (subst sigma A)
    change HasType (Ctx.extend Delta (subst sigma A))
      (weaken (sigma j))
      (subst (Sub.lift sigma) (weaken (Gamma j)))
    rw [subst_lift_weaken]
    exact hj

/-- The natural-number successor-branch context is stable under typed
substitution. -/
noncomputable def natStep {n m : Nat} {Delta : Ctx m}
    {Gamma : Ctx n} {sigma : Sub n m}
    (h : CtxSub Delta Gamma sigma) (natLevel : Nat)
    (motive : Expr (n + 1)) :
    CtxSub
      (natStepCtx Delta natLevel (subst (Sub.lift sigma) motive))
      (natStepCtx Gamma natLevel motive)
      (Sub.lift (Sub.lift sigma)) :=
  lift (lift h (.nat natLevel)) motive

/-- The equality-motive context is stable under typed substitution. -/
noncomputable def eqMotive {n m : Nat} {Delta : Ctx m}
    {Gamma : Ctx n} {sigma : Sub n m}
    (h : CtxSub Delta Gamma sigma) (A a : Expr n) :
    CtxSub
      (eqMotiveCtx Delta (subst sigma A) (subst sigma a))
      (eqMotiveCtx Gamma A a)
      (Sub.lift (Sub.lift sigma)) := by
  simpa [eqMotiveCtx] using
    (lift (lift h A) (eqProofType A a))

end CtxSub

namespace HasType

/-- The fundamental substitution lemma: every well-typed simultaneous
substitution preserves raw typing. -/
noncomputable def substitution_preserves
    {n : Nat} {Gamma : Ctx n} {t A : Expr n}
    (d : HasType Gamma t A) {m : Nat} {Delta : Ctx m}
    (sigma : Sub n m) (hctx : CtxSub Delta Gamma sigma) :
    HasType Delta (subst sigma t) (subst sigma A) := by
  induction d generalizing m with
  | var i => exact hctx i
  | sort level => exact HasType.sort level
  | piForm _ _ ihA ihB =>
      exact HasType.piForm
        (ihA sigma hctx)
        (ihB (Sub.lift sigma) (CtxSub.lift hctx _))
  | sigmaForm _ _ ihA ihB =>
      exact HasType.sigmaForm
        (ihA sigma hctx)
        (ihB (Sub.lift sigma) (CtxSub.lift hctx _))
  | lamIntro _ _ _ ihA ihB ihBody =>
      exact HasType.lamIntro
        (ihA sigma hctx)
        (ihB (Sub.lift sigma) (CtxSub.lift hctx _))
        (ihBody (Sub.lift sigma) (CtxSub.lift hctx _))
  | appElim _ _ ihf iha =>
      simpa using HasType.appElim (ihf sigma hctx) (iha sigma hctx)
  | pairIntro _ _ iha ihb =>
      have hb := ihb sigma hctx
      rw [instantiate_subst] at hb
      exact HasType.pairIntro (iha sigma hctx) hb
  | fstElim _ ih =>
      exact HasType.fstElim (ih sigma hctx)
  | sndElim _ ih =>
      simpa using HasType.sndElim (ih sigma hctx)
  | natForm natLevel => exact HasType.natForm natLevel
  | zeroIntro natLevel => exact HasType.zeroIntro natLevel
  | succIntro natLevel _ ih =>
      exact HasType.succIntro natLevel (ih sigma hctx)
  | natElim motive zeroCase succCase scrutinee ihm ihz ihs ihn =>
      have hs := ihs (Sub.lift (Sub.lift sigma))
        (CtxSub.natStep hctx _ _)
      rw [natStepTarget_subst] at hs
      have hz := ihz sigma hctx
      rw [instantiate_subst] at hz
      simpa using HasType.natElim
        (ihm (Sub.lift sigma) (by
          simpa only [subst] using (CtxSub.lift hctx (.nat _))))
        hz hs (ihn sigma hctx)
  | codeNatIntro level => exact HasType.codeNatIntro level
  | codePiIntro _ _ ihA ihB =>
      exact HasType.codePiIntro
        (ihA sigma hctx)
        (ihB (Sub.lift sigma) (by
          simpa only [subst] using (CtxSub.lift hctx (.el _))))
  | codeSigmaIntro _ _ ihA ihB =>
      exact HasType.codeSigmaIntro
        (ihA sigma hctx)
        (ihB (Sub.lift sigma) (by
          simpa only [subst] using (CtxSub.lift hctx (.el _))))
  | codeIdIntro _ _ _ ihA iha ihb =>
      exact HasType.codeIdIntro
        (ihA sigma hctx) (iha sigma hctx) (ihb sigma hctx)
  | elForm _ ih =>
      exact HasType.elForm (ih sigma hctx)
  | idForm _ _ _ ihA iha ihb =>
      exact HasType.idForm
        (ihA sigma hctx) (iha sigma hctx) (ihb sigma hctx)
  | reflIntro _ ih =>
      exact HasType.reflIntro (ih sigma hctx)
  | eqJElim A a motive reflCase endpoint proof
      ihA iha ihm ihr ihe ihp =>
      have hr := ihr sigma hctx
      rw [instantiate₂_subst] at hr
      simpa using HasType.eqJElim
        (ihA sigma hctx)
        (iha sigma hctx)
        (ihm (Sub.lift (Sub.lift sigma))
          (CtxSub.eqMotive hctx _ _))
        hr
        (ihe sigma hctx)
        (ihp sigma hctx)

/-- One-variable instantiation preserves typing. -/
noncomputable def instantiate_preserves
    {n : Nat} {Gamma : Ctx n} {A : Expr n}
    {t T : Expr (n + 1)} {a : Expr n}
    (d : HasType (Ctx.extend Gamma A) t T)
    (ha : HasType Gamma a A) :
    HasType Gamma (instantiate t a) (instantiate T a) := by
  let sigma : Sub (n + 1) n :=
    fun i => Fin.cases a (fun j => .var j) i
  have hSigma : CtxSub Gamma (Ctx.extend Gamma A) sigma := by
    intro i
    refine Fin.cases ?_ (fun j => ?_) i
    · change HasType Gamma a (instantiate (weaken A) a)
      rw [show weaken A = rename (Ren.wk n) A by rfl,
        instantiate_weaken]
      exact ha
    · have hv := HasType.var (Gamma := Gamma) j
      change HasType Gamma (.var j) (instantiate (weaken (Gamma j)) a)
      rw [show weaken (Gamma j) = rename (Ren.wk n) (Gamma j) by rfl,
        instantiate_weaken]
      exact hv
  simpa [instantiate, sigma] using
    (substitution_preserves d sigma hSigma)

/-- Two-variable instantiation preserves typing for a dependent pair of
arguments. -/
noncomputable def instantiate₂_preserves
    {n : Nat} {Gamma : Ctx n} {A : Expr n} {B : Expr (n + 1)}
    {t T : Expr (n + 2)} {a p : Expr n}
    (d : HasType (Ctx.extend (Ctx.extend Gamma A) B) t T)
    (ha : HasType Gamma a A)
    (hp : HasType Gamma p (instantiate B a)) :
    HasType Gamma (instantiate₂ t a p) (instantiate₂ T a p) := by
  let sigma : Sub (n + 2) n :=
    fun i => Fin.cases p
      (fun j => Fin.cases a (fun k => .var k) j) i
  have hSigma :
      CtxSub Gamma (Ctx.extend (Ctx.extend Gamma A) B) sigma := by
    intro i
    refine Fin.cases ?_ (fun j => ?_) i
    · change HasType Gamma p
        (instantiate₂ (rename (Ren.wk (n + 1)) B) a p)
      simpa using hp
    · refine Fin.cases ?_ (fun k => ?_) j
      · change HasType Gamma a
          (instantiate₂
            (rename (Ren.wk (n + 1)) (rename (Ren.wk n) A)) a p)
        rw [instantiate₂_weaken₂]
        exact ha
      · have hv := HasType.var (Gamma := Gamma) k
        change HasType Gamma (.var k)
          (instantiate₂
            (rename (Ren.wk (n + 1)) (rename (Ren.wk n) (Gamma k)))
            a p)
        rw [instantiate₂_weaken₂]
        exact hv
  simpa [instantiate₂, sigma] using
    (substitution_preserves d sigma hSigma)

end HasType

/-! ## Source computation and definitional equality -/

/-- Primitive source computation rules.  These constructors mention only raw
syntax; in particular, they cannot receive a `Path.Step` or `RwEq` witness. -/
inductive Computation : {n : Nat} -> Expr n -> Expr n -> Type where
  | piBeta {n : Nat} (body : Expr (n + 1)) (argument : Expr n) :
      Computation (.app (.lam body) argument) (instantiate body argument)
  | sigmaFstBeta {n : Nat} (a b : Expr n) :
      Computation (.fst (.pair a b)) a
  | sigmaSndBeta {n : Nat} (a b : Expr n) :
      Computation (.snd (.pair a b)) b
  | natZeroBeta {n : Nat} (natLevel : Nat) (motive : Expr (n + 1))
      (zeroCase : Expr n) (succCase : Expr (n + 2)) :
      Computation
        (.natElim natLevel motive zeroCase succCase (.zero natLevel))
        zeroCase
  | natSuccBeta {n : Nat} (natLevel : Nat) (motive : Expr (n + 1))
      (zeroCase : Expr n) (succCase : Expr (n + 2)) (k : Expr n) :
      Computation
        (.natElim natLevel motive zeroCase succCase (.succ natLevel k))
        (instantiate₂ succCase k
          (.natElim natLevel motive zeroCase succCase k))
  | eqJBeta {n : Nat} (motive : Expr (n + 2))
      (reflCase a : Expr n) :
      Computation
        (.eqJ motive reflCase a (.refl a))
        reflCase
  | elNatBeta {n : Nat} (level : Nat) :
      Computation (.el (.codeNat level) : Expr n) (.nat level)
  | elPiBeta {n : Nat} (A : Expr n) (B : Expr (n + 1)) :
      Computation (.el (.codePi A B)) (.pi (.el A) (.el B))
  | elSigmaBeta {n : Nat} (A : Expr n) (B : Expr (n + 1)) :
      Computation (.el (.codeSigma A B)) (.sigma (.el A) (.el B))
  | elIdBeta {n : Nat} (A a b : Expr n) :
      Computation (.el (.codeId A a b)) (.id (.el A) a b)

namespace Computation

/-- Primitive computation is stable under every simultaneous substitution.
The binder cases use the independently proved one- and two-variable
instantiation laws. -/
noncomputable def substitution {n m : Nat} (sigma : Sub n m)
    {t u : Expr n} (h : Computation t u) :
    Computation (subst sigma t) (subst sigma u) := by
  cases h with
  | piBeta body argument =>
      simpa using
        (Computation.piBeta
          (subst (Sub.lift sigma) body) (subst sigma argument))
  | sigmaFstBeta a b =>
      exact Computation.sigmaFstBeta (subst sigma u) (subst sigma b)
  | sigmaSndBeta a b =>
      exact Computation.sigmaSndBeta (subst sigma a) (subst sigma u)
  | natZeroBeta natLevel motive zeroCase succCase =>
      exact Computation.natZeroBeta natLevel
        (subst (Sub.lift sigma) motive)
        (subst sigma u)
        (subst (Sub.lift (Sub.lift sigma)) succCase)
  | natSuccBeta natLevel motive zeroCase succCase k =>
      simpa using
        (Computation.natSuccBeta natLevel
          (subst (Sub.lift sigma) motive)
          (subst sigma zeroCase)
          (subst (Sub.lift (Sub.lift sigma)) succCase)
          (subst sigma k))
  | eqJBeta motive reflCase a =>
      exact Computation.eqJBeta
        (subst (Sub.lift (Sub.lift sigma)) motive)
        (subst sigma u) (subst sigma a)
  | elNatBeta level =>
      exact Computation.elNatBeta level
  | elPiBeta A B =>
      exact Computation.elPiBeta
        (subst sigma A) (subst (Sub.lift sigma) B)
  | elSigmaBeta A B =>
      exact Computation.elSigmaBeta
        (subst sigma A) (subst (Sub.lift sigma) B)
  | elIdBeta A a b =>
      exact Computation.elIdBeta
        (subst sigma A) (subst sigma a) (subst sigma b)

end Computation

/-- A typed computation supplies only source typing and a source computation
step.  Target typing is *not* a field: it is derived by `subject_reduction`
below. -/
structure TypedComputation {n : Nat} (Gamma : Ctx n)
    (source target : Expr n) where
  type : Expr n
  sourceTyping : HasType Gamma source type
  computation : Computation source target

/-- Source definitional equality: equivalence and compatible closure of the
primitive computation rules.  Congruence is enumerated by raw constructors,
making the supported closure auditable. -/
inductive DefEq : {n : Nat} -> Expr n -> Expr n -> Prop where
  | beta {n : Nat} {t u : Expr n} : Computation t u -> DefEq t u
  | refl {n : Nat} (t : Expr n) : DefEq t t
  | symm {n : Nat} {t u : Expr n} : DefEq t u -> DefEq u t
  | trans {n : Nat} {t u v : Expr n} :
      DefEq t u -> DefEq u v -> DefEq t v
  | piDom {n : Nat} {A A' : Expr n} (B : Expr (n + 1)) :
      DefEq A A' -> DefEq (.pi A B) (.pi A' B)
  | piCod {n : Nat} (A : Expr n) {B B' : Expr (n + 1)} :
      DefEq B B' -> DefEq (.pi A B) (.pi A B')
  | sigmaDom {n : Nat} {A A' : Expr n} (B : Expr (n + 1)) :
      DefEq A A' -> DefEq (.sigma A B) (.sigma A' B)
  | sigmaCod {n : Nat} (A : Expr n) {B B' : Expr (n + 1)} :
      DefEq B B' -> DefEq (.sigma A B) (.sigma A B')
  | lamBody {n : Nat} {body body' : Expr (n + 1)} :
      DefEq body body' -> DefEq (.lam body) (.lam body')
  | appFun {n : Nat} {f f' a : Expr n} :
      DefEq f f' -> DefEq (.app f a) (.app f' a)
  | appArg {n : Nat} {f a a' : Expr n} :
      DefEq a a' -> DefEq (.app f a) (.app f a')
  | pairFst {n : Nat} {a a' b : Expr n} :
      DefEq a a' -> DefEq (.pair a b) (.pair a' b)
  | pairSnd {n : Nat} {a b b' : Expr n} :
      DefEq b b' -> DefEq (.pair a b) (.pair a b')
  | fstCongr {n : Nat} {p p' : Expr n} :
      DefEq p p' -> DefEq (.fst p) (.fst p')
  | sndCongr {n : Nat} {p p' : Expr n} :
      DefEq p p' -> DefEq (.snd p) (.snd p')
  | succCongr {n : Nat} (natLevel : Nat) {t t' : Expr n} :
      DefEq t t' -> DefEq (.succ natLevel t) (.succ natLevel t')
  | natMotive {n : Nat} (natLevel : Nat) {M M' : Expr (n + 1)}
      (z : Expr n) (s : Expr (n + 2)) (t : Expr n) :
      DefEq M M' ->
      DefEq (.natElim natLevel M z s t) (.natElim natLevel M' z s t)
  | natZero {n : Nat} (natLevel : Nat)
      (M : Expr (n + 1)) {z z' : Expr n}
      (s : Expr (n + 2)) (t : Expr n) :
      DefEq z z' ->
      DefEq (.natElim natLevel M z s t) (.natElim natLevel M z' s t)
  | natSucc {n : Nat} (natLevel : Nat)
      (M : Expr (n + 1)) (z : Expr n)
      {s s' : Expr (n + 2)} (t : Expr n) :
      DefEq s s' ->
      DefEq (.natElim natLevel M z s t) (.natElim natLevel M z s' t)
  | natScrutinee {n : Nat} (natLevel : Nat)
      (M : Expr (n + 1)) (z : Expr n)
      (s : Expr (n + 2)) {t t' : Expr n} :
      DefEq t t' ->
      DefEq (.natElim natLevel M z s t)
        (.natElim natLevel M z s t')
  | codePiDom {n : Nat} {A A' : Expr n} (B : Expr (n + 1)) :
      DefEq A A' -> DefEq (.codePi A B) (.codePi A' B)
  | codePiCod {n : Nat} (A : Expr n) {B B' : Expr (n + 1)} :
      DefEq B B' -> DefEq (.codePi A B) (.codePi A B')
  | codeSigmaDom {n : Nat} {A A' : Expr n} (B : Expr (n + 1)) :
      DefEq A A' -> DefEq (.codeSigma A B) (.codeSigma A' B)
  | codeSigmaCod {n : Nat} (A : Expr n) {B B' : Expr (n + 1)} :
      DefEq B B' -> DefEq (.codeSigma A B) (.codeSigma A B')
  | codeIdType {n : Nat} {A A' a b : Expr n} :
      DefEq A A' -> DefEq (.codeId A a b) (.codeId A' a b)
  | codeIdLeft {n : Nat} {A a a' b : Expr n} :
      DefEq a a' -> DefEq (.codeId A a b) (.codeId A a' b)
  | codeIdRight {n : Nat} {A a b b' : Expr n} :
      DefEq b b' -> DefEq (.codeId A a b) (.codeId A a b')
  | elCongr {n : Nat} {code code' : Expr n} :
      DefEq code code' -> DefEq (.el code) (.el code')
  | idType {n : Nat} {A A' a b : Expr n} :
      DefEq A A' -> DefEq (.id A a b) (.id A' a b)
  | idLeft {n : Nat} {A a a' b : Expr n} :
      DefEq a a' -> DefEq (.id A a b) (.id A a' b)
  | idRight {n : Nat} {A a b b' : Expr n} :
      DefEq b b' -> DefEq (.id A a b) (.id A a b')
  | reflCongr {n : Nat} {a a' : Expr n} :
      DefEq a a' -> DefEq (.refl a) (.refl a')
  | eqJMotive {n : Nat} {M M' : Expr (n + 2)}
      (r b p : Expr n) :
      DefEq M M' -> DefEq (.eqJ M r b p) (.eqJ M' r b p)
  | eqJRefl {n : Nat} (M : Expr (n + 2)) {r r' : Expr n}
      (b p : Expr n) :
      DefEq r r' -> DefEq (.eqJ M r b p) (.eqJ M r' b p)
  | eqJEndpoint {n : Nat} (M : Expr (n + 2)) (r : Expr n)
      {b b' : Expr n} (p : Expr n) :
      DefEq b b' -> DefEq (.eqJ M r b p) (.eqJ M r b' p)
  | eqJProof {n : Nat} (M : Expr (n + 2)) (r b : Expr n)
      {p p' : Expr n} :
      DefEq p p' -> DefEq (.eqJ M r b p) (.eqJ M r b p')

namespace DefEq

/-- Source definitional equality is stable under every simultaneous
substitution.  Binder congruences are interpreted with one or two explicit
`Sub.lift`s, so this theorem is also the well-definedness proof needed by the
quotient-level substitution action. -/
theorem substitution {n : Nat} {t u : Expr n} (h : DefEq t u)
    {m : Nat} (sigma : Sub n m) :
    DefEq (subst sigma t) (subst sigma u) := by
  induction h generalizing m with
  | beta h => exact DefEq.beta (Computation.substitution sigma h)
  | refl t => exact DefEq.refl _
  | symm _ ih => exact DefEq.symm (ih sigma)
  | trans _ _ ih₁ ih₂ =>
      exact DefEq.trans (ih₁ sigma) (ih₂ sigma)
  | piDom B _ ih =>
      exact DefEq.piDom (subst (Sub.lift sigma) B) (ih sigma)
  | piCod A _ ih =>
      exact DefEq.piCod (subst sigma A) (ih (Sub.lift sigma))
  | sigmaDom B _ ih =>
      exact DefEq.sigmaDom (subst (Sub.lift sigma) B) (ih sigma)
  | sigmaCod A _ ih =>
      exact DefEq.sigmaCod (subst sigma A) (ih (Sub.lift sigma))
  | lamBody _ ih =>
      exact DefEq.lamBody (ih (Sub.lift sigma))
  | appFun _ ih => exact DefEq.appFun (ih sigma)
  | appArg _ ih => exact DefEq.appArg (ih sigma)
  | pairFst _ ih => exact DefEq.pairFst (ih sigma)
  | pairSnd _ ih => exact DefEq.pairSnd (ih sigma)
  | fstCongr _ ih => exact DefEq.fstCongr (ih sigma)
  | sndCongr _ ih => exact DefEq.sndCongr (ih sigma)
  | succCongr natLevel _ ih =>
      exact DefEq.succCongr natLevel (ih sigma)
  | natMotive natLevel z s t _ ih =>
      exact DefEq.natMotive natLevel
        (subst sigma z)
        (subst (Sub.lift (Sub.lift sigma)) s)
        (subst sigma t)
        (ih (Sub.lift sigma))
  | natZero natLevel M s t _ ih =>
      exact DefEq.natZero natLevel
        (subst (Sub.lift sigma) M)
        (subst (Sub.lift (Sub.lift sigma)) s)
        (subst sigma t)
        (ih sigma)
  | natSucc natLevel M z t _ ih =>
      exact DefEq.natSucc natLevel
        (subst (Sub.lift sigma) M)
        (subst sigma z)
        (subst sigma t)
        (ih (Sub.lift (Sub.lift sigma)))
  | natScrutinee natLevel M z s _ ih =>
      exact DefEq.natScrutinee natLevel
        (subst (Sub.lift sigma) M)
        (subst sigma z)
        (subst (Sub.lift (Sub.lift sigma)) s)
        (ih sigma)
  | codePiDom B _ ih =>
      exact DefEq.codePiDom (subst (Sub.lift sigma) B) (ih sigma)
  | codePiCod A _ ih =>
      exact DefEq.codePiCod (subst sigma A) (ih (Sub.lift sigma))
  | codeSigmaDom B _ ih =>
      exact DefEq.codeSigmaDom (subst (Sub.lift sigma) B) (ih sigma)
  | codeSigmaCod A _ ih =>
      exact DefEq.codeSigmaCod (subst sigma A) (ih (Sub.lift sigma))
  | codeIdType _ ih => exact DefEq.codeIdType (ih sigma)
  | codeIdLeft _ ih => exact DefEq.codeIdLeft (ih sigma)
  | codeIdRight _ ih => exact DefEq.codeIdRight (ih sigma)
  | elCongr _ ih => exact DefEq.elCongr (ih sigma)
  | idType _ ih => exact DefEq.idType (ih sigma)
  | idLeft _ ih => exact DefEq.idLeft (ih sigma)
  | idRight _ ih => exact DefEq.idRight (ih sigma)
  | reflCongr _ ih => exact DefEq.reflCongr (ih sigma)
  | eqJMotive r b p _ ih =>
      exact DefEq.eqJMotive
        (subst sigma r) (subst sigma b) (subst sigma p)
        (ih (Sub.lift (Sub.lift sigma)))
  | eqJRefl M b p _ ih =>
      exact DefEq.eqJRefl
        (subst (Sub.lift (Sub.lift sigma)) M)
        (subst sigma b) (subst sigma p) (ih sigma)
  | eqJEndpoint M r p _ ih =>
      exact DefEq.eqJEndpoint
        (subst (Sub.lift (Sub.lift sigma)) M)
        (subst sigma r) (subst sigma p) (ih sigma)
  | eqJProof M r b _ ih =>
      exact DefEq.eqJProof
        (subst (Sub.lift (Sub.lift sigma)) M)
        (subst sigma r) (subst sigma b) (ih sigma)

/-- Pointwise source equality between simultaneous substitutions. -/
abbrev SubDefEq {n m : Nat} (sigma tau : Sub n m) : Prop :=
  forall i, DefEq (sigma i) (tau i)

/-- Pointwise equality is preserved by explicit binder lifting. -/
theorem lift_subDefEq {n m : Nat} {sigma tau : Sub n m}
    (h : SubDefEq sigma tau) :
    SubDefEq (Sub.lift sigma) (Sub.lift tau) := by
  intro i
  refine Fin.cases ?_ (fun j => ?_) i
  · exact DefEq.refl (.var 0)
  · simpa only [Sub.lift_succ, subst_ofRen] using
      (DefEq.substitution (h j) (Sub.ofRen (Ren.wk m)))

/-- Simultaneous substitution is congruent in all of its images.  Together with
`DefEq.substitution`, this proves well-definedness in both the term
representative and the environment representative. -/
theorem subst_congr {n m : Nat} {sigma tau : Sub n m}
    (h : SubDefEq sigma tau) (t : Expr n) :
    DefEq (subst sigma t) (subst tau t) := by
  induction t generalizing m with
  | var i => exact h i
  | sort level => exact DefEq.refl _
  | pi A B ihA ihB =>
      exact DefEq.trans
        (DefEq.piDom _ (ihA h))
        (DefEq.piCod _ (ihB (lift_subDefEq h)))
  | sigma A B ihA ihB =>
      exact DefEq.trans
        (DefEq.sigmaDom _ (ihA h))
        (DefEq.sigmaCod _ (ihB (lift_subDefEq h)))
  | lam body ih =>
      exact DefEq.lamBody (ih (lift_subDefEq h))
  | app f a ihf iha =>
      exact DefEq.trans (DefEq.appFun (ihf h)) (DefEq.appArg (iha h))
  | pair a b iha ihb =>
      exact DefEq.trans (DefEq.pairFst (iha h)) (DefEq.pairSnd (ihb h))
  | fst p ih => exact DefEq.fstCongr (ih h)
  | snd p ih => exact DefEq.sndCongr (ih h)
  | nat level => exact DefEq.refl _
  | zero level => exact DefEq.refl _
  | succ level t ih => exact DefEq.succCongr level (ih h)
  | natElim level motive zeroCase succCase scrutinee ihm ihz ihs ihn =>
      exact DefEq.trans
        (DefEq.natMotive level _ _ _ (ihm (lift_subDefEq h)))
        (DefEq.trans
          (DefEq.natZero level _ _ _ (ihz h))
          (DefEq.trans
            (DefEq.natSucc level _ _ _ (ihs
              (lift_subDefEq (lift_subDefEq h))))
            (DefEq.natScrutinee level _ _ _ (ihn h))))
  | codeNat level => exact DefEq.refl _
  | codePi A B ihA ihB =>
      exact DefEq.trans
        (DefEq.codePiDom _ (ihA h))
        (DefEq.codePiCod _ (ihB (lift_subDefEq h)))
  | codeSigma A B ihA ihB =>
      exact DefEq.trans
        (DefEq.codeSigmaDom _ (ihA h))
        (DefEq.codeSigmaCod _ (ihB (lift_subDefEq h)))
  | codeId A a b ihA iha ihb =>
      exact DefEq.trans
        (DefEq.codeIdType (ihA h))
        (DefEq.trans (DefEq.codeIdLeft (iha h))
          (DefEq.codeIdRight (ihb h)))
  | el code ih => exact DefEq.elCongr (ih h)
  | id A a b ihA iha ihb =>
      exact DefEq.trans
        (DefEq.idType (ihA h))
        (DefEq.trans (DefEq.idLeft (iha h)) (DefEq.idRight (ihb h)))
  | refl a ih => exact DefEq.reflCongr (ih h)
  | eqJ motive reflCase endpoint proof ihm ihr ihe ihp =>
      exact DefEq.trans
        (DefEq.eqJMotive _ _ _ (ihm
          (lift_subDefEq (lift_subDefEq h))))
        (DefEq.trans
          (DefEq.eqJRefl _ _ _ (ihr h))
          (DefEq.trans
            (DefEq.eqJEndpoint _ _ _ (ihe h))
            (DefEq.eqJProof _ _ _ (ihp h))))

/-- One-variable instantiation is congruent in its argument. -/
theorem instantiate_congr {n : Nat} (body : Expr (n + 1))
    {a a' : Expr n} (h : DefEq a a') :
    DefEq (instantiate body a) (instantiate body a') := by
  apply subst_congr (t := body)
  intro i
  refine Fin.cases h (fun j => DefEq.refl (.var j)) i

/-- Two-variable instantiation is congruent in both supplied expressions. -/
theorem instantiate₂_congr {n : Nat} (body : Expr (n + 2))
    {a a' p p' : Expr n} (ha : DefEq a a') (hp : DefEq p p') :
    DefEq (instantiate₂ body a p) (instantiate₂ body a' p') := by
  apply subst_congr (t := body)
  intro i
  refine Fin.cases hp (fun j => ?_) i
  refine Fin.cases ha (fun k => DefEq.refl (.var k)) j

end DefEq

/-! ## Derived subject reduction -/

/-- Subject reduction modulo source definitional equality.  The target type is
derived from the typing premises; `typeCoherence` relates it to the source
type when dependent elimination changes the displayed type (notably `snd`). -/
structure SubjectReduction {n : Nat} {Gamma : Ctx n}
    {source target : Expr n} (d : TypedComputation Gamma source target) where
  targetType : Expr n
  targetTyping : HasType Gamma target targetType
  typeCoherence : DefEq targetType d.type

/-- Every claimed primitive computation rule preserves typing.

No target-typing premise is assumed.  Product and natural-number beta use the
proved one- and two-variable typing substitution lemmas; the dependent second
projection is preserved modulo the source `fst` beta equality; universe-code
computations use the corrected level-indexed natural type and code formation
rules. -/
noncomputable def subject_reduction {n : Nat} {Gamma : Ctx n}
    {source target : Expr n} (d : TypedComputation Gamma source target) :
    SubjectReduction d := by
  rcases d with ⟨sourceType, sourceTyping, computation⟩
  cases computation with
  | piBeta body argument =>
      cases sourceTyping with
      | appElim hLam hArg =>
          cases hLam with
          | lamIntro hA hB hBody =>
              exact
                { targetType := _
                  targetTyping :=
                    HasType.instantiate_preserves hBody hArg
                  typeCoherence := DefEq.refl _ }
  | sigmaFstBeta a b =>
      cases sourceTyping with
      | fstElim hPair =>
          cases hPair with
          | pairIntro ha hb =>
              exact
                { targetType := _
                  targetTyping := ha
                  typeCoherence := DefEq.refl _ }
  | sigmaSndBeta a b =>
      cases sourceTyping with
      | sndElim hPair =>
          cases hPair with
          | pairIntro ha hb =>
              exact
                { targetType := _
                  targetTyping := hb
                  typeCoherence :=
                    DefEq.instantiate_congr _
                      (DefEq.symm
                        (DefEq.beta
                          (Computation.sigmaFstBeta a target))) }
  | natZeroBeta natLevel motive zeroCase succCase =>
      cases sourceTyping with
      | natElim hM hZero hSucc hScrutinee =>
          exact
            { targetType := _
              targetTyping := hZero
              typeCoherence := DefEq.refl _ }
  | natSuccBeta natLevel motive zeroCase succCase k =>
      cases sourceTyping with
      | natElim hM hZero hSucc hScrutinee =>
          cases hScrutinee with
          | succIntro _ hk =>
              have hRec :
                  HasType Gamma
                    (.natElim natLevel motive zeroCase succCase k)
                    (instantiate motive k) :=
                HasType.natElim hM hZero hSucc hk
              have hTarget :=
                HasType.instantiate₂_preserves hSucc hk hRec
              rw [natStepTarget_instantiate] at hTarget
              exact
                { targetType := _
                  targetTyping := hTarget
                  typeCoherence := DefEq.refl _ }
  | eqJBeta motive reflCase a =>
      cases sourceTyping with
      | eqJElim hA ha hM hRefl hEndpoint hProof =>
          cases hProof with
          | reflIntro hProofBase =>
              exact
                { targetType := _
                  targetTyping := hRefl
                  typeCoherence := DefEq.refl _ }
  | elNatBeta level =>
      cases sourceTyping with
      | elForm hCode =>
          cases hCode with
          | codeNatIntro _ =>
              exact
                { targetType := _
                  targetTyping := HasType.natForm level
                  typeCoherence := DefEq.refl _ }
  | elPiBeta A B =>
      cases sourceTyping with
      | elForm hCode =>
          cases hCode with
          | codePiIntro hA hB =>
              exact
                { targetType := _
                  targetTyping :=
                    HasType.piForm
                      (HasType.elForm hA) (HasType.elForm hB)
                  typeCoherence := DefEq.refl _ }
  | elSigmaBeta A B =>
      cases sourceTyping with
      | elForm hCode =>
          cases hCode with
          | codeSigmaIntro hA hB =>
              exact
                { targetType := _
                  targetTyping :=
                    HasType.sigmaForm
                      (HasType.elForm hA) (HasType.elForm hB)
                  typeCoherence := DefEq.refl _ }
  | elIdBeta A a b =>
      cases sourceTyping with
      | elForm hCode =>
          cases hCode with
          | codeIdIntro hA ha hb =>
              exact
                { targetType := _
                  targetTyping :=
                    HasType.idForm (HasType.elForm hA) ha hb
                  typeCoherence := DefEq.refl _ }

/-- Canonical typed decoding computation for the lifted natural type at any
predicative level. -/
def liftedNatDecodeComputation {n : Nat} (Gamma : Ctx n)
    (level : Nat) :
    TypedComputation Gamma (.el (.codeNat level)) (.nat level) where
  type := .sort level
  sourceTyping := HasType.elForm (HasType.codeNatIntro level)
  computation := Computation.elNatBeta level

/-- Decoding the natural code is type preserving at every level, as an explicit
instance of the general subject-reduction theorem. -/
noncomputable def liftedNatDecode_subject_reduction
    {n : Nat} (Gamma : Ctx n) (level : Nat) :
    SubjectReduction (liftedNatDecodeComputation Gamma level) :=
  subject_reduction (liftedNatDecodeComputation Gamma level)

/-- The source term model is quotiented only by `DefEq`; no target rewrite rule
is included in this setoid. -/
def exprSetoid (n : Nat) : Setoid (Expr n) where
  r := DefEq
  iseqv :=
    { refl := DefEq.refl
      symm := DefEq.symm
      trans := DefEq.trans }

/-! ## Computational-path evidence for typed source reduction -/

/-- The raw term-model carrier is the quotient by source definitional
equality. -/
abbrev TermModel (n : Nat) := Quotient (exprSetoid n)

/-- Quote a raw expression into the source term model. -/
def denote {n : Nat} (t : Expr n) : TermModel n :=
  Quot.mk _ t

/-- A source definitional equality produces an explicit computational path in
the term model. -/
noncomputable def defEqPath {n : Nat} {t u : Expr n} (h : DefEq t u) :
    Path (denote t) (denote u) :=
  Path.stepChain (Quotient.sound h)

/-- Primitive source computation produces a visible beta path. -/
noncomputable def computationPath {n : Nat} {t u : Expr n}
    (h : Computation t u) : Path (denote t) (denote u) :=
  defEqPath (DefEq.beta h)

/-- Substantive certificate attached to a typed source computation.

Unlike the former reflexive derivation trace, `betaPath` connects the actual
source redex and contractum.  `subjectReduction` is derived, while
`roundTripCancellation` and `reassociateCancellation` certify two nontrivial
groupoid reductions of that beta path. -/
structure ComputationPathCertificate {n : Nat} {Gamma : Ctx n}
    {source target : Expr n} (d : TypedComputation Gamma source target) where
  subjectReduction : SubjectReduction d
  betaPath : Path (denote source) (denote target)
  roundTripCancellation :
    RwEq
      (Path.trans betaPath (Path.symm betaPath))
      (Path.refl (denote source))
  reassociateCancellation :
    RwEq
      (Path.trans
        (Path.trans betaPath (Path.symm betaPath))
        betaPath)
      betaPath

/-- Construct the computational certificate from subject reduction and the
actual source beta step. -/
noncomputable def computationPathCertificate
    {n : Nat} {Gamma : Ctx n} {source target : Expr n}
    (d : TypedComputation Gamma source target) :
    ComputationPathCertificate d := by
  let p := computationPath d.computation
  exact
    { subjectReduction := subject_reduction d
      betaPath := p
      roundTripCancellation :=
        rweq_of_step (Path.Step.trans_symm p)
      reassociateCancellation :=
        rweq_trans
          (rweq_of_step
            (Path.Step.trans_assoc p (Path.symm p) p))
          (rweq_trans
            (rweq_trans_congr_right p
              (rweq_of_step (Path.Step.symm_trans p)))
            (rweq_of_step (Path.Step.trans_refl_right p))) }

end RawMLTT
end TypeTheory
end Path
end ComputationalPaths
