/-
# Raw typing and computation judgments for bounded MLTT

This module presents the rules of the source calculus over the independently
scoped syntax from `RawSyntax`.  The judgments are intentionally conservative:
there is no conversion rule that can import a target equality witness, and the
only definitional equalities are generated by the source beta rules and their
source-language congruence closure.

The formation, introduction, elimination, and computation rules cover:

* predicative Tarski universes and decoding;
* dependent products and sums;
* lifted natural numbers and their dependent recursor;
* identity formation/reflexivity; and
* an equality-factored `J` whose motive binds only an endpoint and a source
  identity proof.

`Computation` is the untyped operational layer.  `TypedComputation` records the
common source type and is therefore a machine-checked preservation certificate,
not an assertion that every untyped redex is well typed.  This separation makes
the exact domain of the later semantic soundness theorem explicit.
-/

import ComputationalPaths.Path.TypeTheory.RawSyntax

namespace ComputationalPaths
namespace Path
namespace TypeTheory
namespace RawMLTT

/-! ## Derived binder operations -/

/-- Weakening of an expression by one fresh variable. -/
def weaken {n : Nat} (t : Expr n) : Expr (n + 1) :=
  rename (Ren.wk n) t

/-- Weakening by two fresh variables. -/
def weaken₂ {n : Nat} (t : Expr n) : Expr (n + 2) :=
  rename (Ren.comp (Ren.wk n) (Ren.wk (n + 1))) t

/-- Context in which the natural-number successor branch is checked: the first
extension binds the predecessor and the second binds the induction hypothesis. -/
def natStepCtx {n : Nat} (Gamma : Ctx n) (motive : Expr (n + 1)) :
    Ctx (n + 2) :=
  Ctx.extend (Ctx.extend Gamma (.nat : Expr n)) motive

/-- The target of the natural-number successor branch.  Index zero in `motive`
is replaced by `succ` of the predecessor (index one); ambient variables are
shifted across both branch binders. -/
def natStepTarget {n : Nat} (motive : Expr (n + 1)) : Expr (n + 2) :=
  subst
    (fun i => Fin.cases
      (.succ (.var (Fin.succ (0 : Fin (n + 1)))))
      (fun j => .var (Fin.succ (Fin.succ j))) i)
    motive

/-- Context for the equality-factored motive.  The first new variable is the
endpoint; the second is a proof of identity from the fixed base point. -/
def eqMotiveCtx {n : Nat} (Gamma : Ctx n) (A a : Expr n) :
    Ctx (n + 2) :=
  Ctx.extend (Ctx.extend Gamma A)
    (.id (weaken A) (weaken a) (.var 0))

/-! ## Typing judgment -/

/-- Raw typing derivations for the bounded fragment.

Universe levels are natural numbers.  A code in `sort level` decodes to a type
in the same level, while the universe itself lives in its successor.  Product,
sum, and identity formation are level-preserving in this bounded presentation. -/
inductive HasType : {n : Nat} -> Ctx n -> Expr n -> Expr n -> Type where
  | var {n : Nat} {Gamma : Ctx n} (i : Fin n) :
      HasType Gamma (.var i) (Gamma i)
  | sort {n : Nat} {Gamma : Ctx n} (level : Nat) :
      HasType Gamma (.sort level) (.sort (level + 1))
  | piForm {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma A) B (.sort level) ->
      HasType Gamma (.pi A B) (.sort level)
  | sigmaForm {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma A) B (.sort level) ->
      HasType Gamma (.sigma A B) (.sort level)
  | lamIntro {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B body : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma A) B (.sort level) ->
      HasType (Ctx.extend Gamma A) body B ->
      HasType Gamma (.lam body) (.pi A B)
  | appElim {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {f a : Expr n} :
      HasType Gamma f (.pi A B) ->
      HasType Gamma a A ->
      HasType Gamma (.app f a) (instantiate B a)
  | pairIntro {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {a b : Expr n} :
      HasType Gamma a A ->
      HasType Gamma b (instantiate B a) ->
      HasType Gamma (.pair a b) (.sigma A B)
  | fstElim {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {p : Expr n} :
      HasType Gamma p (.sigma A B) ->
      HasType Gamma (.fst p) A
  | sndElim {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {p : Expr n} :
      HasType Gamma p (.sigma A B) ->
      HasType Gamma (.snd p) (instantiate B (.fst p))
  | natForm {n : Nat} {Gamma : Ctx n} :
      HasType Gamma .nat (.sort 0)
  | zeroIntro {n : Nat} {Gamma : Ctx n} :
      HasType Gamma .zero .nat
  | succIntro {n : Nat} {Gamma : Ctx n} {t : Expr n} :
      HasType Gamma t .nat ->
      HasType Gamma (.succ t) .nat
  | natElim {n : Nat} {Gamma : Ctx n} {motive : Expr (n + 1)}
      {zeroCase scrutinee : Expr n} {succCase : Expr (n + 2)}
      {level : Nat} :
      HasType (Ctx.extend Gamma .nat) motive (.sort level) ->
      HasType Gamma zeroCase (instantiate motive .zero) ->
      HasType (natStepCtx Gamma motive) succCase (natStepTarget motive) ->
      HasType Gamma scrutinee .nat ->
      HasType Gamma (.natElim motive zeroCase succCase scrutinee)
        (instantiate motive scrutinee)
  | codeNatIntro {n : Nat} {Gamma : Ctx n} (level : Nat) :
      HasType Gamma (.codeNat level) (.sort level)
  | codePiIntro {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma (.el A)) B (.sort level) ->
      HasType Gamma (.codePi A B) (.sort level)
  | codeSigmaIntro {n : Nat} {Gamma : Ctx n} {A : Expr n}
      {B : Expr (n + 1)} {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType (Ctx.extend Gamma (.el A)) B (.sort level) ->
      HasType Gamma (.codeSigma A B) (.sort level)
  | codeIdIntro {n : Nat} {Gamma : Ctx n} {A a b : Expr n}
      {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType Gamma a (.el A) ->
      HasType Gamma b (.el A) ->
      HasType Gamma (.codeId A a b) (.sort level)
  | elForm {n : Nat} {Gamma : Ctx n} {code : Expr n} {level : Nat} :
      HasType Gamma code (.sort level) ->
      HasType Gamma (.el code) (.sort level)
  | idForm {n : Nat} {Gamma : Ctx n} {A a b : Expr n}
      {level : Nat} :
      HasType Gamma A (.sort level) ->
      HasType Gamma a A ->
      HasType Gamma b A ->
      HasType Gamma (.id A a b) (.sort level)
  | reflIntro {n : Nat} {Gamma : Ctx n} {A a : Expr n} :
      HasType Gamma a A ->
      HasType Gamma (.refl a) (.id A a a)
  | eqJElim {n : Nat} {Gamma : Ctx n} {A a : Expr n}
      {motive : Expr (n + 2)} {reflCase endpoint proof : Expr n}
      {level motiveLevel : Nat} :
      HasType Gamma A (.sort level) ->
      HasType Gamma a A ->
      HasType (eqMotiveCtx Gamma A a) motive (.sort motiveLevel) ->
      HasType Gamma reflCase (instantiate₂ motive a (.refl a)) ->
      HasType Gamma endpoint A ->
      HasType Gamma proof (.id A a endpoint) ->
      HasType Gamma (.eqJ motive reflCase endpoint proof)
        (instantiate₂ motive endpoint proof)

/-! ## Source computation and definitional equality -/

/-- Primitive source computation rules.  These constructors mention only raw
syntax; in particular, they cannot receive a `Path.Step` or `RwEq` witness. -/
inductive Computation : {n : Nat} -> Expr n -> Expr n -> Prop where
  | piBeta {n : Nat} (body : Expr (n + 1)) (argument : Expr n) :
      Computation (.app (.lam body) argument) (instantiate body argument)
  | sigmaFstBeta {n : Nat} (a b : Expr n) :
      Computation (.fst (.pair a b)) a
  | sigmaSndBeta {n : Nat} (a b : Expr n) :
      Computation (.snd (.pair a b)) b
  | natZeroBeta {n : Nat} (motive : Expr (n + 1))
      (zeroCase : Expr n) (succCase : Expr (n + 2)) :
      Computation (.natElim motive zeroCase succCase .zero) zeroCase
  | natSuccBeta {n : Nat} (motive : Expr (n + 1))
      (zeroCase : Expr n) (succCase : Expr (n + 2)) (k : Expr n) :
      Computation
        (.natElim motive zeroCase succCase (.succ k))
        (instantiate₂ succCase k
          (.natElim motive zeroCase succCase k))
  | eqJBeta {n : Nat} (motive : Expr (n + 2))
      (reflCase a : Expr n) :
      Computation
        (.eqJ motive reflCase a (.refl a))
        reflCase
  | elNatBeta {n : Nat} (level : Nat) :
      Computation (.el (.codeNat level) : Expr n) .nat
  | elPiBeta {n : Nat} (A : Expr n) (B : Expr (n + 1)) :
      Computation (.el (.codePi A B)) (.pi (.el A) (.el B))
  | elSigmaBeta {n : Nat} (A : Expr n) (B : Expr (n + 1)) :
      Computation (.el (.codeSigma A B)) (.sigma (.el A) (.el B))
  | elIdBeta {n : Nat} (A a b : Expr n) :
      Computation (.el (.codeId A a b)) (.id (.el A) a b)

namespace Computation

/-- Primitive computation is stable under every simultaneous substitution.
The binder cases use the independently proved one- and two-variable
instantiation laws. -/
theorem substitution {n m : Nat} (sigma : Sub n m)
    {t u : Expr n} (h : Computation t u) :
    Computation (subst sigma t) (subst sigma u) := by
  cases h with
  | piBeta body argument =>
      simpa using
        (Computation.piBeta
          (subst (Sub.lift sigma) body) (subst sigma argument))
  | sigmaFstBeta a b =>
      exact Computation.sigmaFstBeta (subst sigma u) (subst sigma b)
  | sigmaSndBeta a b =>
      exact Computation.sigmaSndBeta (subst sigma a) (subst sigma u)
  | natZeroBeta motive zeroCase succCase =>
      exact Computation.natZeroBeta
        (subst (Sub.lift sigma) motive)
        (subst sigma u)
        (subst (Sub.lift (Sub.lift sigma)) succCase)
  | natSuccBeta motive zeroCase succCase k =>
      simpa using
        (Computation.natSuccBeta
          (subst (Sub.lift sigma) motive)
          (subst sigma zeroCase)
          (subst (Sub.lift (Sub.lift sigma)) succCase)
          (subst sigma k))
  | eqJBeta motive reflCase a =>
      exact Computation.eqJBeta
        (subst (Sub.lift (Sub.lift sigma)) motive)
        (subst sigma u) (subst sigma a)
  | elNatBeta level =>
      exact Computation.elNatBeta level
  | elPiBeta A B =>
      exact Computation.elPiBeta
        (subst sigma A) (subst (Sub.lift sigma) B)
  | elSigmaBeta A B =>
      exact Computation.elSigmaBeta
        (subst sigma A) (subst (Sub.lift sigma) B)
  | elIdBeta A a b =>
      exact Computation.elIdBeta
        (subst sigma A) (subst sigma a) (subst sigma b)

end Computation

/-- Typed computation certificates state both sides at one common raw type.
This is the exact typed domain used by semantic computation soundness. -/
structure TypedComputation {n : Nat} (Gamma : Ctx n)
    (source target : Expr n) where
  type : Expr n
  sourceTyping : HasType Gamma source type
  targetTyping : HasType Gamma target type
  computation : Computation source target

/-- A typed computation preserves its source type by construction. -/
def TypedComputation.preservation {n : Nat} {Gamma : Ctx n}
    {source target : Expr n} (d : TypedComputation Gamma source target) :
    HasType Gamma target d.type :=
  d.targetTyping

/-- Source definitional equality: equivalence and compatible closure of the
primitive computation rules.  Congruence is enumerated by raw constructors,
making the supported closure auditable. -/
inductive DefEq : {n : Nat} -> Expr n -> Expr n -> Prop where
  | beta {n : Nat} {t u : Expr n} : Computation t u -> DefEq t u
  | refl {n : Nat} (t : Expr n) : DefEq t t
  | symm {n : Nat} {t u : Expr n} : DefEq t u -> DefEq u t
  | trans {n : Nat} {t u v : Expr n} :
      DefEq t u -> DefEq u v -> DefEq t v
  | piDom {n : Nat} {A A' : Expr n} (B : Expr (n + 1)) :
      DefEq A A' -> DefEq (.pi A B) (.pi A' B)
  | piCod {n : Nat} (A : Expr n) {B B' : Expr (n + 1)} :
      DefEq B B' -> DefEq (.pi A B) (.pi A B')
  | sigmaDom {n : Nat} {A A' : Expr n} (B : Expr (n + 1)) :
      DefEq A A' -> DefEq (.sigma A B) (.sigma A' B)
  | sigmaCod {n : Nat} (A : Expr n) {B B' : Expr (n + 1)} :
      DefEq B B' -> DefEq (.sigma A B) (.sigma A B')
  | lamBody {n : Nat} {body body' : Expr (n + 1)} :
      DefEq body body' -> DefEq (.lam body) (.lam body')
  | appFun {n : Nat} {f f' a : Expr n} :
      DefEq f f' -> DefEq (.app f a) (.app f' a)
  | appArg {n : Nat} {f a a' : Expr n} :
      DefEq a a' -> DefEq (.app f a) (.app f a')
  | pairFst {n : Nat} {a a' b : Expr n} :
      DefEq a a' -> DefEq (.pair a b) (.pair a' b)
  | pairSnd {n : Nat} {a b b' : Expr n} :
      DefEq b b' -> DefEq (.pair a b) (.pair a b')
  | fstCongr {n : Nat} {p p' : Expr n} :
      DefEq p p' -> DefEq (.fst p) (.fst p')
  | sndCongr {n : Nat} {p p' : Expr n} :
      DefEq p p' -> DefEq (.snd p) (.snd p')
  | succCongr {n : Nat} {t t' : Expr n} :
      DefEq t t' -> DefEq (.succ t) (.succ t')
  | natMotive {n : Nat} {M M' : Expr (n + 1)}
      (z : Expr n) (s : Expr (n + 2)) (t : Expr n) :
      DefEq M M' ->
      DefEq (.natElim M z s t) (.natElim M' z s t)
  | natZero {n : Nat} (M : Expr (n + 1)) {z z' : Expr n}
      (s : Expr (n + 2)) (t : Expr n) :
      DefEq z z' ->
      DefEq (.natElim M z s t) (.natElim M z' s t)
  | natSucc {n : Nat} (M : Expr (n + 1)) (z : Expr n)
      {s s' : Expr (n + 2)} (t : Expr n) :
      DefEq s s' ->
      DefEq (.natElim M z s t) (.natElim M z s' t)
  | natScrutinee {n : Nat} (M : Expr (n + 1)) (z : Expr n)
      (s : Expr (n + 2)) {t t' : Expr n} :
      DefEq t t' ->
      DefEq (.natElim M z s t) (.natElim M z s t')
  | codePiDom {n : Nat} {A A' : Expr n} (B : Expr (n + 1)) :
      DefEq A A' -> DefEq (.codePi A B) (.codePi A' B)
  | codePiCod {n : Nat} (A : Expr n) {B B' : Expr (n + 1)} :
      DefEq B B' -> DefEq (.codePi A B) (.codePi A B')
  | codeSigmaDom {n : Nat} {A A' : Expr n} (B : Expr (n + 1)) :
      DefEq A A' -> DefEq (.codeSigma A B) (.codeSigma A' B)
  | codeSigmaCod {n : Nat} (A : Expr n) {B B' : Expr (n + 1)} :
      DefEq B B' -> DefEq (.codeSigma A B) (.codeSigma A B')
  | codeIdType {n : Nat} {A A' a b : Expr n} :
      DefEq A A' -> DefEq (.codeId A a b) (.codeId A' a b)
  | codeIdLeft {n : Nat} {A a a' b : Expr n} :
      DefEq a a' -> DefEq (.codeId A a b) (.codeId A a' b)
  | codeIdRight {n : Nat} {A a b b' : Expr n} :
      DefEq b b' -> DefEq (.codeId A a b) (.codeId A a b')
  | elCongr {n : Nat} {code code' : Expr n} :
      DefEq code code' -> DefEq (.el code) (.el code')
  | idType {n : Nat} {A A' a b : Expr n} :
      DefEq A A' -> DefEq (.id A a b) (.id A' a b)
  | idLeft {n : Nat} {A a a' b : Expr n} :
      DefEq a a' -> DefEq (.id A a b) (.id A a' b)
  | idRight {n : Nat} {A a b b' : Expr n} :
      DefEq b b' -> DefEq (.id A a b) (.id A a b')
  | reflCongr {n : Nat} {a a' : Expr n} :
      DefEq a a' -> DefEq (.refl a) (.refl a')
  | eqJMotive {n : Nat} {M M' : Expr (n + 2)}
      (r b p : Expr n) :
      DefEq M M' -> DefEq (.eqJ M r b p) (.eqJ M' r b p)
  | eqJRefl {n : Nat} (M : Expr (n + 2)) {r r' : Expr n}
      (b p : Expr n) :
      DefEq r r' -> DefEq (.eqJ M r b p) (.eqJ M r' b p)
  | eqJEndpoint {n : Nat} (M : Expr (n + 2)) (r : Expr n)
      {b b' : Expr n} (p : Expr n) :
      DefEq b b' -> DefEq (.eqJ M r b p) (.eqJ M r b' p)
  | eqJProof {n : Nat} (M : Expr (n + 2)) (r b : Expr n)
      {p p' : Expr n} :
      DefEq p p' -> DefEq (.eqJ M r b p) (.eqJ M r b p')

/-- The source term model is quotiented only by `DefEq`; no target rewrite rule
is included in this setoid. -/
def exprSetoid (n : Nat) : Setoid (Expr n) where
  r := DefEq
  iseqv :=
    { refl := DefEq.refl
      symm := DefEq.symm
      trans := DefEq.trans }

/-! ## A nontrivial trace on typing evidence -/

/-- A typing derivation supports an explicit two-segment reflexive trace and a
rewrite certificate reducing its trailing unit.  This integrates structural
typing evidence with the computational-path calculus without identifying raw
typing with target equality. -/
structure JudgmentTraceCertificate {n : Nat} {Gamma : Ctx n}
    {t A : Expr n} (d : HasType Gamma t A) where
  oneStep : Path d d
  twoSegment : Path d d
  unitCoherence : RwEq twoSegment oneStep

/-- Construct the trace certificate.  `oneStep` retains a visible source
derivation trace, and `twoSegment` is a genuine `Path.trans` composition. -/
noncomputable def judgmentTraceCertificate {n : Nat} {Gamma : Ctx n}
    {t A : Expr n} (d : HasType Gamma t A) :
    JudgmentTraceCertificate d := by
  let p : Path d d := Path.stepChain rfl
  exact
    { oneStep := p
      twoSegment := Path.trans p (Path.refl d)
      unitCoherence := rweq_of_step (Path.Step.trans_refl_right p) }

end RawMLTT
end TypeTheory
end Path
end ComputationalPaths
