import Mathlib.Algebra.Free

/-!
# Proof-relevant associativity coherence for free magmas

This Palomar challenge isolates a standard, externally grounded rewrite
problem. The objects are Mathlib's `FreeMagma` trees. A directed step is one
associativity rotation, closed under both binary contexts. The selected
theorems ask for termination, canonical normalization, global confluence,
semantic completeness against both `FreeSemigroup` and Mathlib's standard
associativity quotient, and two genuinely distinct traces around Mac Lane's
pentagon.

Only the eight theorem bodies marked `sorry` are omitted. Every datatype,
measure, normal form, trace, and theorem statement is fully visible here.
-/

namespace ComputationalPaths.Path.PalomarAssociativity

universe u

/-- One directed associativity rewrite, closed under both binary contexts. -/
inductive AssocStep {α : Type u} : FreeMagma α → FreeMagma α → Type u where
  | rotate (x y z : FreeMagma α) : AssocStep ((x * y) * z) (x * (y * z))
  | congrLeft {x x' : FreeMagma α} (h : AssocStep x x') (y : FreeMagma α) :
      AssocStep (x * y) (x' * y)
  | congrRight (x : FreeMagma α) {y y' : FreeMagma α} (h : AssocStep y y') :
      AssocStep (x * y) (x * y')

/-- Proof-relevant reflexive-transitive closure of directed reassociation. -/
inductive AssocReduces {α : Type u} : FreeMagma α → FreeMagma α → Type u where
  | refl (x : FreeMagma α) : AssocReduces x x
  | step {x y : FreeMagma α} (h : AssocStep x y) : AssocReduces x y
  | trans {x y z : FreeMagma α} (h₁ : AssocReduces x y)
      (h₂ : AssocReduces y z) : AssocReduces x z

/-- Proof-relevant symmetric rewrite equality generated by associativity. -/
inductive AssocRwEq {α : Type u} : FreeMagma α → FreeMagma α → Type u where
  | refl (x : FreeMagma α) : AssocRwEq x x
  | step {x y : FreeMagma α} (h : AssocStep x y) : AssocRwEq x y
  | symm {x y : FreeMagma α} (h : AssocRwEq x y) : AssocRwEq y x
  | trans {x y z : FreeMagma α} (h₁ : AssocRwEq x y)
      (h₂ : AssocRwEq y z) : AssocRwEq x z

/-- The standard semantic word of a parenthesized term. -/
abbrev word {α : Type u} : FreeMagma α → FreeSemigroup α :=
  FreeMagma.toFreeSemigroup

/-- The canonical fully right-associated tree of a head and a tail word. -/
def rightCombAux {α : Type u} (head : α) : List α → FreeMagma α
  | [] => FreeMagma.of head
  | next :: tail => FreeMagma.of head * rightCombAux next tail

/-- The canonical fully right-associated tree of a nonempty word. -/
def rightComb {α : Type u} (w : FreeSemigroup α) : FreeMagma α :=
  rightCombAux w.head w.tail

/-- Number of leaves in a free-magma tree. -/
def leafCount {α : Type u} : FreeMagma α → Nat
  | .of _ => 1
  | x * y => leafCount x + leafCount y

/-- A right-rotation measure: every directed associativity step decreases it. -/
def assocWeight {α : Type u} : FreeMagma α → Nat
  | .of _ => 0
  | x * y => assocWeight x + assocWeight y + leafCount x

namespace AssocReduces

/-- Embed a reduction trace in a fixed left context. -/
def congrLeft {α : Type u} {x x' : FreeMagma α}
    (h : AssocReduces x x') (y : FreeMagma α) :
    AssocReduces (x * y) (x' * y) :=
  match h with
  | .refl _ => .refl _
  | .step s => .step (.congrLeft s y)
  | .trans h₁ h₂ => .trans (congrLeft h₁ y) (congrLeft h₂ y)

/-- Embed a reduction trace in a fixed right context. -/
def congrRight {α : Type u} (x : FreeMagma α)
    {y y' : FreeMagma α} (h : AssocReduces y y') :
    AssocReduces (x * y) (x * y') :=
  match h with
  | .refl _ => .refl _
  | .step s => .step (.congrRight x s)
  | .trans h₁ h₂ => .trans (congrRight x h₁) (congrRight x h₂)

/-- Forget direction while retaining the proof-relevant trace syntax. -/
def toRwEq {α : Type u} {x y : FreeMagma α} :
    AssocReduces x y → AssocRwEq x y
  | .refl _ => .refl _
  | .step s => .step s
  | .trans h₁ h₂ => .trans (toRwEq h₁) (toRwEq h₂)

/-- Number of primitive rewrites in a reduction trace. -/
def stepCount {α : Type u} {x y : FreeMagma α} :
    AssocReduces x y → Nat
  | .refl _ => 0
  | .step _ => 1
  | .trans h₁ h₂ => stepCount h₁ + stepCount h₂

end AssocReduces

/-- A common reduct together with both proof-relevant reduction traces. -/
structure AssocJoin {α : Type u} (x y : FreeMagma α) where
  target : FreeMagma α
  left : AssocReduces x target
  right : AssocReduces y target

/-- Directed associativity rewriting admits no infinite reduction sequence. -/
theorem assocStep_wellFounded (α : Type u) :
    WellFounded (fun y x : FreeMagma α => Nonempty (AssocStep x y)) := by
  sorry

/-- Every tree explicitly reduces to the right comb of its semantic word. -/
theorem assoc_normalizes {α : Type u} (x : FreeMagma α) :
    Nonempty (AssocReduces x (rightComb (word x))) := by
  sorry

/-- A canonical right comb has no outgoing directed associativity step. -/
theorem rightComb_irreducible {α : Type u} (w : FreeSemigroup α) :
    ∀ {y : FreeMagma α}, AssocStep (rightComb w) y → False := by
  sorry

/-- Any two reductions from a common source have a proof-relevant join. -/
theorem assoc_reduces_confluent {α : Type u} {x y z : FreeMagma α}
    (hy : AssocReduces x y) (hz : AssocReduces x z) :
    Nonempty (AssocJoin y z) := by
  sorry

/-- Rewrite equality is exactly equality of Mathlib nonempty words. -/
theorem assoc_rwEq_iff_freeSemigroup_eq {α : Type u}
    (x y : FreeMagma α) :
    Nonempty (AssocRwEq x y) ↔ word x = word y := by
  sorry

/-- Rewrite equality is exactly equality in Mathlib's associativity quotient. -/
theorem assoc_rwEq_iff_assocQuotient_eq {α : Type u}
    (x y : FreeMagma α) :
    Nonempty (AssocRwEq x y) ↔
      Magma.AssocQuotient.of x = Magma.AssocQuotient.of y := by
  sorry

/-- The two-edge side of Mac Lane's associativity pentagon. -/
def pentagonShort {α : Type u} (w x y z : FreeMagma α) :
    AssocReduces (((w * x) * y) * z) (w * (x * (y * z))) :=
  .trans
    (.step (.rotate (w * x) y z))
    (.step (.rotate w x (y * z)))

/-- The three-edge side of Mac Lane's associativity pentagon. -/
def pentagonLong {α : Type u} (w x y z : FreeMagma α) :
    AssocReduces (((w * x) * y) * z) (w * (x * (y * z))) :=
  .trans
    (.step (.congrLeft (.rotate w x y) z))
    (.trans
      (.step (.rotate w (x * y) z))
      (.step (.congrRight w (.rotate x y z))))

/-- The short and long pentagon routes contain two and three rotations. -/
theorem pentagon_route_counts {α : Type u} (w x y z : FreeMagma α) :
    AssocReduces.stepCount (pentagonShort w x y z) = 2 ∧
      AssocReduces.stepCount (pentagonLong w x y z) = 3 := by
  sorry

/-- The two same-boundary pentagon traces remain syntactically distinct. -/
theorem pentagon_routes_distinct {α : Type u} (w x y z : FreeMagma α) :
    pentagonShort w x y z ≠ pentagonLong w x y z := by
  sorry

end ComputationalPaths.Path.PalomarAssociativity
