import CompPaths.Comparison.HoTTComparison
import CompPaths.Comparison.UnivalenceAnalog
import CompPaths.Context.CongruenceClosure
-- import CompPaths.Rewriting.KnuthBendix  -- TODO: fix GTRS.Expr dependency
import CompPaths.Confluence.ConfluenceDeep
import CompPaths.Coherence.AssociativityCoherence
import CompPaths.Coherence.UnitCoherence
import CompPaths.Coherence.InverseCoherence
import CompPaths.Coherence.InterchangeLaw
import CompPaths.Context.ContextDeep
import CompPaths.CwF.CwFDeep
import CompPaths.DeformationTheory.DeformationPaths
import CompPaths.DeformationTheory.ObstructionPaths
import CompPaths.Transport.PathOverPath
import CompPaths.Transport.TransportDeep
import CompPaths.TypeFormers.UniversalProperties
import CompPaths.OmegaGroupoid.WeakGroupoidPaths
import CompPaths.OmegaGroupoid.CoherencePaths
import CompPaths.OmegaGroupoid.TwoCategoryStructure
import CompPaths.OmegaGroupoid.GroupoidProofs
import CompPaths.OmegaGroupoid.TruncationProof
import CompPaths.Examples.FundamentalGroupTorus
import CompPaths.Homotopy.VanKampen
import CompPaths.Homotopy.VanKampenApplications
import CompPaths.Homotopy.ModelStructure
import CompPaths.Homotopy.FibrationSequence
import CompPaths.Homotopy.HITDeep
import CompPaths.Homotopy.WhiteheadTheorem
import CompPaths.Homotopy.PostnikovTower
import CompPaths.Algebra.HomologicalAlgebra
import CompPaths.Algebra.MayerVietoris
import CompPaths.HIT.SuspensionDeep
import CompPaths.Category.EnrichedCategory
import CompPaths.Algebra.OperadStructure
import CompPaths.Algebra.PathAlgebra

-- Auto-wired subdirectory root modules
import CompPaths.Algebra
import CompPaths.Category
import CompPaths.Coherence
import CompPaths.Comparison
import CompPaths.Confluence
import CompPaths.Context
import CompPaths.CoveringSpace
import CompPaths.CwF
import CompPaths.DeformationTheory
import CompPaths.Examples
import CompPaths.HIT
import CompPaths.Homotopy
import CompPaths.OmegaGroupoid
import CompPaths.Rewriting
import CompPaths.Transport
import CompPaths.TypeFormers
