/-
# Scoped non-collapsing circle and torus loop quotients

The global `PathRwQuot` relation uses every path-rewrite rule, including
trace-erasing function rules.  This module instead instantiates
`ScopedCompletion.Data` on the circle loop-expression language.  Its generated
relation contains only the named completion step for this presentation.

The scoped quotient is sound and complete for winding number, hence equivalent
to `Int` and nontrivial.  The torus quotient is defined componentwise and is
equivalent to `Int × Int`.
-/

import ComputationalPaths.Path.CompPath.CircleCompPath
import ComputationalPaths.Path.Rewrite.ScopedCompletion

namespace ComputationalPaths
namespace Path
namespace CompPath

universe u

/-- Based circle expressions used by the scoped completion. -/
abbrev CircleScopedExpr : Type u :=
  CircleCompPathExpr circleCompPathBase circleCompPathBase

/-- Completed scoped circle presentation. -/
noncomputable def circleScopedCompletion :
    ScopedCompletion.Data CircleScopedExpr Int where
  encode := circleCompPathEncodeExpr'
  decode := circleCompPathLoopExprZPow
  encode_decode := circleCompPathEncodeExpr_zpow

/-- The domain-specific scoped normalization step. -/
abbrev CircleScopedStep :
    CircleScopedExpr → CircleScopedExpr → Prop :=
  ScopedCompletion.Step circleScopedCompletion

/-- Equivalence closure of the scoped circle completion step. -/
abbrev CircleScopedRwEq :
    CircleScopedExpr → CircleScopedExpr → Prop :=
  ScopedCompletion.RwEq circleScopedCompletion

/-- Exact classification of the scoped circle relation by winding number. -/
theorem circleScopedRwEq_iff_encode_eq
    {p q : CircleScopedExpr} :
    CircleScopedRwEq p q ↔
      circleCompPathEncodeExpr' p = circleCompPathEncodeExpr' q :=
  ScopedCompletion.rweq_iff_encode_eq circleScopedCompletion

/-- Non-collapsing circle loop quotient generated by the scoped relation. -/
abbrev CircleScopedPiOne : Type u :=
  ScopedCompletion.Quotient circleScopedCompletion

/-- Encode a scoped circle loop class by winding number. -/
noncomputable def circleScopedEncode : CircleScopedPiOne → Int :=
  ScopedCompletion.encodeQuot circleScopedCompletion

/-- Decode an integer as its canonical signed loop power. -/
noncomputable def circleScopedDecode : Int → CircleScopedPiOne :=
  ScopedCompletion.decodeQuot circleScopedCompletion

@[simp] theorem circleScopedEncode_decode (z : Int) :
    circleScopedEncode (circleScopedDecode z) = z :=
  ScopedCompletion.encodeQuot_decodeQuot circleScopedCompletion z

theorem circleScopedDecode_encode (x : CircleScopedPiOne) :
    circleScopedDecode (circleScopedEncode x) = x :=
  ScopedCompletion.decodeQuot_encodeQuot circleScopedCompletion x

/-- The scoped circle loop quotient is equivalent to the integers. -/
noncomputable def circleScopedPiOneEquivInt :
    SimpleEquiv CircleScopedPiOne Int :=
  ScopedCompletion.equivNormal circleScopedCompletion

/-- The identity and generator classes of the scoped quotient are distinct. -/
theorem circleScoped_zero_ne_one :
    circleScopedDecode 0 ≠ circleScopedDecode 1 :=
  ScopedCompletion.decodeQuot_ne circleScopedCompletion (by decide)

/-- Concrete Path certificate for the circle normalization step. -/
noncomputable def circleScopedNormalizationPath (p : CircleScopedExpr) :
    Path
      (circleCompPathEncodeExpr' p)
      (circleCompPathEncodeExpr'
        (circleCompPathLoopExprZPow (circleCompPathEncodeExpr' p))) :=
  ScopedCompletion.normalizationPath circleScopedCompletion p

/-- The circle normalization certificate is right-unit coherent. -/
noncomputable def circleScopedNormalizationCoherence (p : CircleScopedExpr) :
    _root_.ComputationalPaths.Path.RwEq
      (Path.trans (circleScopedNormalizationPath p)
        (Path.refl
          (circleCompPathEncodeExpr'
            (circleCompPathLoopExprZPow
              (circleCompPathEncodeExpr' p)))))
      (circleScopedNormalizationPath p) :=
  ScopedCompletion.normalizationCoherence circleScopedCompletion p

/-- Scoped torus loop quotient, defined componentwise. -/
abbrev TorusScopedPiOne : Type u :=
  CircleScopedPiOne.{u} × CircleScopedPiOne.{u}

/-- The scoped torus quotient is equivalent to `Int × Int`. -/
noncomputable def torusScopedPiOneEquivIntProd :
    SimpleEquiv TorusScopedPiOne (Int × Int) :=
  SimpleEquiv.prodBoth'
    circleScopedPiOneEquivInt
    circleScopedPiOneEquivInt

end CompPath
end Path
end ComputationalPaths
