/-
# The presented computational fundamental group of the circle

The point carrier alone cannot contain a proof-relevant loop constructor in
Lean's proof-irrelevant equality.  We therefore present the circle as a
one-vertex computational path space:

* raw paths are freely generated by integer-labelled loop edges;
* the relators compose labels by addition, remove the zero edge, and identify
  path reversal with label negation;
* homotopy is generated from these relators and the groupoid laws.

The winding map is defined only after this raw syntax and generated homotopy.
Soundness and a structural normalization proof show that the automorphism group
of the basepoint in the presented path groupoid is equivalent to `Int`.

The integer-labelled edges are a redundant but convenient presentation: the
edge labelled `1` is the usual circle generator, and every other edge is proved
homotopic to its corresponding signed power.
-/

import ComputationalPaths.Path.CompPath.CircleCompPath
import ComputationalPaths.Path.Homotopy.PresentedFundamentalGroup
import ComputationalPaths.Path.Rewrite.SimpleEquiv

namespace ComputationalPaths
namespace Path
namespace CompPath
namespace CirclePresented

open Presented

universe u

/-- Proof-relevant circle edges, indexed by their winding contribution. -/
inductive Edge : CircleCompPath.{u} → CircleCompPath.{u} → Type where
  | winding (z : Int) : Edge circleCompPathBase circleCompPathBase

/-- The one-vertex generator graph of the presented circle. -/
def graph : Presented.Graph where
  Point := CircleCompPath
  Edge := Edge

/-- The raw loop edge with winding label `z`. -/
def rawEdge (z : Int) :
    Presented.RawPath graph circleCompPathBase circleCompPathBase :=
  Presented.RawPath.edge (Edge.winding z)

/-- Circle relators: addition, the zero edge, and reversal of a labelled edge. -/
inductive Relator :
    {a b : graph.Point} →
    Presented.RawPath graph a b →
    Presented.RawPath graph a b → Prop where
  | add (m n : Int) :
      Relator
        (Presented.RawPath.trans (rawEdge m) (rawEdge n))
        (rawEdge (m + n))
  | zero :
      Relator (rawEdge 0)
        (@Presented.RawPath.refl graph circleCompPathBase)
  | neg (z : Int) :
      Relator (Presented.RawPath.symm (rawEdge z)) (rawEdge (-z))

/-- The circle path presentation. -/
def presentation : Presented.Presentation graph where
  Relator := Relator

/-- Winding number of a raw presented circle path. -/
def winding :
    {a b : graph.Point} → Presented.RawPath graph a b → Int
  | _, _, .refl _ => 0
  | _, _, .edge (.winding z) => z
  | _, _, .symm p => -(winding p)
  | _, _, .trans p q => winding p + winding q

@[simp] theorem winding_refl (a : graph.Point) :
    winding (Presented.RawPath.refl a : Presented.RawPath graph a a) = 0 :=
  rfl

@[simp] theorem winding_rawEdge (z : Int) :
    winding (rawEdge z) = z :=
  rfl

@[simp] theorem winding_symm
    {a b : graph.Point} (p : Presented.RawPath graph a b) :
    winding p.symm = -(winding p) :=
  rfl

@[simp] theorem winding_trans
    {a b c : graph.Point}
    (p : Presented.RawPath graph a b) (q : Presented.RawPath graph b c) :
    winding (Presented.RawPath.trans p q) = winding p + winding q :=
  rfl

private theorem int_add_congr {m m' n n' : Int}
    (hm : m = m') (hn : n = n') :
    m + n = m' + n' := by
  cases hm
  cases hn
  rfl

/-- Every named circle relator preserves winding number. -/
theorem relator_winding
    {a b : graph.Point} {p q : Presented.RawPath graph a b}
    (h : Relator p q) :
    winding p = winding q := by
  cases h <;> simp

/-- Generated circle homotopy preserves winding number. -/
theorem homotopy_winding
    {a b : graph.Point} {p q : Presented.RawPath graph a b}
    (h : Presented.Homotopy presentation p q) :
    winding p = winding q := by
  induction h with
  | refl _ => rfl
  | relator h => exact relator_winding h
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂
  | inv_congr _ ih => simpa using _root_.congrArg Neg.neg ih
  | comp_congr _ _ ih₁ ih₂ => exact int_add_congr ih₁ ih₂
  | refl_trans _ => simp
  | trans_refl _ => simp
  | trans_assoc _ _ _ => simp [Int.add_assoc]
  | symm_trans p => exact Int.add_left_neg (winding p)
  | trans_symm p => exact Int.add_right_neg (winding p)
  | symm_symm _ => simp
  | symm_refl _ => rfl
  | symm_comp p q =>
      exact Int.neg_add.trans (Int.add_comm (-(winding p)) (-(winding q)))

/-- Every raw circle path is homotopic to the edge carrying its winding number. -/
theorem normalize_raw
    {a b : graph.Point} (p : Presented.RawPath graph a b) :
    Presented.Homotopy presentation p (rawEdge (winding p)) := by
  induction p with
  | refl x =>
      cases x
      exact Presented.Homotopy.symm
        (Presented.Homotopy.relator Relator.zero)
  | edge e =>
      cases e
      exact Presented.Homotopy.refl _
  | symm p ih =>
      exact Presented.Homotopy.trans
        (Presented.Homotopy.inv_congr ih)
        (Presented.Homotopy.relator (Relator.neg (winding p)))
  | trans p q ihp ihq =>
      exact Presented.Homotopy.trans
        (Presented.Homotopy.comp_congr ihp ihq)
        (Presented.Homotopy.relator
          (Relator.add (winding p) (winding q)))

/-- The presented computational fundamental group of the circle. -/
abbrev PiOne : Type u :=
  Presented.PiOne presentation circleCompPathBase

/-- Encode a presented circle loop class by winding number. -/
noncomputable def encode : PiOne → Int :=
  Quot.lift winding (fun _ _ h => homotopy_winding h)

/-- Decode an integer as the class of its labelled loop edge. -/
noncomputable def decode (z : Int) : PiOne :=
  Presented.PiOne.ofRaw (P := presentation) (rawEdge z)

@[simp] theorem encode_decode (z : Int) :
    encode (decode z) = z :=
  rfl

theorem decode_encode (x : PiOne) :
    decode (encode x) = x := by
  induction x using Quot.ind with
  | _ p =>
      exact Quot.sound (Presented.Homotopy.symm (normalize_raw p))

@[simp] theorem encode_id :
    encode (Presented.PiOne.id : PiOne) = 0 :=
  rfl

theorem encode_mul (x y : PiOne) :
    encode (Presented.PiOne.mul x y) = encode x + encode y := by
  induction x using Quot.ind with
  | _ p =>
      induction y using Quot.ind with
      | _ q =>
          rfl

theorem encode_inv (x : PiOne) :
    encode (Presented.PiOne.inv x) = -(encode x) := by
  induction x using Quot.ind with
  | _ p =>
      rfl

/-- The presented computational fundamental group of the circle is `Int`. -/
noncomputable def piOneEquivInt : SimpleEquiv PiOne Int where
  toFun := encode
  invFun := decode
  left_inv := decode_encode
  right_inv := encode_decode

/-- The identity and unit-winding generator define distinct fundamental-group
elements. -/
theorem identity_ne_generator :
    decode 0 ≠ decode 1 := by
  intro h
  have := _root_.congrArg encode h
  simp at this

/-- Concrete equality trace certifying normalization preserves winding. -/
noncomputable def normalizationPath
    {a b : graph.Point} (p : Presented.RawPath graph a b) :
    Path (winding p) (winding (rawEdge (winding p))) :=
  Path.stepChain (homotopy_winding (normalize_raw p))

/-- The normalization trace is coherent with right-unit composition. -/
noncomputable def normalizationCoherence
    {a b : graph.Point} (p : Presented.RawPath graph a b) :
    RwEq
      (Path.trans (normalizationPath p)
        (Path.refl (winding (rawEdge (winding p)))))
      (normalizationPath p) :=
  rweq_cmpA_refl_right (normalizationPath p)

end CirclePresented
end CompPath
end Path
end ComputationalPaths
