/-
# Scoped Seifert--van Kampen for completed loop presentations

Let the left and right loop-expression languages have completed presentations
with normal-form types `G₁` and `G₂`.  Scoped pushout loop expressions are
alternating words in those expression languages.  Encoding maps each component
expression to its normal form and then takes the full amalgamated word class.
Decoding chooses a representative and replaces every normal-form letter by its
canonical component expression.

The component encode/decode laws prove the global round trip.  Applying
`ScopedCompletion` gives a general non-collapsing SVK equivalence for completed
presentations, distinct from the quotient generated by the full raw-`Path`
rewrite relation.
-/

import ComputationalPaths.Path.CompPath.CircleScoped
import ComputationalPaths.Path.CompPath.PushoutPaths
import ComputationalPaths.Path.Rewrite.ScopedCompletion

namespace ComputationalPaths
namespace Path
namespace CompPath
namespace ScopedSeifertVanKampen

universe u v

/-- Scoped pushout loop expressions: alternating component expressions. -/
abbrev ScopedExpr (Expr₁ : Type u) (Expr₂ : Type u) : Type u :=
  FreeProductWord Expr₁ Expr₂

variable {Expr₁ : Type u} {Expr₂ : Type u}
variable {G₁ : Type v} {G₂ : Type v} {H : Type v}

/-- Encode each component expression as a normal-form letter. -/
noncomputable def encodeWord
    (P₁ : ScopedCompletion.Data Expr₁ G₁)
    (P₂ : ScopedCompletion.Data Expr₂ G₂) :
    ScopedExpr Expr₁ Expr₂ → FreeProductWord G₁ G₂ :=
  FreeProductWord.map P₁.encode P₂.encode

/-- Decode each component normal-form letter as its canonical expression. -/
noncomputable def decodeWord
    (P₁ : ScopedCompletion.Data Expr₁ G₁)
    (P₂ : ScopedCompletion.Data Expr₂ G₂) :
    FreeProductWord G₁ G₂ → ScopedExpr Expr₁ Expr₂ :=
  FreeProductWord.map P₁.decode P₂.decode

/-- Component round trips imply the word-level encode/decode round trip. -/
theorem encodeWord_decodeWord
    (P₁ : ScopedCompletion.Data Expr₁ G₁)
    (P₂ : ScopedCompletion.Data Expr₂ G₂)
    (w : FreeProductWord G₁ G₂) :
    encodeWord P₁ P₂ (decodeWord P₁ P₂ w) = w := by
  induction w with
  | nil => rfl
  | consLeft x rest ih =>
      unfold encodeWord decodeWord at ih
      simp only [decodeWord, encodeWord, FreeProductWord.map_consLeft]
      rw [P₁.encode_decode, ih]
  | consRight y rest ih =>
      unfold encodeWord decodeWord at ih
      simp only [decodeWord, encodeWord, FreeProductWord.map_consRight]
      rw [P₂.encode_decode, ih]

section General

variable [Add G₁] [Add G₂] [Zero G₁] [Zero G₂]
variable (P₁ : ScopedCompletion.Data Expr₁ G₁)
variable (P₂ : ScopedCompletion.Data Expr₂ G₂)
variable (i₁ : H → G₁) (i₂ : H → G₂)

/-- Choose a word representative of a full amalgamated target class. -/
noncomputable def targetRepresentative
    (x : FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂) :
    FreeProductWord G₁ G₂ :=
  Classical.choose (Quot.exists_rep x)

@[simp] theorem targetRepresentative_spec
    (x : FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂) :
    FullAmalgamatedFreeProduct.ofWord
        (targetRepresentative (i₁ := i₁) (i₂ := i₂) x) =
      x :=
  Classical.choose_spec (Quot.exists_rep x)

/-- Encode a scoped pushout expression into the full amalgamated target. -/
noncomputable def encodeTarget
    (e : ScopedExpr Expr₁ Expr₂) :
    FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂ :=
  FullAmalgamatedFreeProduct.ofWord (encodeWord P₁ P₂ e)

/-- Decode a target class to a canonical scoped pushout expression. -/
noncomputable def decodeTarget
    (x : FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂) :
    ScopedExpr Expr₁ Expr₂ :=
  decodeWord P₁ P₂
    (targetRepresentative (i₁ := i₁) (i₂ := i₂) x)

@[simp] theorem encodeTarget_decodeTarget
    (x : FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂) :
    encodeTarget P₁ P₂ i₁ i₂ (decodeTarget P₁ P₂ i₁ i₂ x) = x := by
  unfold encodeTarget decodeTarget
  rw [encodeWord_decodeWord]
  exact targetRepresentative_spec (i₁ := i₁) (i₂ := i₂) x

/-- Completed scoped SVK presentation. -/
noncomputable def completion :
    ScopedCompletion.Data
      (ScopedExpr Expr₁ Expr₂)
      (FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂) where
  encode := encodeTarget P₁ P₂ i₁ i₂
  decode := decodeTarget P₁ P₂ i₁ i₂
  encode_decode := encodeTarget_decodeTarget P₁ P₂ i₁ i₂

/-- Scoped pushout loop quotient for two completed component presentations. -/
abbrev PiOne : Type u :=
  ScopedCompletion.Quotient (completion P₁ P₂ i₁ i₂)

/-- General scoped SVK encode map. -/
noncomputable def encode :
    PiOne P₁ P₂ i₁ i₂ →
      FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂ :=
  ScopedCompletion.encodeQuot (completion P₁ P₂ i₁ i₂)

/-- General scoped SVK decode map. -/
noncomputable def decode :
    FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂ →
      PiOne P₁ P₂ i₁ i₂ :=
  ScopedCompletion.decodeQuot (completion P₁ P₂ i₁ i₂)

@[simp] theorem encode_decode
    (x : FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂) :
    encode P₁ P₂ i₁ i₂ (decode P₁ P₂ i₁ i₂ x) = x :=
  ScopedCompletion.encodeQuot_decodeQuot
    (completion P₁ P₂ i₁ i₂) x

theorem decode_encode (x : PiOne P₁ P₂ i₁ i₂) :
    decode P₁ P₂ i₁ i₂ (encode P₁ P₂ i₁ i₂ x) = x :=
  ScopedCompletion.decodeQuot_encodeQuot
    (completion P₁ P₂ i₁ i₂) x

/-- Fully general scoped SVK equivalence for completed component
presentations. -/
noncomputable def scopedSeifertVanKampenEquiv :
    SimpleEquiv
      (PiOne P₁ P₂ i₁ i₂)
      (FullAmalgamatedFreeProduct G₁ G₂ H i₁ i₂) :=
  ScopedCompletion.equivNormal (completion P₁ P₂ i₁ i₂)

end General

/-! ## Figure-eight instance -/

/-- Full free-product target for two scoped circles. -/
abbrev FigureEightTarget : Type :=
  FullAmalgamatedFreeProduct Int Int Unit
    (fun _ => 0) (fun _ => 0)

/-- Named completed presentation for the scoped figure-eight. -/
noncomputable def figureEightCompletion :
    ScopedCompletion.Data
      (ScopedExpr CircleScopedExpr.{u} CircleScopedExpr.{u})
      FigureEightTarget :=
  completion
    circleScopedCompletion
    circleScopedCompletion
    (fun _ : Unit => (0 : Int))
    (fun _ : Unit => (0 : Int))

/-- Scoped figure-eight loop quotient. -/
abbrev FigureEightScopedPiOne : Type u :=
  ScopedCompletion.Quotient figureEightCompletion

/-- The non-collapsing scoped figure-eight satisfies the full free-product
calculation. -/
noncomputable def figureEightScopedSVKEquiv :
    SimpleEquiv FigureEightScopedPiOne.{u} FigureEightTarget :=
  ScopedCompletion.equivNormal figureEightCompletion

/-- Concrete Path witness for the figure-eight scoped normalization. -/
noncomputable def figureEightScopedNormalizationPath
    (e : ScopedExpr CircleScopedExpr.{u} CircleScopedExpr.{u}) :
    Path
      (figureEightCompletion.encode e)
      (figureEightCompletion.encode
        (figureEightCompletion.decode (figureEightCompletion.encode e))) :=
  ScopedCompletion.normalizationPath figureEightCompletion e

/-- The figure-eight normalization witness is right-unit coherent. -/
noncomputable def figureEightScopedNormalizationCoherence
    (e : ScopedExpr CircleScopedExpr.{u} CircleScopedExpr.{u}) :
    _root_.ComputationalPaths.Path.RwEq
      (Path.trans (figureEightScopedNormalizationPath e)
        (Path.refl
          (figureEightCompletion.encode
            (figureEightCompletion.decode
              (figureEightCompletion.encode e)))))
      (figureEightScopedNormalizationPath e) :=
  ScopedCompletion.normalizationCoherence figureEightCompletion e

end ScopedSeifertVanKampen
end CompPath
end Path
end ComputationalPaths
