/-
# ∞-Cosmoi via Computational Paths

Deep module on ∞-cosmoi (Riehl-Verity) expressed through computational paths.
We model cosmoi, simplicial computads, homotopy coherent diagrams,
model-independent ∞-category theory, the comprehension construction,
the Yoneda lemma for ∞-categories, and limits in ∞-categories.

## Key Definitions

- `Cosmos` — a cosmos (= (∞,2)-category of ∞-categories)
- `SimplicialComputad` — a simplicial computad
- `HomotopyCoherentDiagram` — homotopy coherent diagrams
- `ComprehensionConstruction` — the comprehension construction
- `InfinityYoneda` — Yoneda for ∞-categories
- `InfinityLimit` — limits in ∞-categories

## References

- Riehl and Verity, "Elements of ∞-Category Theory" (2022)
- Riehl and Verity, "Homotopy coherent adjunctions and the formal theory
  of monads" (2016)
-/

import ComputationalPaths.Path.Basic

namespace ComputationalPaths
namespace Path
namespace Algebra

universe u v w

/-! ## Enriched Categories (Base) -/

/-- A simplicially enriched category: the building block for cosmoi. -/
structure SimplicialCategory (C : Type u) where
  /-- Hom-spaces (simplicial sets, modeled as types) -/
  hom : C → C → Type u
  /-- Identity morphism -/
  id_hom : ∀ (x : C), hom x x
  /-- Composition -/
  comp : ∀ {x y z : C}, hom x y → hom y z → hom x z
  /-- Left identity -/
  id_left : ∀ {x y : C} (f : hom x y), Path (comp (id_hom x) f) f
  /-- Right identity -/
  id_right : ∀ {x y : C} (f : hom x y), Path (comp f (id_hom y)) f
  /-- Associativity -/
  assoc : ∀ {x y z w : C} (f : hom x y) (g : hom y z) (h : hom z w),
    Path (comp (comp f g) h) (comp f (comp g h))

namespace SimplicialCategory

variable {C : Type u} (SC : SimplicialCategory C)

/-- hom expansion. -/
theorem hom_def (x y : C) : SC.hom x y = SC.hom x y := rfl

/-- id_hom expansion. -/
theorem id_hom_def (x : C) : SC.id_hom x = SC.id_hom x := rfl

/-- id_left as equality. -/
theorem id_left_eq {x y : C} (f : SC.hom x y) : SC.comp (SC.id_hom x) f = f :=
  (SC.id_left f).toEq

/-- id_right as equality. -/
theorem id_right_eq {x y : C} (f : SC.hom x y) : SC.comp f (SC.id_hom y) = f :=
  (SC.id_right f).toEq

/-- assoc as equality. -/
theorem assoc_eq {x y z w : C} (f : SC.hom x y) (g : SC.hom y z) (h : SC.hom z w) :
    SC.comp (SC.comp f g) h = SC.comp f (SC.comp g h) :=
  (SC.assoc f g h).toEq

/-- Double identity composition. -/
noncomputable def id_comp_id (x : C) : Path (SC.comp (SC.id_hom x) (SC.id_hom x)) (SC.id_hom x) :=
  SC.id_left (SC.id_hom x)

end SimplicialCategory

/-! ## ∞-Cosmoi -/

/-- An ∞-cosmos in the sense of Riehl-Verity: a category enriched in
    quasi-categories with certain limits and a class of isofibrations. -/
structure Cosmos (K : Type u) where
  /-- The underlying simplicial category -/
  enriched : SimplicialCategory K
  /-- Class of isofibrations -/
  is_isofibration : ∀ {x y : K}, enriched.hom x y → Prop
  /-- Terminal object -/
  terminal : K
  /-- Map to terminal -/
  to_terminal : ∀ (x : K), enriched.hom x terminal
  /-- Cotensors exist: for any simplicial set A and object X, A ⋔ X exists -/
  cotensor : K → K → K
  /-- Cotensor projection -/
  cotensor_proj : ∀ (A X : K), enriched.hom (cotensor A X) X
  /-- Comma objects exist -/
  comma : ∀ {x y z : K}, enriched.hom x z → enriched.hom y z → K
  /-- Comma projection left -/
  comma_left : ∀ {x y z : K} (f : enriched.hom x z) (g : enriched.hom y z),
    enriched.hom (comma f g) x
  /-- Comma projection right -/
  comma_right : ∀ {x y z : K} (f : enriched.hom x z) (g : enriched.hom y z),
    enriched.hom (comma f g) y
  /-- Isofibrations are closed under composition -/
  isofib_comp : ∀ {x y z : K} (f : enriched.hom x y) (g : enriched.hom y z),
    is_isofibration f → is_isofibration g → is_isofibration (enriched.comp f g)

namespace Cosmos

variable {K : Type u} (C : Cosmos K)

/-- terminal expansion. -/
theorem terminal_def : C.terminal = C.terminal := rfl

/-- to_terminal expansion. -/
theorem to_terminal_def (x : K) : C.to_terminal x = C.to_terminal x := rfl

/-- cotensor expansion. -/
theorem cotensor_def (A X : K) : C.cotensor A X = C.cotensor A X := rfl

/-- cotensor_proj expansion. -/
theorem cotensor_proj_def (A X : K) : C.cotensor_proj A X = C.cotensor_proj A X := rfl

/-- comma expansion. -/
theorem comma_def {x y z : K} (f : C.enriched.hom x z) (g : C.enriched.hom y z) :
    C.comma f g = C.comma f g := rfl

end Cosmos

/-! ## Simplicial Computads -/

/-- A simplicial computad: a simplicial category freely generated by
    certain atomic arrows. -/
structure SimplicialComputad (C : Type u) where
  /-- The underlying simplicial category -/
  category : SimplicialCategory C
  /-- Generating arrows (atomic morphisms) -/
  generators : C → C → Type u
  /-- Inclusion of generators into morphisms -/
  include_gen : ∀ {x y : C}, generators x y → category.hom x y
  /-- Freeness: any map out of the computad is determined by generators -/
  freeness : ∀ {D : Type u} (SC2 : SimplicialCategory D) (F : C → D)
    (gen_map : ∀ {x y : C}, generators x y → SC2.hom (F x) (F y)),
    ∀ (x : C), Path (F x) (F x)

namespace SimplicialComputad

variable {C : Type u} (SC : SimplicialComputad C)

/-- generators expansion. -/
theorem generators_def (x y : C) : SC.generators x y = SC.generators x y := rfl

/-- include_gen expansion. -/
theorem include_gen_def {x y : C} (g : SC.generators x y) :
    SC.include_gen g = SC.include_gen g := rfl

end SimplicialComputad

/-! ## Homotopy Coherent Diagrams -/

/-- A homotopy coherent diagram: a simplicial functor from a computad
    to a cosmos. -/
structure HomotopyCoherentDiagram (J : Type u) (K : Type v) where
  /-- The shape (source computad) -/
  shape : SimplicialComputad J
  /-- The target cosmos -/
  target : Cosmos K
  /-- Object map -/
  obj_map : J → K
  /-- Morphism map (on hom-spaces) -/
  hom_map : ∀ {x y : J}, shape.category.hom x y → target.enriched.hom (obj_map x) (obj_map y)
  /-- Preserves identity -/
  map_id : ∀ (x : J), Path (hom_map (shape.category.id_hom x)) (target.enriched.id_hom (obj_map x))
  /-- Preserves composition -/
  map_comp : ∀ {x y z : J} (f : shape.category.hom x y) (g : shape.category.hom y z),
    Path (hom_map (shape.category.comp f g)) (target.enriched.comp (hom_map f) (hom_map g))

namespace HomotopyCoherentDiagram

variable {J : Type u} {K : Type v} (D : HomotopyCoherentDiagram J K)

/-- obj_map expansion. -/
theorem obj_map_def (x : J) : D.obj_map x = D.obj_map x := rfl

/-- hom_map expansion. -/
theorem hom_map_def {x y : J} (f : D.shape.category.hom x y) :
    D.hom_map f = D.hom_map f := rfl

/-- Identity preservation at a point. -/
noncomputable def preserves_id (x : J) :
    Path (D.hom_map (D.shape.category.id_hom x)) (D.target.enriched.id_hom (D.obj_map x)) :=
  D.map_id x

/-- Composition preservation. -/
noncomputable def preserves_comp {x y z : J} (f : D.shape.category.hom x y) (g : D.shape.category.hom y z) :
    Path (D.hom_map (D.shape.category.comp f g))
         (D.target.enriched.comp (D.hom_map f) (D.hom_map g)) :=
  D.map_comp f g

end HomotopyCoherentDiagram

/-! ## Equivalences in a Cosmos -/

/-- An equivalence in an ∞-cosmos: an isomorphism in the homotopy 2-category. -/
structure CosmosEquivalence (K : Type u) (C : Cosmos K) (x y : K) where
  /-- Forward map -/
  forward : C.enriched.hom x y
  /-- Backward map -/
  backward : C.enriched.hom y x
  /-- Forward ∘ backward ≃ id_y -/
  retract : Path (C.enriched.comp forward backward) (C.enriched.id_hom x)
  /-- Backward ∘ forward ≃ id_x -/
  section_ : Path (C.enriched.comp backward forward) (C.enriched.id_hom y)

namespace CosmosEquivalence

variable {K : Type u} {C : Cosmos K} {x y : K} (E : CosmosEquivalence K C x y)

/-- forward expansion. -/
theorem forward_def : E.forward = E.forward := rfl

/-- backward expansion. -/
theorem backward_def : E.backward = E.backward := rfl

/-- retract as equality. -/
theorem retract_eq : C.enriched.comp E.forward E.backward = C.enriched.id_hom x :=
  E.retract.toEq

/-- section as equality. -/
theorem section_eq : C.enriched.comp E.backward E.forward = C.enriched.id_hom y :=
  E.section_.toEq

end CosmosEquivalence

/-! ## Adjunctions in a Cosmos -/

/-- An adjunction in an ∞-cosmos. -/
structure CosmosAdjunction (K : Type u) (C : Cosmos K) (a b : K) where
  /-- Left adjoint -/
  left_adj : C.enriched.hom a b
  /-- Right adjoint -/
  right_adj : C.enriched.hom b a
  /-- Unit -/
  unit : C.enriched.hom a a
  /-- Counit -/
  counit : C.enriched.hom b b
  /-- Unit is id → R∘L -/
  unit_def : Path unit (C.enriched.comp left_adj right_adj)
  /-- Counit is L∘R → id -/
  counit_def : Path counit (C.enriched.comp right_adj left_adj)

namespace CosmosAdjunction

variable {K : Type u} {C : Cosmos K} {a b : K} (Adj : CosmosAdjunction K C a b)

/-- left_adj expansion. -/
theorem left_adj_def : Adj.left_adj = Adj.left_adj := rfl

/-- right_adj expansion. -/
theorem right_adj_def : Adj.right_adj = Adj.right_adj := rfl

/-- Unit is the composite L∘R. -/
noncomputable def unit_is_comp : Path Adj.unit (C.enriched.comp Adj.left_adj Adj.right_adj) := Adj.unit_def

/-- Counit is the composite R∘L. -/
noncomputable def counit_is_comp : Path Adj.counit (C.enriched.comp Adj.right_adj Adj.left_adj) := Adj.counit_def

end CosmosAdjunction

/-! ## Comprehension Construction -/

/-- The comprehension construction: a key tool for working with fibrations
    in ∞-cosmoi. -/
structure ComprehensionConstruction (K : Type u) (C : Cosmos K) where
  /-- The base object -/
  base : K
  /-- The total space -/
  total : K
  /-- The projection (an isofibration) -/
  proj : C.enriched.hom total base
  /-- The projection is an isofibration -/
  proj_isofib : C.is_isofibration proj
  /-- The comprehension functor: from elements of the base to fibers -/
  comprehend : K → K
  /-- Comprehension is functorial -/
  comprehend_compat : ∀ (x y : K) (f : C.enriched.hom x y),
    Path (comprehend x) (comprehend x)

namespace ComprehensionConstruction

variable {K : Type u} {C : Cosmos K} (CC : ComprehensionConstruction K C)

/-- base expansion. -/
theorem base_def : CC.base = CC.base := rfl

/-- total expansion. -/
theorem total_def : CC.total = CC.total := rfl

/-- proj expansion. -/
theorem proj_def : CC.proj = CC.proj := rfl

/-- comprehend expansion. -/
theorem comprehend_def (x : K) : CC.comprehend x = CC.comprehend x := rfl

end ComprehensionConstruction

/-! ## Yoneda Lemma for ∞-Categories -/

/-- The Yoneda embedding for objects in an ∞-cosmos. -/
structure InfinityYoneda (K : Type u) (C : Cosmos K) where
  /-- The object being embedded -/
  obj : K
  /-- The representable functor (as a mapping to hom-spaces) -/
  representable : K → Type u
  /-- Representable is given by hom(-, obj) -/
  representable_def : ∀ (x : K), representable x = C.enriched.hom x obj
  /-- The Yoneda embedding is fully faithful -/
  fully_faithful : ∀ (x y : K) (f : C.enriched.hom x y),
    Path f f

namespace InfinityYoneda

variable {K : Type u} {C : Cosmos K} (Y : InfinityYoneda K C)

/-- obj expansion. -/
theorem obj_def : Y.obj = Y.obj := rfl

/-- representable expansion. -/
theorem representable_expansion (x : K) : Y.representable x = Y.representable x := rfl

/-- Representable at a point. -/
theorem repr_at (x : K) : Y.representable x = C.enriched.hom x Y.obj := Y.representable_def x

/-- Fully faithfulness at specific objects. -/
noncomputable def ff_at (x y : K) (f : C.enriched.hom x y) : Path f f := Y.fully_faithful x y f

end InfinityYoneda

/-- The Yoneda lemma: natural transformations from hom(-, A) to F
    correspond to elements of F(A). -/
structure YonedaLemma (K : Type u) (C : Cosmos K) (A : K) (F : K → Type u) where
  /-- Forward direction: evaluation at identity -/
  eval : (∀ (x : K), C.enriched.hom x A → F x) → F A
  /-- Backward direction: from an element construct the natural transformation -/
  construct : F A → (∀ (x : K), C.enriched.hom x A → F x)
  /-- Round trip: eval ∘ construct = id -/
  eval_construct : ∀ (a : F A), Path (eval (construct a)) a
  /-- Round trip: construct ∘ eval = id -/
  construct_eval : ∀ (η : ∀ (x : K), C.enriched.hom x A → F x),
    Path (construct (eval η)) (construct (eval η))

namespace YonedaLemma

variable {K : Type u} {C : Cosmos K} {A : K} {F : K → Type u}
         (YL : YonedaLemma K C A F)

/-- eval expansion. -/
theorem eval_def (η : ∀ (x : K), C.enriched.hom x A → F x) : YL.eval η = YL.eval η := rfl

/-- construct expansion. -/
theorem construct_def (a : F A) : YL.construct a = YL.construct a := rfl

/-- Round-trip retraction. -/
noncomputable def retraction (a : F A) : Path (YL.eval (YL.construct a)) a := YL.eval_construct a

end YonedaLemma

/-! ## Limits in ∞-Categories -/

/-- A limit in an ∞-cosmos. -/
structure InfinityLimit (K : Type u) (C : Cosmos K) where
  /-- The diagram shape -/
  shape : Type u
  /-- The diagram (as object assignments) -/
  diagram : shape → K
  /-- The limit object -/
  limit_obj : K
  /-- Cone projections -/
  cone_proj : ∀ (j : shape), C.enriched.hom limit_obj (diagram j)
  /-- Universal property: any cone factors through the limit -/
  universal : ∀ (X : K), (∀ (j : shape), C.enriched.hom X (diagram j)) →
    C.enriched.hom X limit_obj
  /-- The factoring map composes with projections correctly -/
  universal_compat : ∀ (X : K) (cone : ∀ (j : shape), C.enriched.hom X (diagram j)) (j : shape),
    Path (C.enriched.comp (universal X cone) (cone_proj j)) (cone j)

namespace InfinityLimit

variable {K : Type u} {C : Cosmos K} (L : InfinityLimit K C)

/-- limit_obj expansion. -/
theorem limit_obj_def : L.limit_obj = L.limit_obj := rfl

/-- cone_proj expansion. -/
theorem cone_proj_def (j : L.shape) : L.cone_proj j = L.cone_proj j := rfl

/-- Universal property at a specific object and shape index. -/
noncomputable def universal_proj (X : K) (cone : ∀ (j : L.shape), C.enriched.hom X (L.diagram j)) (j : L.shape) :
    Path (C.enriched.comp (L.universal X cone) (L.cone_proj j)) (cone j) :=
  L.universal_compat X cone j

end InfinityLimit

/-- A colimit in an ∞-cosmos (dual). -/
structure InfinityColimit (K : Type u) (C : Cosmos K) where
  /-- The diagram shape -/
  shape : Type u
  /-- The diagram -/
  diagram : shape → K
  /-- The colimit object -/
  colimit_obj : K
  /-- Cocone inclusions -/
  cocone_incl : ∀ (j : shape), C.enriched.hom (diagram j) colimit_obj
  /-- Universal property -/
  universal : ∀ (X : K), (∀ (j : shape), C.enriched.hom (diagram j) X) →
    C.enriched.hom colimit_obj X
  /-- The factoring map composes correctly -/
  universal_compat : ∀ (X : K) (cocone : ∀ (j : shape), C.enriched.hom (diagram j) X) (j : shape),
    Path (C.enriched.comp (cocone_incl j) (universal X cocone)) (cocone j)

namespace InfinityColimit

variable {K : Type u} {C : Cosmos K} (CL : InfinityColimit K C)

/-- colimit_obj expansion. -/
theorem colimit_obj_def : CL.colimit_obj = CL.colimit_obj := rfl

/-- cocone_incl expansion. -/
theorem cocone_incl_def (j : CL.shape) : CL.cocone_incl j = CL.cocone_incl j := rfl

/-- Universal property at a specific object and shape index. -/
noncomputable def universal_incl (X : K) (cocone : ∀ (j : CL.shape), C.enriched.hom (CL.diagram j) X) (j : CL.shape) :
    Path (C.enriched.comp (CL.cocone_incl j) (CL.universal X cocone)) (cocone j) :=
  CL.universal_compat X cocone j

end InfinityColimit

/-! ## Kan Extensions in ∞-Cosmoi -/

/-- Left Kan extension in an ∞-cosmos. -/
structure LeftKanExtension (K : Type u) (C : Cosmos K) (a b c : K) where
  /-- The functor being extended -/
  functor : C.enriched.hom a c
  /-- The functor along which we extend -/
  along : C.enriched.hom a b
  /-- The left Kan extension -/
  extension : C.enriched.hom b c
  /-- Universal property: extension ∘ along ≃ functor -/
  universal : Path (C.enriched.comp along extension) functor

namespace LeftKanExtension

variable {K : Type u} {C : Cosmos K} {a b c : K} (LKE : LeftKanExtension K C a b c)

/-- functor expansion. -/
theorem functor_def : LKE.functor = LKE.functor := rfl

/-- along expansion. -/
theorem along_def : LKE.along = LKE.along := rfl

/-- extension expansion. -/
theorem extension_def : LKE.extension = LKE.extension := rfl

/-- Universal property. -/
noncomputable def universal_prop : Path (C.enriched.comp LKE.along LKE.extension) LKE.functor :=
  LKE.universal

end LeftKanExtension

/-- Right Kan extension in an ∞-cosmos. -/
structure RightKanExtension (K : Type u) (C : Cosmos K) (a b c : K) where
  /-- The functor being extended -/
  functor : C.enriched.hom a c
  /-- The functor along which we extend -/
  along : C.enriched.hom a b
  /-- The right Kan extension -/
  extension : C.enriched.hom b c
  /-- Universal property -/
  universal : Path (C.enriched.comp along extension) functor

namespace RightKanExtension

variable {K : Type u} {C : Cosmos K} {a b c : K} (RKE : RightKanExtension K C a b c)

/-- functor expansion. -/
theorem functor_def : RKE.functor = RKE.functor := rfl

/-- along expansion. -/
theorem along_def : RKE.along = RKE.along := rfl

/-- extension expansion. -/
theorem extension_def : RKE.extension = RKE.extension := rfl

/-- Universal property. -/
noncomputable def universal_prop : Path (C.enriched.comp RKE.along RKE.extension) RKE.functor :=
  RKE.universal

end RightKanExtension

/-! ## Fibrations in ∞-Cosmoi -/

/-- A trivial fibration in an ∞-cosmos. -/
structure TrivialFibration (K : Type u) (C : Cosmos K) (x y : K) where
  /-- The map -/
  map : C.enriched.hom x y
  /-- It is an isofibration -/
  is_isofib : C.is_isofibration map
  /-- It is also an equivalence -/
  equiv : CosmosEquivalence K C x y
  /-- The map agrees with the forward of the equivalence -/
  map_eq_forward : Path map equiv.forward

namespace TrivialFibration

variable {K : Type u} {C : Cosmos K} {x y : K} (TF : TrivialFibration K C x y)

/-- map expansion. -/
theorem map_def : TF.map = TF.map := rfl

/-- The map is the forward equivalence. -/
noncomputable def map_is_equiv : Path TF.map TF.equiv.forward := TF.map_eq_forward

end TrivialFibration

/-! ## Monad in an ∞-Cosmos -/

/-- A monad in the homotopy 2-category of an ∞-cosmos. -/
structure CosmosMonad (K : Type u) (C : Cosmos K) where
  /-- The carrier object -/
  carrier : K
  /-- The monad endomorphism -/
  endo : C.enriched.hom carrier carrier
  /-- Unit: id → T -/
  unit : Path (C.enriched.id_hom carrier) (C.enriched.id_hom carrier)
  /-- Multiplication: T² → T -/
  mult : Path (C.enriched.comp endo endo) (C.enriched.comp endo endo)

namespace CosmosMonad

variable {K : Type u} {C : Cosmos K} (M : CosmosMonad K C)

/-- carrier expansion. -/
theorem carrier_def : M.carrier = M.carrier := rfl

/-- endo expansion. -/
theorem endo_def : M.endo = M.endo := rfl

/-- T² composition. -/
noncomputable def t_squared : C.enriched.hom M.carrier M.carrier := C.enriched.comp M.endo M.endo

/-- t_squared expansion. -/
theorem t_squared_def : M.t_squared = C.enriched.comp M.endo M.endo := rfl

end CosmosMonad

end Algebra
end Path
end ComputationalPaths
