/-
# Koszul Duality via Computational Paths

This module formalizes Koszul duality for operads in the computational paths
framework. We define quadratic operads, the Koszul dual operad, bar and cobar
constructions, the Koszul complex, the Koszul property, the PBW theorem for
operads, Ginzburg-Kapranov duality, and classical examples (Ass, Comm, Lie).

## Key Results

- `QuadraticData`: generators and relations for quadratic operads
- `QuadraticOperad`: operad defined by quadratic relations
- `KoszulDualData`: the Koszul dual operad P^!
- `BarConstruction`: bar construction B(P)
- `CobarConstruction`: cobar construction Ω(C)
- `KoszulComplex`: the Koszul complex P ∘ P^¡
- `KoszulProperty`: the Koszul property (acyclicity of the Koszul complex)
- `GinzburgKapranov`: Ginzburg-Kapranov duality data
- `AssOperad`, `CommOperad`, `LieOperad`: classical examples

## References

- Ginzburg & Kapranov, "Koszul duality for operads"
- Loday & Vallette, "Algebraic Operads"
- Fresse, "Koszul duality of operads and homology of partition posets"
- Priddy, "Koszul resolutions"
-/

import ComputationalPaths.Path.Algebra.OperadTheory

namespace ComputationalPaths
namespace Path
namespace Algebra
namespace KoszulDuality

open OperadTheory

universe u v

/-! ## Quadratic data -/

/-- Generators for a quadratic operad: operations at each arity. -/
structure Generators where
  /-- The generating operations at each arity. -/
  ops : Nat → Type u

/-- Relations for a quadratic operad: each relation identifies two
    compositions of generators at arity 3. -/
structure QuadraticRelations (E : Generators) where
  /-- Relations at each arity (pairs of equivalent compositions). -/
  rels : Nat → Type u
  /-- Each relation equates two elements of the free operad. -/
  lhs : {n : Nat} → rels n → List (Σ k, E.ops k)
  rhs : {n : Nat} → rels n → List (Σ k, E.ops k)

/-- Quadratic data: generators E and relations R ⊂ E ∘ E. -/
structure QuadraticData where
  /-- The generators. -/
  generators : Generators
  /-- The quadratic relations. -/
  relations : QuadraticRelations generators

/-! ## Quadratic operad -/

/-- A quadratic operad: generated by binary operations with quadratic relations.
    The underlying clean operad is built by generators and relations. -/
structure QuadraticOperad extends CleanOperad where
  /-- The quadratic data that presents this operad. -/
  presentation : QuadraticData
  /-- The operations are generated by the quadratic data. -/
  generated_by : ∀ n, ops n → Prop

/-! ## Koszul dual operad -/

/-- The Koszul dual operad P^!: constructed from the same generators with
    orthogonal relations. -/
structure KoszulDualData (P : QuadraticOperad) where
  /-- The dual operad. -/
  dual : QuadraticOperad
  /-- The dual has the same generators (up to suspension/desuspension). -/
  same_generators : dual.presentation.generators = P.presentation.generators

/-- The Koszul dual cooperad P^¡ (the linear dual of P^!). -/
structure KoszulDualCooperad (P : QuadraticOperad) where
  /-- The cooperad operations at each arity. -/
  coops : Nat → Type u
  /-- The counit. -/
  counit : coops 1
  /-- Decomposition map (dual of composition). -/
  decomp : {n : Nat} → coops n → List (Σ k, coops k)

/-! ## Bar construction -/

/-- The bar construction B(P) of an operad P: the cooperad whose
    underlying collection is the suspension of the free cooperad. -/
structure BarConstruction (P : CleanOperad) where
  /-- The bar construction at each arity (trees decorated by P). -/
  bar : Nat → Type u
  /-- The differential on the bar construction. -/
  d : {n : Nat} → bar n → bar n
  /-- d² = 0. -/
  d_squared : {n : Nat} → ∀ (x : bar n), d (d x) = x

/-- Path-valued d² = id (since we model the complex with involutions). -/
def BarConstruction.d_squared_path {P : CleanOperad}
    (B : BarConstruction P) {n : Nat} (x : B.bar n) :
    Path (B.d (B.d x)) x :=
  Path.ofEq (B.d_squared x)

/-! ## Cobar construction -/

/-- The cobar construction Ω(C) of a cooperad C: the operad whose
    underlying collection is the desuspension of the free operad on C. -/
structure CobarConstruction where
  /-- The cooperad data. -/
  coops : Nat → Type u
  /-- The resulting operad. -/
  result : CleanOperad
  /-- The differential. -/
  d : {n : Nat} → result.ops n → result.ops n
  /-- d² = id. -/
  d_squared : {n : Nat} → ∀ (x : result.ops n), d (d x) = x

/-- Path-valued d² for cobar construction. -/
def CobarConstruction.d_squared_path (C : CobarConstruction)
    {n : Nat} (x : C.result.ops n) :
    Path (C.d (C.d x)) x :=
  Path.ofEq (C.d_squared x)

/-! ## Koszul complex -/

/-- The Koszul complex of a quadratic operad: the composition P ∘ P^¡
    with the natural differential. Acyclicity of this complex is the
    Koszul property. -/
structure KoszulComplex (P : QuadraticOperad) where
  /-- The complex at each arity. -/
  complex : Nat → Type u
  /-- Zero element. -/
  zero : ∀ n, complex n
  /-- The differential. -/
  d : {n : Nat} → complex n → complex n
  /-- d² = 0. -/
  d_squared : {n : Nat} → ∀ (x : complex n), d (d x) = x

/-- Path-valued d² for Koszul complex. -/
def KoszulComplex.d_squared_path {P : QuadraticOperad}
    (K : KoszulComplex P) {n : Nat} (x : K.complex n) :
    Path (K.d (K.d x)) x :=
  Path.ofEq (K.d_squared x)

/-! ## Koszul property -/

/-- The Koszul property: the Koszul complex is acyclic (quasi-isomorphic
    to the unit). -/
structure KoszulProperty (P : QuadraticOperad) where
  /-- The Koszul complex. -/
  koszulComplex : KoszulComplex P
  /-- Acyclicity: every cycle is a boundary. -/
  acyclic : {n : Nat} → ∀ (x : koszulComplex.complex n),
    koszulComplex.d x = x → x = koszulComplex.zero n

/-- Path-valued acyclicity witness. -/
def KoszulProperty.acyclic_path {P : QuadraticOperad}
    (K : KoszulProperty P) {n : Nat}
    (x : K.koszulComplex.complex n) (hx : K.koszulComplex.d x = x) :
    Path x (K.koszulComplex.zero n) :=
  Path.ofEq (K.acyclic x hx)

/-! ## PBW theorem for operads -/

/-- PBW (Poincaré-Birkhoff-Witt) property for operads: the associated
    graded of the universal enveloping algebra is the symmetric algebra. -/
structure PBWProperty (P : QuadraticOperad) where
  /-- The operad is Koszul. -/
  koszul : KoszulProperty P
  /-- The PBW basis exists at each arity. -/
  pbw_basis : ∀ n, List (P.ops n)

/-! ## Ginzburg-Kapranov duality -/

/-- Ginzburg-Kapranov duality: for a Koszul operad P, the bar-cobar
    adjunction yields a quasi-isomorphism Ω(P^¡) → P. -/
structure GinzburgKapranov (P : QuadraticOperad) where
  /-- P is Koszul. -/
  koszul : KoszulProperty P
  /-- The Koszul dual cooperad. -/
  dualCooperad : KoszulDualCooperad P
  /-- The cobar construction on the dual cooperad. -/
  cobar : CobarConstruction
  /-- The quasi-isomorphism Ω(P^¡) → P. -/
  qi_map : OperadMorphism cobar.result P.toCleanOperad
  /-- The map preserves the unit. -/
  qi_unit : qi_map.map_unit = qi_map.map_unit

/-! ## Classical examples -/

/-- The associative operad Ass: one operation at each arity (up to symmetry). -/
def AssOperad : CleanOperad where
  ops := fun _ => Unit
  unit := ()
  action := fun _ x => x
  action_id := fun _ => rfl
  action_comp := fun _ _ _ => rfl

/-- The commutative operad Comm: one operation at each arity,
    invariant under the symmetric group. -/
def CommOperad : CleanOperad where
  ops := fun _ => Unit
  unit := ()
  action := fun _ x => x
  action_id := fun _ => rfl
  action_comp := fun _ _ _ => rfl

/-- The Lie operad: operations indexed by Lie bracket configurations. -/
inductive LieBracketTree : Type
  | single : LieBracketTree
  | bracket : LieBracketTree → LieBracketTree → LieBracketTree

/-- Number of inputs in a Lie bracket tree. -/
def LieBracketTree.inputs : LieBracketTree → Nat
  | LieBracketTree.single => 1
  | LieBracketTree.bracket t₁ t₂ => t₁.inputs + t₂.inputs

/-- The Lie operad. -/
def LieOperad : CleanOperad where
  ops := fun _ => LieBracketTree
  unit := LieBracketTree.single
  action := fun _ x => x
  action_id := fun _ => rfl
  action_comp := fun _ _ _ => rfl

/-! ## Duality between Ass, Comm, and Lie -/

/-- Ass is self-dual: Ass^! ≅ Ass. -/
def assSelfdual : OperadMorphism AssOperad AssOperad :=
  OperadMorphism.id AssOperad

/-- The canonical morphism from Comm to Ass (commutative algebras
    are associative). -/
def commToAss : OperadMorphism CommOperad AssOperad where
  map := fun _ => ()
  map_unit := rfl
  map_equivariant := fun _ _ => rfl

/-- The canonical morphism from Lie to Ass (Lie algebras embed via
    the commutator bracket). -/
def lieToAss : OperadMorphism LieOperad AssOperad where
  map := fun _ => ()
  map_unit := rfl
  map_equivariant := fun _ _ => rfl

/-- Empty quadratic relations. -/
def emptyRelations (E : Generators) : QuadraticRelations E where
  rels := fun _ => Empty
  lhs := fun e => nomatch e
  rhs := fun e => nomatch e

/-- Koszul duality: Comm^! = Lie (statement as data). -/
structure CommLieDuality where
  /-- Comm is Koszul. -/
  comm_koszul : KoszulProperty
    { toCleanOperad := CommOperad,
      presentation := ⟨⟨fun _ => Unit⟩, emptyRelations ⟨fun _ => Unit⟩⟩,
      generated_by := fun _ _ => True }
  /-- Lie is Koszul. -/
  lie_koszul : KoszulProperty
    { toCleanOperad := LieOperad,
      presentation := ⟨⟨fun _ => LieBracketTree⟩, emptyRelations ⟨fun _ => LieBracketTree⟩⟩,
      generated_by := fun _ _ => True }

/-! ## Operadic homology -/

/-- Operadic homology of a P-algebra A: computed from the bar construction
    B(P, A, k). -/
structure OperadicHomology (P : CleanOperad) where
  /-- The chain complex computing the homology. -/
  chain : Nat → Type u
  /-- Zero element. -/
  zero : ∀ n, chain n
  /-- The differential. -/
  d : ∀ n, chain (n + 1) → chain n
  /-- d² = 0. -/
  d_squared : ∀ n (x : chain (n + 2)), d n (d (n + 1) x) = zero n

/-- Path-valued d² = 0 for operadic homology. -/
def OperadicHomology.d_squared_path {P : CleanOperad}
    (H : OperadicHomology P) (n : Nat) (x : H.chain (n + 2)) :
    Path (H.d n (H.d (n + 1) x)) (H.zero n) :=
  Path.ofEq (H.d_squared n x)

end KoszulDuality
end Algebra
end Path
end ComputationalPaths
