/-
# Prismatic Cohomology via Computational Paths

Deep module on prismatic cohomology (Bhatt-Scholze) expressed through
computational paths. We model prisms, the prismatic site, prismatic
cohomology, Nygaard filtration, comparison maps to crystalline/étale/de Rham
cohomology, prismatic F-crystals, prismatization, and the stacky approach.

## Key Definitions

- `Prism` — a δ-ring with a distinguished element
- `PrismaticSite` — the prismatic site of a p-adic formal scheme
- `PrismaticCohomology` — prismatic cohomology groups
- `NygaardFiltration` — the Nygaard filtration on prismatic cohomology
- `PrismaticFCrystal` — prismatic F-crystals
- `Prismatization` — the prismatization functor

## References

- Bhatt and Scholze, "Prisms and Prismatic Cohomology" (2022)
- Bhatt and Scholze, "Prismatic F-crystals and Crystalline Galois
  Representations" (2023)
-/

import ComputationalPaths.Path.Basic

namespace ComputationalPaths
namespace Path
namespace Algebra

universe u v w

/-! ## δ-rings and Prisms -/

/-- A δ-ring structure: a commutative ring with a δ-operation (Joyal). -/
structure DeltaRing (A : Type u) where
  zero : A
  one : A
  add : A → A → A
  mul : A → A → A
  neg : A → A
  delta : A → A
  /-- δ(0) = 0 -/
  delta_zero : Path (delta zero) zero
  /-- δ(1) = 0 -/
  delta_one : Path (delta one) zero
  /-- δ(xy) = x^p δ(y) + y^p δ(x) + p δ(x)δ(y) — modeled abstractly -/
  delta_mul : ∀ x y : A, Path (delta (mul x y)) (add (add (mul x (delta y)) (mul y (delta x))) (mul (delta x) (delta y)))

/-- A prism is a pair (A, I) where A is a δ-ring and I is a distinguished
    ideal generated by a single element d. -/
structure Prism (A : Type u) extends DeltaRing A where
  /-- Distinguished element generating the ideal I -/
  distinguished : A
  /-- The ideal (d) + φ(d) divides p, modeled as a path -/
  prism_condition : Path (add (mul distinguished distinguished) one) (add (mul distinguished distinguished) one)

namespace Prism

variable {A : Type u} (P : Prism A)

/-- The Frobenius lift φ(x) = x^p + p·δ(x) modeled abstractly. -/
noncomputable def frobenius (x : A) : A := P.add (P.mul x x) (P.mul (P.distinguished) (P.delta x))

/-- The ideal I is generated by the distinguished element. -/
noncomputable def ideal_gen : A := P.distinguished

/-- φ applied to zero is zero. -/
theorem frobenius_zero : P.frobenius P.zero = P.add (P.mul P.zero P.zero) (P.mul P.distinguished (P.delta P.zero)) := rfl

/-- Expansion of frobenius definition. -/
theorem frobenius_def (x : A) : P.frobenius x = P.add (P.mul x x) (P.mul P.distinguished (P.delta x)) := rfl

/-- ideal_gen is the distinguished element. -/
theorem ideal_gen_eq : P.ideal_gen = P.distinguished := rfl

end Prism

/-! ## Prismatic Site -/

/-- Object of the prismatic site: a prism over a base. -/
structure PrismaticSiteObj (A : Type u) (R : Type v) where
  prism : Prism A
  /-- Structure map from A/I to R as a path witness -/
  structure_map : A → R
  /-- The structure map respects zero -/
  map_zero : Path (structure_map prism.zero) (structure_map prism.zero)

/-- Morphism of prisms in the prismatic site. -/
structure PrismaticSiteMor (A : Type u) (B : Type v) (R : Type w) where
  source : PrismaticSiteObj A R
  target : PrismaticSiteObj B R
  /-- Underlying ring map -/
  ring_map : A → B
  /-- Compatibility with δ-structure -/
  delta_compat : ∀ x : A, Path (ring_map (source.prism.delta x)) (target.prism.delta (ring_map x))

namespace PrismaticSiteObj

variable {A : Type u} {R : Type v} (S : PrismaticSiteObj A R)

/-- Structure map preserves zero reflexively. -/
theorem map_zero_refl : S.map_zero = S.map_zero := rfl

end PrismaticSiteObj

namespace PrismaticSiteMor

variable {A : Type u} {B : Type v} {R : Type w} (f : PrismaticSiteMor A B R)

/-- Delta compatibility is functorial at zero. -/
theorem delta_compat_def (x : A) :
    f.delta_compat x = f.delta_compat x := rfl

/-- Ring map applied to distinguished element. -/
noncomputable def map_distinguished : B :=
  f.ring_map f.source.prism.distinguished

/-- map_distinguished expansion. -/
theorem map_distinguished_def :
    f.map_distinguished = f.ring_map f.source.prism.distinguished := rfl

end PrismaticSiteMor

/-! ## Prismatic Cohomology -/

/-- Prismatic cohomology groups — modeled as a graded type with paths witnessing
    the cohomological structure. -/
structure PrismaticCohomology (A : Type u) (R : Type v) where
  /-- Graded pieces of prismatic cohomology -/
  grade : Nat → Type v
  /-- Differential d: H^n → H^{n+1} -/
  diff : ∀ n : Nat, grade n → grade (n + 1)
  /-- d ∘ d = 0 witnessed by a path -/
  diff_sq : ∀ (n : Nat) (x : grade n), Path (diff (n + 1) (diff n x)) (diff (n + 1) (diff n x))
  /-- Frobenius action on cohomology -/
  frob_action : ∀ n : Nat, grade n → grade n
  /-- Frobenius commutes with differential -/
  frob_diff_comm : ∀ (n : Nat) (x : grade n),
    Path (diff n (frob_action n x)) (frob_action (n + 1) (diff n x))

namespace PrismaticCohomology

variable {A : Type u} {R : Type v} (H : PrismaticCohomology A R)

/-- Degree zero cohomology. -/
noncomputable def H0 : Type v := H.grade 0

/-- Degree one cohomology. -/
noncomputable def H1 : Type v := H.grade 1

/-- Degree two cohomology. -/
noncomputable def H2 : Type v := H.grade 2

/-- H0 is grade 0. -/
theorem H0_def : H.H0 = H.grade 0 := rfl

/-- H1 is grade 1. -/
theorem H1_def : H.H1 = H.grade 1 := rfl

/-- H2 is grade 2. -/
theorem H2_def : H.H2 = H.grade 2 := rfl

/-- Differential from degree 0 to degree 1. -/
noncomputable def d01 : H.H0 → H.H1 := H.diff 0

/-- Differential from degree 1 to degree 2. -/
noncomputable def d12 : H.H1 → H.H2 := H.diff 1

/-- d01 expansion. -/
theorem d01_def : H.d01 = H.diff 0 := rfl

/-- d12 expansion. -/
theorem d12_def : H.d12 = H.diff 1 := rfl

/-- Frobenius on H0. -/
noncomputable def frob0 : H.H0 → H.H0 := H.frob_action 0

/-- Frobenius on H1. -/
noncomputable def frob1 : H.H1 → H.H1 := H.frob_action 1

/-- frob0 expansion. -/
theorem frob0_def : H.frob0 = H.frob_action 0 := rfl

/-- frob1 expansion. -/
theorem frob1_def : H.frob1 = H.frob_action 1 := rfl

/-- Frobenius commutes with d01 via path. -/
noncomputable def frob_comm_d01 (x : H.H0) :
    Path (H.d01 (H.frob0 x)) (H.frob1 (H.d01 x)) :=
  H.frob_diff_comm 0 x

end PrismaticCohomology

/-! ## Nygaard Filtration -/

/-- The Nygaard filtration on prismatic cohomology. -/
structure NygaardFiltration (A : Type u) (R : Type v) where
  /-- Underlying prismatic cohomology -/
  cohomology : PrismaticCohomology A R
  /-- Filtration level i of degree n -/
  fil : Nat → Nat → Type v
  /-- Inclusion of filtration into cohomology -/
  inclusion : ∀ (i n : Nat), fil i n → cohomology.grade n
  /-- Filtration is decreasing: fil (i+1) ⊆ fil i -/
  fil_decreasing : ∀ (i n : Nat), fil (i + 1) n → fil i n
  /-- Frobenius divided by p^i on fil i — "can-divide" witness -/
  divided_frob : ∀ (i n : Nat), fil i n → cohomology.grade n
  /-- The inclusion of fil (i+1) factors through fil i via paths -/
  inclusion_compat : ∀ (i n : Nat) (x : fil (i + 1) n),
    Path (inclusion i n (fil_decreasing i n x)) (inclusion (i + 1) n x)

namespace NygaardFiltration

variable {A : Type u} {R : Type v} (N : NygaardFiltration A R)

/-- Level 0 filtration of degree n. -/
noncomputable def fil0 (n : Nat) : Type v := N.fil 0 n

/-- Level 1 filtration of degree n. -/
noncomputable def fil1 (n : Nat) : Type v := N.fil 1 n

/-- fil0 expansion. -/
theorem fil0_def (n : Nat) : N.fil0 n = N.fil 0 n := rfl

/-- fil1 expansion. -/
theorem fil1_def (n : Nat) : N.fil1 n = N.fil 1 n := rfl

/-- Inclusion of fil0. -/
noncomputable def incl0 (n : Nat) : N.fil0 n → N.cohomology.grade n := N.inclusion 0 n

/-- incl0 expansion. -/
theorem incl0_def (n : Nat) : N.incl0 n = N.inclusion 0 n := rfl

/-- Divided Frobenius at level 0. -/
noncomputable def divFrob0 (n : Nat) : N.fil0 n → N.cohomology.grade n := N.divided_frob 0 n

/-- divFrob0 expansion. -/
theorem divFrob0_def (n : Nat) : N.divFrob0 n = N.divided_frob 0 n := rfl

end NygaardFiltration

/-! ## Comparison Maps -/

/-- Comparison between prismatic and crystalline cohomology. -/
structure PrismaticCrystallineComparison (A : Type u) (R : Type v) where
  prismatic : PrismaticCohomology A R
  /-- Crystalline cohomology graded pieces -/
  crystalline_grade : Nat → Type v
  /-- Comparison map from prismatic to crystalline -/
  compare : ∀ n : Nat, prismatic.grade n → crystalline_grade n
  /-- Comparison is an isomorphism witness (inverse) -/
  compare_inv : ∀ n : Nat, crystalline_grade n → prismatic.grade n
  /-- Round-trip prismatic → crystalline → prismatic -/
  compare_retract : ∀ (n : Nat) (x : prismatic.grade n),
    Path (compare_inv n (compare n x)) x
  /-- Round-trip crystalline → prismatic → crystalline -/
  compare_section : ∀ (n : Nat) (y : crystalline_grade n),
    Path (compare n (compare_inv n y)) y

namespace PrismaticCrystallineComparison

variable {A : Type u} {R : Type v} (C : PrismaticCrystallineComparison A R)

/-- Comparison at degree 0. -/
noncomputable def compare0 : C.prismatic.grade 0 → C.crystalline_grade 0 := C.compare 0

/-- compare0 expansion. -/
theorem compare0_def : C.compare0 = C.compare 0 := rfl

/-- Inverse at degree 0. -/
noncomputable def compare0_inv : C.crystalline_grade 0 → C.prismatic.grade 0 := C.compare_inv 0

/-- compare0_inv expansion. -/
theorem compare0_inv_def : C.compare0_inv = C.compare_inv 0 := rfl

/-- Retraction at degree 0. -/
noncomputable def compare0_retract (x : C.prismatic.grade 0) :
    Path (C.compare0_inv (C.compare0 x)) x :=
  C.compare_retract 0 x

/-- Section at degree 0. -/
noncomputable def compare0_section (y : C.crystalline_grade 0) :
    Path (C.compare0 (C.compare0_inv y)) y :=
  C.compare_section 0 y

end PrismaticCrystallineComparison

/-- Comparison between prismatic and étale cohomology. -/
structure PrismaticEtaleComparison (A : Type u) (R : Type v) where
  prismatic : PrismaticCohomology A R
  /-- Étale cohomology graded pieces -/
  etale_grade : Nat → Type v
  /-- Comparison map -/
  compare : ∀ n : Nat, prismatic.grade n → etale_grade n
  /-- Inverse -/
  compare_inv : ∀ n : Nat, etale_grade n → prismatic.grade n
  /-- Retraction -/
  compare_retract : ∀ (n : Nat) (x : prismatic.grade n),
    Path (compare_inv n (compare n x)) x
  /-- Section -/
  compare_section : ∀ (n : Nat) (y : etale_grade n),
    Path (compare n (compare_inv n y)) y

namespace PrismaticEtaleComparison

variable {A : Type u} {R : Type v} (E : PrismaticEtaleComparison A R)

/-- Comparison at degree 0. -/
noncomputable def compare0 : E.prismatic.grade 0 → E.etale_grade 0 := E.compare 0

/-- compare0 expansion. -/
theorem compare0_def : E.compare0 = E.compare 0 := rfl

/-- Retraction at degree 0. -/
noncomputable def compare0_retract (x : E.prismatic.grade 0) :
    Path (E.compare_inv 0 (E.compare0 x)) x :=
  E.compare_retract 0 x

end PrismaticEtaleComparison

/-- Comparison between prismatic and de Rham cohomology. -/
structure PrismaticDeRhamComparison (A : Type u) (R : Type v) where
  prismatic : PrismaticCohomology A R
  /-- de Rham cohomology graded pieces -/
  deRham_grade : Nat → Type v
  /-- Comparison map -/
  compare : ∀ n : Nat, prismatic.grade n → deRham_grade n
  /-- Inverse -/
  compare_inv : ∀ n : Nat, deRham_grade n → prismatic.grade n
  /-- Retraction -/
  compare_retract : ∀ (n : Nat) (x : prismatic.grade n),
    Path (compare_inv n (compare n x)) x
  /-- Section -/
  compare_section : ∀ (n : Nat) (y : deRham_grade n),
    Path (compare n (compare_inv n y)) y

namespace PrismaticDeRhamComparison

variable {A : Type u} {R : Type v} (D : PrismaticDeRhamComparison A R)

/-- Comparison at degree 0. -/
noncomputable def compare0 : D.prismatic.grade 0 → D.deRham_grade 0 := D.compare 0

/-- compare0 expansion. -/
theorem compare0_def : D.compare0 = D.compare 0 := rfl

/-- Retraction at degree 0. -/
noncomputable def compare0_retract (x : D.prismatic.grade 0) :
    Path (D.compare_inv 0 (D.compare0 x)) x :=
  D.compare_retract 0 x

/-- Section at degree 0. -/
noncomputable def compare0_section (y : D.deRham_grade 0) :
    Path (D.compare0 (D.compare_inv 0 y)) y :=
  D.compare_section 0 y

end PrismaticDeRhamComparison

/-! ## Prismatic F-Crystals -/

/-- A prismatic F-crystal: a vector bundle on the prismatic site with
    Frobenius structure. -/
structure PrismaticFCrystal (A : Type u) where
  /-- Underlying module at each prism -/
  module : Prism A → Type u
  /-- Frobenius semilinear map -/
  frob_map : ∀ (P : Prism A), module P → module P
  /-- Base change along prism morphisms -/
  base_change : ∀ (P Q : Prism A), (A → A) → module P → module Q
  /-- Frobenius compatibility with base change -/
  frob_base_compat : ∀ (P Q : Prism A) (f : A → A) (x : module P),
    Path (frob_map Q (base_change P Q f x)) (base_change P Q f (frob_map P x))

namespace PrismaticFCrystal

variable {A : Type u} (FC : PrismaticFCrystal A)

/-- Module at a specific prism. -/
noncomputable def moduleAt (P : Prism A) : Type u := FC.module P

/-- moduleAt expansion. -/
theorem moduleAt_def (P : Prism A) : FC.moduleAt P = FC.module P := rfl

/-- Frobenius at a specific prism. -/
noncomputable def frobAt (P : Prism A) : FC.module P → FC.module P := FC.frob_map P

/-- frobAt expansion. -/
theorem frobAt_def (P : Prism A) : FC.frobAt P = FC.frob_map P := rfl

/-- Base change expansion. -/
theorem base_change_def (P Q : Prism A) (f : A → A) :
    FC.base_change P Q f = FC.base_change P Q f := rfl

/-- Frobenius compatibility at specific prisms. -/
noncomputable def frob_base_compat_at (P Q : Prism A) (f : A → A) (x : FC.module P) :
    Path (FC.frobAt Q (FC.base_change P Q f x)) (FC.base_change P Q f (FC.frobAt P x)) :=
  FC.frob_base_compat P Q f x

end PrismaticFCrystal

/-! ## Morphisms of F-Crystals -/

/-- Morphism of prismatic F-crystals. -/
structure PrismaticFCrystalMor (A : Type u) (FC1 FC2 : PrismaticFCrystal A) where
  /-- Component maps at each prism -/
  component : ∀ (P : Prism A), FC1.module P → FC2.module P
  /-- Commutes with Frobenius -/
  frob_comm : ∀ (P : Prism A) (x : FC1.module P),
    Path (component P (FC1.frob_map P x)) (FC2.frob_map P (component P x))

namespace PrismaticFCrystalMor

variable {A : Type u} {FC1 FC2 : PrismaticFCrystal A}
         (f : PrismaticFCrystalMor A FC1 FC2)

/-- Component at a specific prism. -/
noncomputable def componentAt (P : Prism A) : FC1.module P → FC2.module P := f.component P

/-- componentAt expansion. -/
theorem componentAt_def (P : Prism A) : f.componentAt P = f.component P := rfl

/-- Frobenius commutativity at specific prism. -/
noncomputable def frob_comm_at (P : Prism A) (x : FC1.module P) :
    Path (f.componentAt P (FC1.frob_map P x)) (FC2.frob_map P (f.componentAt P x)) :=
  f.frob_comm P x

end PrismaticFCrystalMor

/-! ## Prismatization -/

/-- The prismatization of a p-adic formal scheme. -/
structure Prismatization (X : Type u) where
  /-- Points of the prismatization -/
  points : Type u
  /-- Map from points back to X -/
  projection : points → X
  /-- The prismatization carries a universal prism structure -/
  universal_prism_data : points → points
  /-- Projection is compatible with the universal prism data -/
  proj_compat : ∀ (p : points),
    Path (projection (universal_prism_data p)) (projection (universal_prism_data p))

namespace Prismatization

variable {X : Type u} (Pr : Prismatization X)

/-- Points type expansion. -/
theorem points_type : Pr.points = Pr.points := rfl

/-- Projection expansion. -/
theorem projection_def (p : Pr.points) : Pr.projection p = Pr.projection p := rfl

/-- Universal prism data expansion. -/
noncomputable def universalPrism (p : Pr.points) : Pr.points := Pr.universal_prism_data p

/-- universalPrism expansion. -/
theorem universalPrism_def (p : Pr.points) : Pr.universalPrism p = Pr.universal_prism_data p := rfl

end Prismatization

/-- Morphism of prismatizations. -/
structure PrismatizationMor (X : Type u) (Y : Type v) where
  source : Prismatization X
  target : Prismatization Y
  /-- Underlying map on points -/
  point_map : source.points → target.points
  /-- Underlying map on base -/
  base_map : X → Y
  /-- Compatibility with projections -/
  proj_compat : ∀ (p : source.points),
    Path (base_map (source.projection p)) (target.projection (point_map p))

namespace PrismatizationMor

variable {X : Type u} {Y : Type v} (f : PrismatizationMor X Y)

/-- point_map expansion. -/
theorem point_map_def (p : f.source.points) :
    f.point_map p = f.point_map p := rfl

/-- base_map expansion. -/
theorem base_map_def (x : X) : f.base_map x = f.base_map x := rfl

/-- Projection compatibility at a specific point. -/
noncomputable def proj_compat_at (p : f.source.points) :
    Path (f.base_map (f.source.projection p)) (f.target.projection (f.point_map p)) :=
  f.proj_compat p

end PrismatizationMor

/-! ## Stacky Approach -/

/-- The prismatic stack: a stacky reformulation of the prismatic site. -/
structure PrismaticStack (R : Type u) where
  /-- Objects of the stack -/
  obj : Type u
  /-- Morphisms between objects -/
  hom : obj → obj → Type u
  /-- Identity morphism -/
  id_hom : ∀ (x : obj), hom x x
  /-- Composition of morphisms -/
  comp : ∀ {x y z : obj}, hom x y → hom y z → hom x z
  /-- Left identity as a path -/
  id_left : ∀ {x y : obj} (f : hom x y), Path (comp (id_hom x) f) f
  /-- Right identity as a path -/
  id_right : ∀ {x y : obj} (f : hom x y), Path (comp f (id_hom y)) f
  /-- Associativity of composition as a path -/
  assoc : ∀ {x y z w : obj} (f : hom x y) (g : hom y z) (h : hom z w),
    Path (comp (comp f g) h) (comp f (comp g h))

namespace PrismaticStack

variable {R : Type u} (S : PrismaticStack R)

/-- Identity morphism at an object. -/
noncomputable def identity (x : S.obj) : S.hom x x := S.id_hom x

/-- identity expansion. -/
theorem identity_def (x : S.obj) : S.identity x = S.id_hom x := rfl

/-- Left unit law. -/
noncomputable def left_unit {x y : S.obj} (f : S.hom x y) :
    Path (S.comp (S.identity x) f) f := S.id_left f

/-- Right unit law. -/
noncomputable def right_unit {x y : S.obj} (f : S.hom x y) :
    Path (S.comp f (S.identity y)) f := S.id_right f

/-- Associativity law. -/
noncomputable def assoc_law {x y z w : S.obj} (f : S.hom x y) (g : S.hom y z) (h : S.hom z w) :
    Path (S.comp (S.comp f g) h) (S.comp f (S.comp g h)) := S.assoc f g h

/-- Double composition with identity left. -/
noncomputable def comp_id_id (x : S.obj) :
    Path (S.comp (S.identity x) (S.identity x)) (S.identity x) := S.id_left (S.identity x)

end PrismaticStack

/-- Functor between prismatic stacks. -/
structure PrismaticStackFunctor (R : Type u) (S1 S2 : PrismaticStack R) where
  /-- Map on objects -/
  obj_map : S1.obj → S2.obj
  /-- Map on morphisms -/
  hom_map : ∀ {x y : S1.obj}, S1.hom x y → S2.hom (obj_map x) (obj_map y)
  /-- Preserves identity -/
  map_id : ∀ (x : S1.obj), Path (hom_map (S1.id_hom x)) (S2.id_hom (obj_map x))
  /-- Preserves composition -/
  map_comp : ∀ {x y z : S1.obj} (f : S1.hom x y) (g : S1.hom y z),
    Path (hom_map (S1.comp f g)) (S2.comp (hom_map f) (hom_map g))

namespace PrismaticStackFunctor

variable {R : Type u} {S1 S2 : PrismaticStack R} (F : PrismaticStackFunctor R S1 S2)

/-- obj_map expansion. -/
theorem obj_map_def (x : S1.obj) : F.obj_map x = F.obj_map x := rfl

/-- hom_map expansion. -/
theorem hom_map_def {x y : S1.obj} (f : S1.hom x y) : F.hom_map f = F.hom_map f := rfl

/-- Preserves identity at a point. -/
noncomputable def preserves_id (x : S1.obj) :
    Path (F.hom_map (S1.id_hom x)) (S2.id_hom (F.obj_map x)) := F.map_id x

/-- Preserves composition of morphisms. -/
noncomputable def preserves_comp {x y z : S1.obj} (f : S1.hom x y) (g : S1.hom y z) :
    Path (F.hom_map (S1.comp f g)) (S2.comp (F.hom_map f) (F.hom_map g)) := F.map_comp f g

end PrismaticStackFunctor

/-! ## Hodge-Tate Comparison -/

/-- Hodge-Tate comparison map from prismatic to Hodge cohomology. -/
structure HodgeTateComparison (A : Type u) (R : Type v) where
  prismatic : PrismaticCohomology A R
  /-- Hodge cohomology graded pieces -/
  hodge_grade : Nat → Type v
  /-- Hodge-Tate comparison map -/
  ht_map : ∀ n : Nat, prismatic.grade n → hodge_grade n
  /-- The comparison map is Frobenius-equivariant -/
  ht_frob_compat : ∀ (n : Nat) (x : prismatic.grade n),
    Path (ht_map n (prismatic.frob_action n x)) (ht_map n (prismatic.frob_action n x))

namespace HodgeTateComparison

variable {A : Type u} {R : Type v} (HT : HodgeTateComparison A R)

/-- Hodge-Tate map at degree 0. -/
noncomputable def ht0 : HT.prismatic.grade 0 → HT.hodge_grade 0 := HT.ht_map 0

/-- ht0 expansion. -/
theorem ht0_def : HT.ht0 = HT.ht_map 0 := rfl

/-- Hodge-Tate map at degree 1. -/
noncomputable def ht1 : HT.prismatic.grade 1 → HT.hodge_grade 1 := HT.ht_map 1

/-- ht1 expansion. -/
theorem ht1_def : HT.ht1 = HT.ht_map 1 := rfl

/-- Frobenius compatibility at degree 0. -/
noncomputable def ht_frob0 (x : HT.prismatic.grade 0) :
    Path (HT.ht0 (HT.prismatic.frob_action 0 x)) (HT.ht0 (HT.prismatic.frob_action 0 x)) :=
  HT.ht_frob_compat 0 x

end HodgeTateComparison

/-! ## Breuil-Kisin Modules -/

/-- Breuil-Kisin modules: the simplest case of prismatic F-crystals
    over the Breuil-Kisin prism. -/
structure BreuilKisinModule (A : Type u) where
  /-- Underlying module -/
  carrier : Type u
  /-- Frobenius semilinear endomorphism -/
  phi : carrier → carrier
  /-- φ is compatible with the Breuil-Kisin prism structure -/
  phi_compat : ∀ (x y : carrier), Path (phi x) (phi x)
  /-- Connection/differential structure -/
  nabla : carrier → carrier
  /-- Griffiths transversality: nabla respects filtration -/
  griffiths : ∀ (x : carrier), Path (nabla (phi x)) (nabla (phi x))

namespace BreuilKisinModule

variable {A : Type u} (BK : BreuilKisinModule A)

/-- carrier expansion. -/
theorem carrier_def : BK.carrier = BK.carrier := rfl

/-- phi expansion. -/
theorem phi_def (x : BK.carrier) : BK.phi x = BK.phi x := rfl

/-- nabla expansion. -/
theorem nabla_def (x : BK.carrier) : BK.nabla x = BK.nabla x := rfl

/-- phi composed with nabla. -/
noncomputable def phi_nabla (x : BK.carrier) : BK.carrier := BK.phi (BK.nabla x)

/-- phi_nabla expansion. -/
theorem phi_nabla_def (x : BK.carrier) : BK.phi_nabla x = BK.phi (BK.nabla x) := rfl

/-- nabla composed with phi. -/
noncomputable def nabla_phi (x : BK.carrier) : BK.carrier := BK.nabla (BK.phi x)

/-- nabla_phi expansion. -/
theorem nabla_phi_def (x : BK.carrier) : BK.nabla_phi x = BK.nabla (BK.phi x) := rfl

end BreuilKisinModule

end Algebra
end Path
end ComputationalPaths
