import ComputationalPaths.Birational.FlipsFlopsPaths
import ComputationalPaths.Birational.MMPPaths

/-!
# Birational path infrastructure

This module packages flips, flops, and contractions into reusable
path-preserving MMP constructions.
-/

namespace ComputationalPaths
namespace Birational

open Path

universe u

/-- A concrete path-preserving MMP package with a chosen starting model. -/
structure PathPreservingMMPConstruction (X : Type u) where
  data : MMPPaths.MMPPathData X
  startModel : X

namespace PathPreservingMMPConstruction

variable {X : Type u} (C : PathPreservingMMPConstruction X)

/-- Canonical path generated by one selected MMP move from the start model. -/
def firstStepPath (m : MMPPaths.Move) :
    Path
      (C.data.birational.canonical (C.data.applyMove m C.startModel))
      (C.data.birational.canonical C.startModel) :=
  C.data.moveCanonicalPath m C.startModel

/-- Canonical path generated by two selected MMP moves from the start model. -/
def twoStepPath (m₁ m₂ : MMPPaths.Move) :
    Path
      (C.data.birational.canonical (C.data.applyMove m₁ (C.data.applyMove m₂ C.startModel)))
      (C.data.birational.canonical C.startModel) :=
  C.data.twoStepCanonicalPath m₁ m₂ C.startModel

/-- Primitive right-unit normalization for two-step MMP construction paths. -/
noncomputable def twoStepPathNormalize (m₁ m₂ : MMPPaths.Move) :
    RwEq
      (Path.trans (C.twoStepPath m₁ m₂) (Path.refl (C.data.birational.canonical C.startModel)))
      (C.twoStepPath m₁ m₂) :=
  C.data.twoStepNormalize m₁ m₂ C.startModel

/-- Left inverse cancellation for one-step MMP construction paths. -/
noncomputable def firstStepCancelLeft (m : MMPPaths.Move) :
    RwEq
      (Path.trans (Path.symm (C.firstStepPath m)) (C.firstStepPath m))
      (Path.refl (C.data.birational.canonical C.startModel)) :=
  C.data.moveCancelLeft m C.startModel

end PathPreservingMMPConstruction

end Birational
end ComputationalPaths
