/- Root module for ComputationalPaths.Path.OmegaGroupoidCompPaths -/

import ComputationalPaths.Path.OmegaGroupoid.CoherencePaths
import ComputationalPaths.Path.OmegaGroupoid.GroupoidProofs
import ComputationalPaths.Path.OmegaGroupoid.HigherCellPaths
import ComputationalPaths.Path.OmegaGroupoid.TruncationProof
import ComputationalPaths.Path.OmegaGroupoid.TwoCategoryStructure
import ComputationalPaths.Path.OmegaGroupoid.WeakGroupoidPaths