/-
# A focused statement for the computational-path omega-groupoid certificate

This file contains the small, statement-facing cell tower used by the Palomar
artifact.  It deliberately separates the syntax of the cells from the proof
that the tower has the advertised coherence and contraction properties.

The intended interpretation is extensional and Lean-specific:

* 1-cells are the trace-carrying `Path` records;
* 2-cells are explicit rewrite derivations generated by `Step`;
* 3-cells are generated coherence derivations, including the proof-irrelevance
  transport generator;
* dimensions 4 and above have explicit parallel-cell fillers.

Consequently the result below is a 3-truncated weak omega-groupoid certificate
in an extensional, proof-irrelevant setting.  It is not a claim that the
present hierarchy is a constructive Squier finite-derivation-type proof, nor
that `Path` is an intensional HoTT identity type.
-/

import ComputationalPaths.Path.Basic
import ComputationalPaths.Path.Rewrite.Step
import ComputationalPaths.Path.Rewrite.RwEq

namespace ComputationalPaths
namespace Path
namespace PalomarOmegaGroupoid

universe u

variable {A : Type u}

/-! ## 2-cells: explicit rewrite derivations -/

/-- A 2-cell is an explicit symmetric, reflexive, transitive rewrite derivation
between parallel computational paths. -/
inductive Derivation₂ {a b : A} : Path a b → Path a b → Type (u + 2) where
  | refl (p : Path a b) : Derivation₂ p p
  | step {p q : Path a b} : Step p q → Derivation₂ p q
  | inv {p q : Path a b} : Derivation₂ p q → Derivation₂ q p
  | vcomp {p q r : Path a b} :
      Derivation₂ p q → Derivation₂ q r → Derivation₂ p r

namespace Derivation₂

/-- Forget the derivation syntax while retaining its rewrite certificate. -/
def toRwEq {p q : Path a b} : Derivation₂ p q → RwEq p q
  | .refl _ => RwEq.refl _
  | .step s => RwEq.step s
  | .inv d => RwEq.symm (toRwEq d)
  | .vcomp d₁ d₂ => RwEq.trans (toRwEq d₁) (toRwEq d₂)

/-- Reify a symmetric, reflexive, transitive rewrite certificate. -/
def ofRwEq {p q : Path a b} : RwEq p q → Derivation₂ p q
  | .refl p => .refl p
  | .step s => .step s
  | .symm h => .inv (ofRwEq h)
  | .trans h₁ h₂ => .vcomp (ofRwEq h₁) (ofRwEq h₂)

end Derivation₂

/-! ## Horizontal composition of 2-cells -/

noncomputable def whiskerLeft {a b c : A} (f : Path a b) {p q : Path b c}
    (α : Derivation₂ p q) :
    Derivation₂ (Path.trans f p) (Path.trans f q) :=
  match α with
  | .refl _ => .refl _
  | .step s => .step (Step.trans_congr_right f s)
  | .inv d => .inv (whiskerLeft f d)
  | .vcomp d₁ d₂ => .vcomp (whiskerLeft f d₁) (whiskerLeft f d₂)

noncomputable def whiskerRight {a b c : A} {p q : Path a b}
    (α : Derivation₂ p q) (g : Path b c) :
    Derivation₂ (Path.trans p g) (Path.trans q g) :=
  match α with
  | .refl _ => .refl _
  | .step s => .step (Step.trans_congr_left g s)
  | .inv d => .inv (whiskerRight d g)
  | .vcomp d₁ d₂ => .vcomp (whiskerRight d₁ g) (whiskerRight d₂ g)

noncomputable def hcomp {a b c : A}
    {p p' : Path a b} {q q' : Path b c}
    (α : Derivation₂ p p') (β : Derivation₂ q q') :
    Derivation₂ (Path.trans p q) (Path.trans p' q') :=
  .vcomp (whiskerRight α q) (whiskerLeft p' β)

/-! ## Named coherence boundaries -/

noncomputable def associator {a b c d : A}
    (f : Path a b) (g : Path b c) (h : Path c d) :
    Derivation₂ (Path.trans (Path.trans f g) h)
      (Path.trans f (Path.trans g h)) :=
  .step (Step.trans_assoc f g h)

noncomputable def leftUnitor {a b : A} (f : Path a b) :
    Derivation₂ (Path.trans (Path.refl a) f) f :=
  .step (Step.trans_refl_left f)

noncomputable def rightUnitor {a b : A} (f : Path a b) :
    Derivation₂ (Path.trans f (Path.refl b)) f :=
  .step (Step.trans_refl_right f)

noncomputable def pentagonLeft {a b c d e : A}
    (f : Path a b) (g : Path b c) (h : Path c d) (k : Path d e) :
    Derivation₂
      (Path.trans (Path.trans (Path.trans f g) h) k)
      (Path.trans f (Path.trans g (Path.trans h k))) :=
  .vcomp (associator (Path.trans f g) h k)
    (associator f g (Path.trans h k))

noncomputable def pentagonRight {a b c d e : A}
    (f : Path a b) (g : Path b c) (h : Path c d) (k : Path d e) :
    Derivation₂
      (Path.trans (Path.trans (Path.trans f g) h) k)
      (Path.trans f (Path.trans g (Path.trans h k))) :=
  .vcomp
    (.vcomp (whiskerRight (associator f g h) k)
      (associator f (Path.trans g h) k))
    (whiskerLeft f (associator g h k))

noncomputable def triangleLeft {a b c : A}
    (f : Path a b) (g : Path b c) :
    Derivation₂
      (Path.trans (Path.trans f (Path.refl b)) g)
      (Path.trans f g) :=
  .vcomp (associator f (Path.refl b) g)
    (whiskerLeft f (leftUnitor g))

noncomputable def triangleRight {a b c : A}
    (f : Path a b) (g : Path b c) :
    Derivation₂
      (Path.trans (Path.trans f (Path.refl b)) g)
      (Path.trans f g) :=
  whiskerRight (rightUnitor f) g

/-! ## 3-cells: coherence derivations between 2-cells -/

/-- Primitive coherence generators.  The `rweq_transport` generator is the
proof-irrelevance boundary: all induced equality proofs live in `Prop`. -/
inductive MetaStep₃ : {a b : A} → {p q : Path a b} →
    Derivation₂ p q → Derivation₂ p q → Type (u + 2) where
  | vcomp_refl_left {a b : A} {p q : Path a b} (d : Derivation₂ p q) :
      MetaStep₃ (.vcomp (.refl p) d) d
  | vcomp_refl_right {a b : A} {p q : Path a b} (d : Derivation₂ p q) :
      MetaStep₃ (.vcomp d (.refl q)) d
  | vcomp_assoc {a b : A} {p q r s : Path a b}
      (d₁ : Derivation₂ p q) (d₂ : Derivation₂ q r) (d₃ : Derivation₂ r s) :
      MetaStep₃ (.vcomp (.vcomp d₁ d₂) d₃)
        (.vcomp d₁ (.vcomp d₂ d₃))
  | inv_inv {a b : A} {p q : Path a b} (d : Derivation₂ p q) :
      MetaStep₃ (.inv (.inv d)) d
  | vcomp_inv_left {a b : A} {p q : Path a b} (d : Derivation₂ p q) :
      MetaStep₃ (.vcomp (.inv d) d) (.refl q)
  | vcomp_inv_right {a b : A} {p q : Path a b} (d : Derivation₂ p q) :
      MetaStep₃ (.vcomp d (.inv d)) (.refl p)
  | inv_vcomp {a b : A} {p q r : Path a b}
      (d₁ : Derivation₂ p q) (d₂ : Derivation₂ q r) :
      MetaStep₃ (.inv (.vcomp d₁ d₂))
        (.vcomp (.inv d₂) (.inv d₁))
  | step_eq {a b : A} {p q : Path a b} (s₁ s₂ : Step p q) :
      MetaStep₃ (.step s₁) (.step s₂)
  | rweq_transport {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q}
      (h : rweq_toEq d₁.toRwEq = rweq_toEq d₂.toRwEq) :
      MetaStep₃ d₁ d₂
  | interchange {a b c : A} {f f' : Path a b} {g g' : Path b c}
      (α : Derivation₂ f f') (β : Derivation₂ g g') :
      MetaStep₃ (hcomp α β)
        (.vcomp (whiskerLeft f β) (whiskerRight α g'))
  | pentagon {a b c d e : A}
      (f : Path a b) (g : Path b c) (h : Path c d) (k : Path d e) :
      MetaStep₃ (pentagonLeft f g h k) (pentagonRight f g h k)
  | triangle {a b c : A} (f : Path a b) (g : Path b c) :
      MetaStep₃ (triangleLeft f g) (triangleRight f g)

/-- A 3-cell is a finite coherence derivation generated by `MetaStep₃`. -/
inductive Derivation₃ {a b : A} {p q : Path a b} :
    Derivation₂ p q → Derivation₂ p q → Type (u + 2) where
  | refl (d : Derivation₂ p q) : Derivation₃ d d
  | step {d₁ d₂ : Derivation₂ p q} :
      MetaStep₃ d₁ d₂ → Derivation₃ d₁ d₂
  | inv {d₁ d₂ : Derivation₂ p q} :
      Derivation₃ d₁ d₂ → Derivation₃ d₂ d₁
  | vcomp {d₁ d₂ d₃ : Derivation₂ p q} :
      Derivation₃ d₁ d₂ → Derivation₃ d₂ d₃ → Derivation₃ d₁ d₃

/-! ## Dimensions 4 and above -/

/-- Higher generators include the formal parallel-cell filler used to exhibit
the declared truncation boundary. -/
inductive MetaStep₄ : {a b : A} → {p q : Path a b} →
    {d₁ d₂ : Derivation₂ p q} →
    Derivation₃ d₁ d₂ → Derivation₃ d₁ d₂ → Type (u + 2) where
  | vcomp_refl_left {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} (m : Derivation₃ d₁ d₂) :
      MetaStep₄ (.vcomp (.refl d₁) m) m
  | vcomp_refl_right {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} (m : Derivation₃ d₁ d₂) :
      MetaStep₄ (.vcomp m (.refl d₂)) m
  | vcomp_assoc {a b : A} {p q : Path a b}
      {d₁ d₂ d₃ d₄ : Derivation₂ p q}
      (m₁ : Derivation₃ d₁ d₂) (m₂ : Derivation₃ d₂ d₃)
      (m₃ : Derivation₃ d₃ d₄) :
      MetaStep₄ (.vcomp (.vcomp m₁ m₂) m₃)
        (.vcomp m₁ (.vcomp m₂ m₃))
  | inv_inv {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} (m : Derivation₃ d₁ d₂) :
      MetaStep₄ (.inv (.inv m)) m
  | vcomp_inv_left {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} (m : Derivation₃ d₁ d₂) :
      MetaStep₄ (.vcomp (.inv m) m) (.refl d₂)
  | vcomp_inv_right {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} (m : Derivation₃ d₁ d₂) :
      MetaStep₄ (.vcomp m (.inv m)) (.refl d₁)
  | inv_vcomp {a b : A} {p q : Path a b}
      {d₁ d₂ d₃ : Derivation₂ p q}
      (m₁ : Derivation₃ d₁ d₂) (m₂ : Derivation₃ d₂ d₃) :
      MetaStep₄ (.inv (.vcomp m₁ m₂))
        (.vcomp (.inv m₂) (.inv m₁))
  | step_eq {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} (s₁ s₂ : MetaStep₃ d₁ d₂) :
      MetaStep₄ (.step s₁) (.step s₂)
  | diamond_filler {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} (m₁ m₂ : Derivation₃ d₁ d₂) :
      MetaStep₄ m₁ m₂

inductive Derivation₄ {a b : A} {p q : Path a b}
    {d₁ d₂ : Derivation₂ p q} :
    Derivation₃ d₁ d₂ → Derivation₃ d₁ d₂ → Type (u + 2) where
  | refl (m : Derivation₃ d₁ d₂) : Derivation₄ m m
  | step {m₁ m₂ : Derivation₃ d₁ d₂} :
      MetaStep₄ m₁ m₂ → Derivation₄ m₁ m₂
  | inv {m₁ m₂ : Derivation₃ d₁ d₂} :
      Derivation₄ m₁ m₂ → Derivation₄ m₂ m₁
  | vcomp {m₁ m₂ m₃ : Derivation₃ d₁ d₂} :
      Derivation₄ m₁ m₂ → Derivation₄ m₂ m₃ → Derivation₄ m₁ m₃

inductive MetaStepHigh (n : Nat) : {a b : A} → {p q : Path a b} →
    {d₁ d₂ : Derivation₂ p q} →
    {m₁ m₂ : Derivation₃ d₁ d₂} →
    Derivation₄ m₁ m₂ → Derivation₄ m₁ m₂ → Type (u + 2) where
  | vcomp_refl_left {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
      (c : Derivation₄ m₁ m₂) :
      MetaStepHigh n (.vcomp (.refl m₁) c) c
  | vcomp_refl_right {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
      (c : Derivation₄ m₁ m₂) :
      MetaStepHigh n (.vcomp c (.refl m₂)) c
  | vcomp_assoc {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ m₃ m₄ : Derivation₃ d₁ d₂}
      (c₁ : Derivation₄ m₁ m₂) (c₂ : Derivation₄ m₂ m₃)
      (c₃ : Derivation₄ m₃ m₄) :
      MetaStepHigh n (.vcomp (.vcomp c₁ c₂) c₃)
        (.vcomp c₁ (.vcomp c₂ c₃))
  | inv_inv {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
      (c : Derivation₄ m₁ m₂) :
      MetaStepHigh n (.inv (.inv c)) c
  | vcomp_inv_left {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
      (c : Derivation₄ m₁ m₂) :
      MetaStepHigh n (.vcomp (.inv c) c) (.refl m₂)
  | vcomp_inv_right {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
      (c : Derivation₄ m₁ m₂) :
      MetaStepHigh n (.vcomp c (.inv c)) (.refl m₁)
  | inv_vcomp {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ m₃ : Derivation₃ d₁ d₂}
      (c₁ : Derivation₄ m₁ m₂) (c₂ : Derivation₄ m₂ m₃) :
      MetaStepHigh n (.inv (.vcomp c₁ c₂))
        (.vcomp (.inv c₂) (.inv c₁))
  | step_eq {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
      (s₁ s₂ : MetaStep₄ m₁ m₂) :
      MetaStepHigh n (.step s₁) (.step s₂)
  | diamond_filler {a b : A} {p q : Path a b}
      {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
      (c₁ c₂ : Derivation₄ m₁ m₂) :
      MetaStepHigh n c₁ c₂

inductive DerivationHigh (n : Nat) {a b : A} {p q : Path a b}
    {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂} :
    Derivation₄ m₁ m₂ → Derivation₄ m₁ m₂ → Type (u + 2) where
  | refl (c : Derivation₄ m₁ m₂) : DerivationHigh n c c
  | step {c₁ c₂ : Derivation₄ m₁ m₂} :
      MetaStepHigh n c₁ c₂ → DerivationHigh n c₁ c₂
  | inv {c₁ c₂ : Derivation₄ m₁ m₂} :
      DerivationHigh n c₁ c₂ → DerivationHigh n c₂ c₁
  | vcomp {c₁ c₂ c₃ : Derivation₄ m₁ m₂} :
      DerivationHigh n c₁ c₂ → DerivationHigh n c₂ c₃ →
      DerivationHigh n c₁ c₃

/-! ## The indexed cell tower and certificate interface -/

def CellType (A : Type u) : Nat → Type (u + 2)
  | 0 => ULift.{u + 2, u} A
  | 1 => ULift.{u + 2, u} (Σ (a b : A), Path a b)
  | 2 => Σ (a b : A) (p q : Path a b), Derivation₂ p q
  | 3 => Σ (a b : A) (p q : Path a b)
      (d₁ d₂ : Derivation₂ p q), Derivation₃ d₁ d₂
  | 4 => Σ (a b : A) (p q : Path a b)
      (d₁ d₂ : Derivation₂ p q)
      (m₁ m₂ : Derivation₃ d₁ d₂), Derivation₄ m₁ m₂
  | n + 5 => Σ (a b : A) (p q : Path a b)
      (d₁ d₂ : Derivation₂ p q)
      (m₁ m₂ : Derivation₃ d₁ d₂)
      (c₁ c₂ : Derivation₄ m₁ m₂), DerivationHigh n c₁ c₂

structure WeakOmegaGroupoid (A : Type u) where
  cells : (n : Nat) → Type (u + 2)
  contract₃ : ∀ {a b : A} {p q : Path a b}
    (d₁ d₂ : Derivation₂ p q), Derivation₃ d₁ d₂
  contract₄ : ∀ {a b : A} {p q : Path a b}
    {d₁ d₂ : Derivation₂ p q}
    (m₁ m₂ : Derivation₃ d₁ d₂), Derivation₄ m₁ m₂
  contractHigh : ∀ {a b : A} {p q : Path a b}
    {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
    (n : Nat) (c₁ c₂ : Derivation₄ m₁ m₂), DerivationHigh n c₁ c₂
  pentagon : ∀ {a b c d e : A}
    (f : Path a b) (g : Path b c) (h : Path c d) (k : Path d e),
    Derivation₃ (pentagonLeft f g h k) (pentagonRight f g h k)
  triangle : ∀ {a b c : A} (f : Path a b) (g : Path b c),
    Derivation₃ (triangleLeft f g) (triangleRight f g)

structure CoherenceCertificate (A : Type u) where
  unit_left : ∀ {a b : A} {p q : Path a b} (d : Derivation₂ p q),
    Derivation₃ (.vcomp (.refl p) d) d
  unit_right : ∀ {a b : A} {p q : Path a b} (d : Derivation₂ p q),
    Derivation₃ (.vcomp d (.refl q)) d
  associativity : ∀ {a b : A} {p q r s : Path a b}
    (d₁ : Derivation₂ p q) (d₂ : Derivation₂ q r) (d₃ : Derivation₂ r s),
    Derivation₃ (.vcomp (.vcomp d₁ d₂) d₃)
      (.vcomp d₁ (.vcomp d₂ d₃))
  inverse_inverse : ∀ {a b : A} {p q : Path a b} (d : Derivation₂ p q),
    Derivation₃ (.inv (.inv d)) d
  inverse_left : ∀ {a b : A} {p q : Path a b} (d : Derivation₂ p q),
    Derivation₃ (.vcomp (.inv d) d) (.refl q)
  inverse_right : ∀ {a b : A} {p q : Path a b} (d : Derivation₂ p q),
    Derivation₃ (.vcomp d (.inv d)) (.refl p)
  inverse_composition : ∀ {a b : A} {p q r : Path a b}
    (d₁ : Derivation₂ p q) (d₂ : Derivation₂ q r),
    Derivation₃ (.inv (.vcomp d₁ d₂))
      (.vcomp (.inv d₂) (.inv d₁))
  interchange : ∀ {a b c : A} {f f' : Path a b} {g g' : Path b c}
    (α : Derivation₂ f f') (β : Derivation₂ g g'),
    Derivation₃ (hcomp α β)
      (.vcomp (whiskerLeft f β) (whiskerRight α g'))
  pentagon : ∀ {a b c d e : A}
    (f : Path a b) (g : Path b c) (h : Path c d) (k : Path d e),
    Derivation₃ (pentagonLeft f g h k) (pentagonRight f g h k)
  triangle : ∀ {a b c : A} (f : Path a b) (g : Path b c),
    Derivation₃ (triangleLeft f g) (triangleRight f g)

structure OmegaGroupoidCertificate (A : Type u) where
  omega : WeakOmegaGroupoid A
  cells_are_explicit : omega.cells = CellType A
  two_cell_sound : ∀ {a b : A} {p q : Path a b},
    Derivation₂ p q → RwEq p q
  two_cell_complete : ∀ {a b : A} {p q : Path a b},
    RwEq p q → Derivation₂ p q
  two_cell_iff : ∀ {a b : A} {p q : Path a b},
    Nonempty (Derivation₂ p q) ↔ RwEqProp p q
  two_cell_to_rw_eq_roundtrip : ∀ {a b : A} {p q : Path a b}
    (h : RwEq p q),
    Derivation₂.toRwEq (Derivation₂.ofRwEq h) = h
  two_cell_reification_roundtrip : ∀ {a b : A} {p q : Path a b}
    (d : Derivation₂ p q),
    Derivation₂.ofRwEq (Derivation₂.toRwEq d) = d
  three_cell_sound : ∀ {a b : A} {p q : Path a b}
    {d₁ d₂ : Derivation₂ p q}, Derivation₃ d₁ d₂ →
      rweq_toEq d₁.toRwEq = rweq_toEq d₂.toRwEq
  contractibility₃ : ∀ {a b : A} {p q : Path a b}
    (d₁ d₂ : Derivation₂ p q), Derivation₃ d₁ d₂
  contractibility₄ : ∀ {a b : A} {p q : Path a b}
    {d₁ d₂ : Derivation₂ p q}
    (m₁ m₂ : Derivation₃ d₁ d₂), Derivation₄ m₁ m₂
  contractibility_high : ∀ {a b : A} {p q : Path a b}
    {d₁ d₂ : Derivation₂ p q} {m₁ m₂ : Derivation₃ d₁ d₂}
    (n : Nat) (c₁ c₂ : Derivation₄ m₁ m₂), DerivationHigh n c₁ c₂
  coherence : CoherenceCertificate A
  trace_metadata_nontrivial : ∀ (a : A),
    Path.ofEq (rfl : a = a) ≠ Path.refl a
  two_cell_syntax_nontrivial : ∀ (a : A) (p : Path a a),
    Derivation₂.refl p ≠ Derivation₂.vcomp (.refl p) (.refl p)

end PalomarOmegaGroupoid
end Path
end ComputationalPaths
