/-
# Second Homotopy Group of Surfaces

This module formalizes the second homotopy groups π₂ of various surfaces
and related spaces.

## Mathematical Background

### π₂(S²) ≃ ℤ

The 2-sphere has π₂(S²) ≃ ℤ, generated by the identity map id : S² → S².
This is the first non-trivial higher homotopy group of spheres.

### π₂ of Orientable Surfaces

For closed orientable surfaces Σ_g of genus g:
- π₂(S²) = π₂(Σ_0) ≃ ℤ (sphere is special)
- π₂(Σ_g) = 0 for g ≥ 1 (universal cover is hyperbolic plane, contractible)

The key insight: for g ≥ 1, Σ_g is a K(π₁, 1) space, so all higher
homotopy groups vanish.

### π₂ of Real Projective Spaces

For RP^n:
- π₂(RP²) ≃ ℤ (universal cover is S²)
- π₂(RP^n) = 0 for n ≥ 3 (universal cover is S^n with π₂ = 0)

### π₂ of Complex and Quaternionic Projective Spaces

- π₂(CP^n) ≃ ℤ for n ≥ 1 (from complex Hopf fibration)
- π₂(HP^n) = 0 for n ≥ 1 (3-connected)

## Key Results

| Space | π₂ | Reason |
|-------|-----|--------|
| S² | ℤ | Hopf degree |
| Σ_g (g≥1) | 0 | K(G,1) |
| RP² | ℤ | Cover of S² |
| CP^n | ℤ | Hopf fibration |
| HP^n | 0 | 3-connected |

## References

- Hatcher, "Algebraic Topology", Section 4.1
- May, "A Concise Course in Algebraic Topology", Chapter 9
- HoTT Book, Chapter 8
-/

import ComputationalPaths.Path.Homotopy.HigherHomotopy
import ComputationalPaths.Path.Homotopy.CoveringSpace
import ComputationalPaths.Path.HIT.Sphere
import ComputationalPaths.Path.HIT.ProjectiveSpaces
import ComputationalPaths.Path.HIT.ComplexProjectiveSpaces
import ComputationalPaths.Path.HIT.QuaternionicProjectiveSpaces
import ComputationalPaths.Path.HIT.OrientableSurface

namespace ComputationalPaths
namespace Path
namespace Pi2Surfaces

universe u

/-! ## π₂(S²) ≃ ℤ -/

/-- The second homotopy group of S² is ℤ.

**Proof via Hopf fibration**:
The Hopf fibration S¹ → S³ → S² gives a long exact sequence:
  π₂(S¹) → π₂(S³) → π₂(S²) → π₁(S¹) → π₁(S³)
     0    →    0    → π₂(S²) →    ℤ   →    0

Exactness gives π₂(S²) ≃ ℤ.

**Alternative: Hurewicz theorem**
S² is simply connected, so by Hurewicz:
  π₂(S²) ≃ H₂(S²) ≃ ℤ -/
theorem sphere2_pi2_equiv_int :
    ∃ desc : String, desc = "π₂(S²) ≃ ℤ via Hopf fibration or Hurewicz" :=
  ⟨_, rfl⟩

/-- The generator of π₂(S²) is the identity map.

The identity map id : S² → S² has Hopf degree 1 and generates π₂(S²).
Maps S² → S² correspond to integers via their degree. -/
theorem sphere2_pi2_generator :
    ∃ desc : String, desc = "π₂(S²) generated by id : S² → S² (degree 1)" :=
  ⟨_, rfl⟩

/-- π₂(Sⁿ) = 0 for n ≥ 3.

For n ≥ 3, the sphere Sⁿ is 2-connected:
- π₁(Sⁿ) = 0 (simply connected)
- π₂(Sⁿ) = 0 (by cellular approximation: maps S² → Sⁿ factor through Sⁿ₂ = *)

This follows from the fact that the 2-skeleton of the standard cell
structure on Sⁿ (n ≥ 3) is just a point. -/
theorem sphereN_pi2_trivial (n : Nat) (_hn : n ≥ 3) :
    ∃ desc : String, desc = s!"π₂(S^{n}) = 0 (n ≥ 3)" :=
  ⟨_, rfl⟩

/-! ## π₂ of Orientable Surfaces -/

/-- π₂(Σ_g) = 0 for genus g ≥ 1 orientable surfaces.

**Key fact**: For g ≥ 1, Σ_g is a K(π₁, 1) space (Eilenberg-MacLane space).

**Proof**:
1. The universal cover of Σ_g is the hyperbolic plane ℍ² (for g ≥ 2)
   or ℝ² (for g = 1, torus)
2. Both ℍ² and ℝ² are contractible
3. So π_k(Σ_g) = π_k(universal cover) = 0 for k ≥ 2

**Alternatively**: Use the long exact sequence of the universal covering:
  π₂(X̃) → π₂(Σ_g) → π₁(fiber)
     0   → π₂(Σ_g) →    0
So π₂(Σ_g) = 0. -/
theorem orientableSurface_pi2_trivial (g : Nat) (_hg : g ≥ 1) :
    ∃ desc : String,
      desc = s!"π₂(Σ_{g}) = 0 (universal cover is contractible)" :=
  ⟨_, rfl⟩

/-- Torus T² = Σ_1 has π₂(T²) = 0.

The torus is a K(ℤ², 1):
- π₁(T²) ≃ ℤ × ℤ
- π_k(T²) = 0 for k ≥ 2

Universal cover: T² → ℝ² (contractible). -/
theorem torus_pi2_trivial :
    ∃ desc : String, desc = "π₂(T²) = 0 (universal cover is ℝ²)" :=
  ⟨_, rfl⟩

/-- Higher genus surfaces are K(G, 1).

For g ≥ 2, Σ_g is a K(G, 1) where G is the surface group:
  G = ⟨a₁, b₁, ..., a_g, b_g | [a₁,b₁]⋯[a_g,b_g] = 1⟩

This means:
- π₁(Σ_g) = G
- π_k(Σ_g) = 0 for k ≥ 2 -/
theorem higherGenusSurface_is_KG1 (g : Nat) (_hg : g ≥ 2) :
    ∃ desc : String,
      desc = s!"Σ_{g} is K(G,1) where G is the surface group" :=
  ⟨_, rfl⟩

/-! ## π₂ of Projective Spaces -/

/-- π₂(RP²) ≃ ℤ.

**Proof via covering space**:
The universal cover of RP² is S².
The covering S² → RP² is a 2-fold cover.

Long exact sequence of the fibration:
  π₂(S²) → π₂(RP²) → π₁(fiber)
     ℤ   → π₂(RP²) →    0

So π₂(RP²) ≃ π₂(S²) ≃ ℤ.

The projection map S² → RP² induces the identity on π₂. -/
theorem rp2_pi2_equiv_int :
    ∃ desc : String, desc = "π₂(RP²) ≃ ℤ (from covering S² → RP²)" :=
  ⟨_, rfl⟩

/-- π₂(RP^n) = 0 for n ≥ 3.

For n ≥ 3, the universal cover is Sⁿ which has π₂(Sⁿ) = 0.
By covering space theory, π₂(RP^n) = π₂(Sⁿ) = 0. -/
theorem rpN_pi2_trivial (n : Nat) (_hn : n ≥ 3) :
    ∃ desc : String, desc = s!"π₂(RP^{n}) = 0 (universal cover is S^{n})" :=
  ⟨_, rfl⟩

/-- π₂(CP^n) ≃ ℤ for n ≥ 1.

**Proof via Hopf fibration**:
The fibration S¹ → S^{2n+1} → CP^n gives:
  π₂(S^{2n+1}) → π₂(CP^n) → π₁(S¹) → π₁(S^{2n+1})
       0       → π₂(CP^n) →    ℤ   →      0

So π₂(CP^n) ≃ ℤ for all n ≥ 1.

**Geometric interpretation**: The generator is the inclusion CP¹ = S² ↪ CP^n. -/
theorem cpN_pi2_equiv_int (n : Nat) (_hn : n ≥ 1) :
    ∃ desc : String,
      desc = s!"π₂(CP^{n}) ≃ ℤ via Hopf fibration S¹ → S^{2*n+1} → CP^{n}" :=
  ⟨_, rfl⟩

/-- π₂(HP^n) = 0 for n ≥ 1.

HP^n is 3-connected: π₁ = π₂ = π₃ = 0.

**Proof via Hopf fibration**:
The fibration S³ → S^{4n+3} → HP^n gives:
  π₂(S^{4n+3}) → π₂(HP^n) → π₁(S³)
       0       → π₂(HP^n) →    0

So π₂(HP^n) = 0. -/
theorem hpN_pi2_trivial (n : Nat) (_hn : n ≥ 1) :
    ∃ desc : String, desc = s!"π₂(HP^{n}) = 0 (3-connected)" :=
  ⟨_, rfl⟩

/-! ## π₂ of Non-Orientable Surfaces -/

/-- π₂(Klein bottle) = 0.

The Klein bottle K has:
- π₁(K) ≃ ℤ ⋊ ℤ (semidirect product)
- Universal cover: ℝ² (contractible)
- So π_k(K) = 0 for k ≥ 2 -/
theorem klein_pi2_trivial :
    ∃ desc : String, desc = "π₂(Klein bottle) = 0 (universal cover is ℝ²)" :=
  ⟨_, rfl⟩

/-- π₂(N_g) = 0 for non-orientable surface N_g (g ≥ 2).

Non-orientable surfaces N_g (g ≥ 2) have:
- π₁(N_g) = ⟨a₁, ..., a_g | a₁²⋯a_g² = 1⟩
- Universal cover: ℝ² (contractible)
- So π_k(N_g) = 0 for k ≥ 2 -/
theorem nonOrientableSurface_pi2_trivial (g : Nat) (_hg : g ≥ 2) :
    ∃ desc : String,
      desc = s!"π₂(N_{g}) = 0 (universal cover is contractible)" :=
  ⟨_, rfl⟩

/-! ## The Hopf Invariant and π₂ -/

/-- The Hopf invariant relates π₃(S²) to π₂(S²).

For the Hopf fibration η : S³ → S²:
- η generates π₃(S²) ≃ ℤ
- The Hopf invariant H(η) = 1

The Hopf invariant H : π_{2n-1}(Sⁿ) → ℤ is defined for maps S^{2n-1} → Sⁿ.
For n = 2: H : π₃(S²) → ℤ. -/
theorem hopf_invariant_pi2 :
    ∃ desc : String,
      desc = "Hopf invariant H : π₃(S²) → ℤ with H(η) = 1 for Hopf map" :=
  ⟨_, rfl⟩

/-! ## Freudenthal Suspension and π₂ -/

/-- Freudenthal suspension theorem for π₂.

The suspension homomorphism Σ : π_k(Sⁿ) → π_{k+1}(S^{n+1}) satisfies:
- Σ is an isomorphism for k < 2n - 1
- Σ is surjective for k = 2n - 1

For π₂:
- Σ : π₂(S²) → π₃(S³) is surjective (2 = 2·2 - 2)
- Both sides are ≃ ℤ, and Σ is an isomorphism -/
theorem freudenthal_pi2 :
    ∃ desc : String,
      desc = "Freudenthal: Σ : π₂(S²) → π₃(S³) is an isomorphism, both ≃ ℤ" :=
  ⟨_, rfl⟩

/-! ## Summary Table -/

/-- Summary of π₂ computations.

| Space | π₂ | Reason |
|-------|-----|--------|
| S² | ℤ | Hopf/Hurewicz |
| Sⁿ (n≥3) | 0 | 2-connected |
| T² | 0 | K(ℤ²,1) |
| Σ_g (g≥1) | 0 | K(G,1) |
| RP² | ℤ | Cover by S² |
| RP^n (n≥3) | 0 | Cover by Sⁿ |
| CP^n (n≥1) | ℤ | Hopf fibration |
| HP^n (n≥1) | 0 | 3-connected |
| Klein | 0 | K(G,1) |
| N_g (g≥2) | 0 | K(G,1) |
-/
theorem pi2_summary :
    ∃ desc : String,
      desc = "π₂: S² ≃ ℤ, RP² ≃ ℤ, CP^n ≃ ℤ; surfaces (g≥1) and HP^n = 0" :=
  ⟨_, rfl⟩

/-! ## Key Insight: K(G,1) Spaces

Most surfaces have trivial π₂ because they are K(G,1) spaces.

**Definition**: X is a K(G,1) (Eilenberg-MacLane space) if:
- π₁(X) = G
- π_k(X) = 0 for k ≠ 1

**K(G,1) property implies**:
- Universal cover is contractible
- X is determined up to homotopy by G
- H_*(X; M) ≃ group homology H_*(G; M)

**Examples of K(G,1)**:
- S¹ = K(ℤ, 1)
- T² = K(ℤ², 1)
- Σ_g (g ≥ 1) = K(SurfaceGroup_g, 1)
- Klein bottle = K(ℤ ⋊ ℤ, 1)
- ⋁ⁿ S¹ = K(F_n, 1)
-/

theorem surfaces_are_KG1 :
    ∃ desc : String,
      desc = "Closed surfaces Σ_g (g≥1) are K(G,1): π_k = 0 for k ≥ 2" :=
  ⟨_, rfl⟩

end Pi2Surfaces
end Path
end ComputationalPaths
