import ComputationalPaths.Path.Topology.OpenGeometricComputationalPath
import ComputationalPaths.Path.Homotopy.PresentedGroupoidRealization

/-!
# Geometric adapter for presented computational paths

The SVK paper has two complementary presentations of the same data:

* `Presented.RawPath`, generated by `refl`, graph edges, `symm`, and `trans`;
* the Mathlib topological realization of the presented path groupoid.

This file connects those presentations through `OpenGeometricCompPath`.  A
graph edge is realized by the canonical one-simplex path in the nerve, and
every raw presented path is transported recursively to a coherent geometric
computational path.  Its geometric coordinate can then be read directly as an
arrow of the realized topological fundamental groupoid.

This is an adapter, not a replacement for the presented SVK theorem: the
algebraic encode/decode proof remains the theorem that identifies the full
amalgamated product.
-/

namespace ComputationalPaths
namespace Path
namespace Presented
namespace Realization
namespace GeometricAdapter

open CategoryTheory
open scoped FundamentalGroupoid
attribute [local instance] _root_.Path.Homotopic.setoid

universe u v

variable {G : Graph.{u, v}} (P : Presentation G)

/-! ## The presentation's geometric primitive steps -/

/-- The type of graph edges with their source and target retained in the data. -/
abbrev EdgeStep (G : Graph.{u, v}) :=
  Σ x : G.Point, Σ y : G.Point, G.Edge x y

/-- Regard a graph edge as a morphism of the presented path groupoid. -/
noncomputable def edgeMorphism {x y : G.Point} (e : G.Edge x y) :
    Object.ofPoint (P := P) x ⟶ Object.ofPoint (P := P) y :=
  PathClass.ofRaw (P := P) (RawPath.edge e)

/-- The canonical geometric step system attached to a presented path space. -/
noncomputable def presentedStepSystem :
    GeometricTopology.GeometricStepSystem
      (topologicalRealization P) (EdgeStep G) where
  src s := TopologicalNerve.nerveVertex (Object.ofPoint (P := P) s.1)
  tgt s := TopologicalNerve.nerveVertex (Object.ofPoint (P := P) s.2.1)
  realize s := TopologicalNerve.nerveEdge (edgeMorphism P s.2.2)

/-! ## Raw paths transported to coherent geometric paths -/

open GeometricTopology

/-- Recursively realize a presented raw path as an open geometric path. -/
noncomputable def rawPathToGeometric
    {x y : G.Point} (p : RawPath G x y) :
    OpenGeometricCompPath (presentedStepSystem P)
      (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) x))
      (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) y)) :=
  match p with
  | RawPath.refl x =>
      openRefl (presentedStepSystem P)
        (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) x))
  | RawPath.edge e =>
      ofGeometricStep (presentedStepSystem P) ⟨_, _, e⟩
  | RawPath.symm p =>
      openSymm (presentedStepSystem P) (rawPathToGeometric p)
  | RawPath.trans p q =>
      openTrans (presentedStepSystem P)
        (rawPathToGeometric p) (rawPathToGeometric q)

/-! ## Reading the adapter in the topological fundamental groupoid -/

/-- The topological fundamental-groupoid arrow carried by a geometric path. -/
noncomputable def geometricArrow
    {x y : G.Point} (p : RawPath G x y) :
    FundamentalGroupoid.fromTop
        (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) x)) ⟶
      FundamentalGroupoid.fromTop
        (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) y) :
          topologicalRealization P) :=
  Quotient.mk' (rawPathToGeometric P p).geometric

/-- The geometric edge used by the adapter is the paper's realized nerve edge. -/
noncomputable def edgeGeometricPath {x y : G.Point} (e : G.Edge x y) :
    _root_.Path
      (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) x))
      (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) y) :
        topologicalRealization P) :=
  (rawPathToGeometric P (RawPath.edge e)).geometric

/-- The comparison-functor arrow associated to a primitive presentation edge. -/
noncomputable def edgeComparisonArrow {x y : G.Point} (e : G.Edge x y) :
    (topologicalComparisonFunctor P).obj (Object.ofPoint (P := P) x) ⟶
      (topologicalComparisonFunctor P).obj (Object.ofPoint (P := P) y) :=
  (topologicalComparisonFunctor P).map (edgeMorphism P e)

theorem edgeGeometricPath_is_nerveEdge {x y : G.Point} (e : G.Edge x y) :
    edgeGeometricPath P e = TopologicalNerve.nerveEdge (edgeMorphism P e) := by
  simp [edgeGeometricPath, rawPathToGeometric, presentedStepSystem,
    GeometricTopology.ofGeometricStep]

theorem edgeGeometricArrow_is_comparison {x y : G.Point} (e : G.Edge x y) :
    geometricArrow P (RawPath.edge e) = edgeComparisonArrow P e := by
  simp [geometricArrow, edgeComparisonArrow, rawPathToGeometric,
    presentedStepSystem, GeometricTopology.ofGeometricStep,
    topologicalComparisonFunctor, TopologicalNerve.nerveRealizationFunctor]

theorem rawPathGeometricArrow_is_comparison {x y : G.Point}
    (p : RawPath G x y) :
    geometricArrow P p =
      (topologicalComparisonFunctor P).map (PathClass.ofRaw (P := P) p) := by
  induction p with
  | refl x =>
      change Quotient.mk'
          (_root_.Path.refl
            (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) x))) =
        (topologicalComparisonFunctor P).map
          (𝟙 (Object.ofPoint (P := P) x))
      rw [(topologicalComparisonFunctor P).map_id]
      rfl
  | edge e =>
      exact edgeGeometricArrow_is_comparison P e
  | symm p ih =>
      calc
        geometricArrow P p.symm =
            CategoryTheory.Groupoid.inv (geometricArrow P p) := by
          rfl
        _ = CategoryTheory.Groupoid.inv
            ((topologicalComparisonFunctor P).map
              (PathClass.ofRaw (P := P) p)) := by
          rw [ih]
        _ = (topologicalComparisonFunctor P).map
            (CategoryTheory.Groupoid.inv (PathClass.ofRaw (P := P) p)) := by
          calc
            CategoryTheory.Groupoid.inv
                ((topologicalComparisonFunctor P).map
                  (PathClass.ofRaw (P := P) p)) =
                CategoryTheory.inv
                  ((topologicalComparisonFunctor P).map
                    (PathClass.ofRaw (P := P) p)) :=
              CategoryTheory.Groupoid.inv_eq_inv _
            _ = (topologicalComparisonFunctor P).map
                (CategoryTheory.inv (PathClass.ofRaw (P := P) p)) :=
              ((topologicalComparisonFunctor P).map_inv _).symm
            _ = (topologicalComparisonFunctor P).map
                (CategoryTheory.Groupoid.inv (PathClass.ofRaw (P := P) p)) := by
              rw [CategoryTheory.Groupoid.inv_eq_inv]
        _ = (topologicalComparisonFunctor P).map
            (PathClass.ofRaw (P := P) p.symm) := by
          rfl
  | trans p q ihp ihq =>
      change
        (Quotient.mk' (rawPathToGeometric P p).geometric) ≫
          (Quotient.mk' (rawPathToGeometric P q).geometric) =
          (topologicalComparisonFunctor P).map
            (PathClass.ofRaw (P := P) p ≫
              PathClass.ofRaw (P := P) q)
      rw [(topologicalComparisonFunctor P).map_comp]
      exact congrArg₂ (fun f g => f ≫ g) ihp ihq

/-! ## A compact adapter certificate -/

/-- The data needed to use the presented path groupoid geometrically. -/
structure Certificate where
  stepSystem :
    GeometricTopology.GeometricStepSystem
      (topologicalRealization P) (EdgeStep G)
  edgePath {x y : G.Point} (e : G.Edge x y) :
    _root_.Path
      (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) x))
      (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) y) :
        topologicalRealization P)
  edgeArrow {x y : G.Point} (e : G.Edge x y) :
    FundamentalGroupoid.fromTop
        (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) x)) ⟶
      FundamentalGroupoid.fromTop
        (TopologicalNerve.nerveVertex (Object.ofPoint (P := P) y) :
          topologicalRealization P)
  rawPathArrow {x y : G.Point} (p : RawPath G x y) :
    geometricArrow P p =
      (topologicalComparisonFunctor P).map (PathClass.ofRaw (P := P) p)

noncomputable def certificate : Certificate P where
  stepSystem := presentedStepSystem P
  edgePath := edgeGeometricPath P
  edgeArrow := fun e => geometricArrow (P := P) (RawPath.edge e)
  rawPathArrow := rawPathGeometricArrow_is_comparison P

end GeometricAdapter
end Realization
end Presented
end Path
end ComputationalPaths
