/-
# Fundamental groups of presented computational path spaces

A `Graph` supplies points and proof-relevant generating paths.  `RawPath` freely
adds reflexivity, composition, and reversal.  A `Presentation` supplies named
two-dimensional relators, and `Homotopy` is generated from those relators
together with the groupoid laws and congruence.

The quotient of raw paths by generated homotopy is a strict groupoid.  Its
automorphism group at a chosen point is `PiOne`.  Unlike the global
`PathRwQuot`, this construction does not import function-space rewrite rules:
the homotopies are exactly those generated by the presentation.

This module supplies the path-space object needed to state non-collapsing SVK
as a fundamental-group theorem rather than as an unstructured normal-form
quotient.
-/

import ComputationalPaths.Path.Algebra.FreeGroupoid

namespace ComputationalPaths
namespace Path
namespace Presented

universe u v

/-- A bundled group equivalence for explicitly supplied operations.  This
project-local structure avoids imposing external algebraic typeclasses while
recording that the underlying equivalence preserves multiplication, identity,
and inversion. -/
structure GroupEquiv (G : Type u) (H : Type v)
    (mulG : G → G → G) (oneG : G) (invG : G → G)
    (mulH : H → H → H) (oneH : H) (invH : H → H) :
    Type (max u v) where
  equiv : SimpleEquiv G H
  map_mul : ∀ x y : G,
    equiv.toFun (mulG x y) = mulH (equiv.toFun x) (equiv.toFun y)
  map_one : equiv.toFun oneG = oneH
  map_inv : ∀ x : G, equiv.toFun (invG x) = invH (equiv.toFun x)

/-- A proof-relevant directed graph of path generators. -/
structure Graph where
  Point : Type u
  Edge : Point → Point → Type v

/-- Raw computational paths freely generated by a graph. -/
inductive RawPath (G : Graph.{u, v}) : G.Point → G.Point → Type (max u v) where
  | refl (x : G.Point) : RawPath G x x
  | edge {x y : G.Point} (e : G.Edge x y) : RawPath G x y
  | symm {x y : G.Point} (p : RawPath G x y) : RawPath G y x
  | trans {x y z : G.Point} (p : RawPath G x y) (q : RawPath G y z) :
      RawPath G x z

namespace RawPath

variable {G : Graph.{u, v}}
variable {a b c d : G.Point}

/-- Paper notation for raw path composition. -/
infixr:80 " ⬝ᵣ " => RawPath.trans

/-- Paper notation for raw path reversal. -/
postfix:max "⁻¹ᵣ" => RawPath.symm

end RawPath

/-- A path presentation consists of named relators between parallel raw paths. -/
structure Presentation (G : Graph.{u, v}) where
  Relator : {a b : G.Point} → RawPath G a b → RawPath G a b → Prop

/-- Homotopy generated by the named relators and the groupoid laws. -/
inductive Homotopy {G : Graph.{u, v}} (P : Presentation G) :
    {a b : G.Point} → RawPath G a b → RawPath G a b → Prop where
  | refl (p : RawPath G a b) : Homotopy P p p
  | relator {p q : RawPath G a b} : P.Relator p q → Homotopy P p q
  | symm {p q : RawPath G a b} : Homotopy P p q → Homotopy P q p
  | trans {p q r : RawPath G a b} :
      Homotopy P p q → Homotopy P q r → Homotopy P p r
  | inv_congr {p q : RawPath G a b} :
      Homotopy P p q → Homotopy P p.symm q.symm
  | comp_congr {p p' : RawPath G a b} {q q' : RawPath G b c} :
      Homotopy P p p' → Homotopy P q q' →
        Homotopy P (RawPath.trans p q) (RawPath.trans p' q')
  | refl_trans (p : RawPath G a b) :
      Homotopy P (RawPath.trans (RawPath.refl a) p) p
  | trans_refl (p : RawPath G a b) :
      Homotopy P (RawPath.trans p (RawPath.refl b)) p
  | trans_assoc (p : RawPath G a b) (q : RawPath G b c)
      (r : RawPath G c d) :
      Homotopy P
        (RawPath.trans (RawPath.trans p q) r)
        (RawPath.trans p (RawPath.trans q r))
  | symm_trans (p : RawPath G a b) :
      Homotopy P (RawPath.trans p.symm p) (RawPath.refl b)
  | trans_symm (p : RawPath G a b) :
      Homotopy P (RawPath.trans p p.symm) (RawPath.refl a)
  | symm_symm (p : RawPath G a b) :
      Homotopy P p.symm.symm p
  | symm_refl (a : G.Point) :
      Homotopy P (RawPath.symm (RawPath.refl a)) (RawPath.refl a)
  | symm_comp (p : RawPath G a b) (q : RawPath G b c) :
      Homotopy P
        (RawPath.symm (RawPath.trans p q))
        (RawPath.trans q.symm p.symm)

namespace Homotopy

variable {G : Graph.{u, v}} {P : Presentation G}
variable {a b c : G.Point}

/-- Composition is congruent in its left argument. -/
theorem comp_congr_left {p p' : RawPath G a b} (q : RawPath G b c)
    (h : Homotopy P p p') :
    Homotopy P (RawPath.trans p q) (RawPath.trans p' q) :=
  Homotopy.comp_congr h (Homotopy.refl q)

/-- Composition is congruent in its right argument. -/
theorem comp_congr_right (p : RawPath G a b) {q q' : RawPath G b c}
    (h : Homotopy P q q') :
    Homotopy P (RawPath.trans p q) (RawPath.trans p q') :=
  Homotopy.comp_congr (Homotopy.refl p) h

end Homotopy

/-- The generated homotopy relation as a setoid on each path fiber. -/
noncomputable def homotopySetoid {G : Graph.{u, v}} (P : Presentation G)
    (a b : G.Point) : Setoid (RawPath G a b) where
  r := Homotopy P
  iseqv := by
    refine ⟨Homotopy.refl, ?_, ?_⟩
    · intro p q h
      exact Homotopy.symm h
    · intro p q r h₁ h₂
      exact Homotopy.trans h₁ h₂

/-- Homotopy classes of presented paths. -/
abbrev PathClass {G : Graph.{u, v}} (P : Presentation G)
    (a b : G.Point) : Type (max u v) :=
  Quot (homotopySetoid P a b).r

namespace PathClass

variable {G : Graph.{u, v}} {P : Presentation G}
variable {a b c d : G.Point}

/-- Embed a raw path into its homotopy class. -/
noncomputable def ofRaw (p : RawPath G a b) : PathClass P a b :=
  Quot.mk _ p

/-- The identity path class. -/
noncomputable def id (a : G.Point) : PathClass P a a :=
  ofRaw (RawPath.refl a)

/-- Compose presented path classes. -/
noncomputable def comp (x : PathClass P a b) (y : PathClass P b c) :
    PathClass P a c :=
  Quot.lift
    (fun p =>
      Quot.lift
        (fun q => ofRaw (RawPath.trans p q))
        (fun q q' hq =>
          Quot.sound (Homotopy.comp_congr (Homotopy.refl p) hq))
        y)
    (fun p p' hp => by
      induction y using Quot.ind with
      | _ q =>
          exact Quot.sound (Homotopy.comp_congr hp (Homotopy.refl q)))
    x

/-- Reverse a presented path class. -/
noncomputable def inv (x : PathClass P a b) : PathClass P b a :=
  Quot.lift
    (fun p => ofRaw p.symm)
    (fun _ _ h => Quot.sound (Homotopy.inv_congr h))
    x

@[simp] theorem comp_id_left (x : PathClass P a b) :
    comp (id a) x = x := by
  induction x using Quot.ind with
  | _ p =>
      exact Quot.sound (Homotopy.refl_trans p)

@[simp] theorem comp_id_right (x : PathClass P a b) :
    comp x (id b) = x := by
  induction x using Quot.ind with
  | _ p =>
      exact Quot.sound (Homotopy.trans_refl p)

@[simp] theorem comp_assoc (x : PathClass P a b) (y : PathClass P b c)
    (z : PathClass P c d) :
    comp (comp x y) z = comp x (comp y z) := by
  induction x using Quot.ind with
  | _ p =>
      induction y using Quot.ind with
      | _ q =>
          induction z using Quot.ind with
          | _ r =>
              exact Quot.sound (Homotopy.trans_assoc p q r)

@[simp] theorem inv_comp (x : PathClass P a b) :
    comp (inv x) x = id b := by
  induction x using Quot.ind with
  | _ p =>
      exact Quot.sound (Homotopy.symm_trans p)

@[simp] theorem comp_inv (x : PathClass P a b) :
    comp x (inv x) = id a := by
  induction x using Quot.ind with
  | _ p =>
      exact Quot.sound (Homotopy.trans_symm p)

@[simp] theorem inv_inv (x : PathClass P a b) :
    inv (inv x) = x := by
  induction x using Quot.ind with
  | _ p =>
      exact Quot.sound (Homotopy.symm_symm p)

@[simp] theorem inv_id :
    inv (id a : PathClass P a a) = id a :=
  Quot.sound (Homotopy.symm_refl a)

@[simp] theorem inv_comp_order (x : PathClass P a b) (y : PathClass P b c) :
    inv (comp x y) = comp (inv y) (inv x) := by
  induction x using Quot.ind with
  | _ p =>
      induction y using Quot.ind with
      | _ q =>
          exact Quot.sound (Homotopy.symm_comp p q)

end PathClass

/-- The strict groupoid presented by generators and relators. -/
noncomputable def groupoid {G : Graph.{u, v}} (P : Presentation G) :
    Algebra.CPGroupoid where
  Obj := G.Point
  Hom := PathClass P
  id := PathClass.id
  comp := PathClass.comp
  inv := PathClass.inv
  comp_assoc := PathClass.comp_assoc
  id_comp := PathClass.comp_id_left
  comp_id := PathClass.comp_id_right
  inv_comp := PathClass.inv_comp
  comp_inv := PathClass.comp_inv

/-- The fundamental group of a presented path space at `a`: the automorphism
group of `a` in its generated path groupoid. -/
abbrev PiOne {G : Graph.{u, v}} (P : Presentation G) (a : G.Point) :
    Type (max u v) :=
  (groupoid P).Hom a a

namespace PiOne

variable {G : Graph.{u, v}} {P : Presentation G} {a : G.Point}

/-- Identity element of a presented fundamental group. -/
noncomputable def id : PiOne P a :=
  PathClass.id a

/-- Multiplication in a presented fundamental group. -/
noncomputable def mul (x y : PiOne P a) : PiOne P a :=
  PathClass.comp x y

/-- Inversion in a presented fundamental group. -/
noncomputable def inv (x : PiOne P a) : PiOne P a :=
  PathClass.inv x

/-- A raw loop determines an element of the presented fundamental group. -/
noncomputable def ofRaw (p : RawPath G a a) : PiOne P a :=
  PathClass.ofRaw p

/-- A generating loop determines an element of the presented fundamental group. -/
noncomputable def ofEdge (e : G.Edge a a) : PiOne P a :=
  ofRaw (RawPath.edge e)

@[simp] theorem mul_assoc (x y z : PiOne P a) :
    mul (mul x y) z = mul x (mul y z) :=
  PathClass.comp_assoc x y z

@[simp] theorem id_mul (x : PiOne P a) : mul id x = x :=
  PathClass.comp_id_left x

@[simp] theorem mul_id (x : PiOne P a) : mul x id = x :=
  PathClass.comp_id_right x

@[simp] theorem inv_mul (x : PiOne P a) : mul (inv x) x = id :=
  PathClass.inv_comp x

@[simp] theorem mul_inv (x : PiOne P a) : mul x (inv x) = id :=
  PathClass.comp_inv x

@[simp] theorem inv_id : inv (@id G P a) = @id G P a :=
  PathClass.inv_id

@[simp] theorem inv_mul_order (x y : PiOne P a) :
    inv (mul x y) = mul (inv y) (inv x) :=
  PathClass.inv_comp_order x y

/-- Path-valued associativity certificate for the presented fundamental group. -/
noncomputable def mul_assoc_path (x y z : PiOne P a) :
    Path (mul (mul x y) z) (mul x (mul y z)) :=
  Path.stepChain (mul_assoc x y z)

/-- The associativity certificate is coherent with right-unit composition. -/
noncomputable def mul_assoc_coherence (x y z : PiOne P a) :
    RwEq
      (Path.trans (mul_assoc_path x y z)
        (Path.refl (mul x (mul y z))))
      (mul_assoc_path x y z) :=
  rweq_cmpA_refl_right (mul_assoc_path x y z)

end PiOne

end Presented
end Path
end ComputationalPaths
