/-
# Quotient-saturated open subsets of geometric realization

Compatible families of maps on topological simplices descend through
Mathlib's realization adjunction.  Applying this to the Sierpiński topology on
`Prop` turns any compatible family of open simplex subsets into a genuine open
subset of `SSet.toTop`, with an exact computation rule on every representative.

This avoids reasoning directly with the generated equivalence relation of the
realization colimit.
-/

import ComputationalPaths.Path.Homotopy.TopologicalNerveContractible
import Mathlib.Topology.Order

open CategoryTheory Simplicial Opposite
open CategoryTheory.Limits

namespace ComputationalPaths
namespace Path
namespace TopologicalNerve

universe u

/-- The underlying type-valued diagram whose colimit is geometric
realization. -/
abbrev RealizationTypeDiagram (X : SSet.{u}) :=
  (CostructuredArrow.proj SSet.stdSimplex X ⋙
    SimplexCategory.toTop.{u}) ⋙ forget TopCat

/-- The realization-index object corresponding to a simplex. -/
noncomputable def realizationIndexOfSimplex
    {X : SSet.{u}} {n : SimplexCategory}
    (s : X.obj (op n)) : RealizationIndex X :=
  CostructuredArrow.mk (SSet.yonedaEquiv.symm s)

theorem realizationAtlas_indexOfSimplex
    {X : SSet.{u}} {n : SimplexCategory}
    (s : X.obj (op n))
    (p : SimplexCategory.toTop.{u}.obj n) :
    realizationAtlas X ⟨realizationIndexOfSimplex s, p⟩ =
      realizeSimplex s p := by
  rw [realizationAtlas_apply]
  simp [realizationIndexOfSimplex]

theorem realizationIndex_simplex_naturality
    {X : SSet.{u}} {a b : RealizationIndex X}
    (f : a ⟶ b) :
    SSet.yonedaEquiv a.hom =
      X.map f.left.op (SSet.yonedaEquiv b.hom) := by
  have hw : SSet.stdSimplex.map f.left ≫ b.hom = a.hom :=
    CostructuredArrow.w f
  rw [← hw]
  exact (uliftYonedaEquiv_naturality b.hom f.left.op).symm

/-- Equality in the genuine realization is generated by the elementary
simplex-coordinate identifications of the realization diagram. -/
theorem realizationAtlas_eqvGen
    {X : SSet.{u}} {a b : RealizationAtlas X}
    (h : realizationAtlas X a = realizationAtlas X b) :
    Relation.EqvGen (RealizationTypeDiagram X).ColimitTypeRel a b := by
  rcases a with ⟨a, p⟩
  rcases b with ⟨b, q⟩
  let c := (forget TopCat).mapCocone (realizationCocone X)
  let hc : IsColimit c :=
    isColimitOfPreserves (forget TopCat)
      (realizationCoconeIsColimit X)
  have hc' :
      ((RealizationTypeDiagram X).coconeTypesEquiv.symm c).IsColimit :=
    (Limits.Types.isColimit_iff_coconeTypesIsColimit c).mp ⟨hc⟩
  rw [← (RealizationTypeDiagram X).ιColimitType_eq_iff]
  rw [← hc'.equiv_symm_ι_apply a p,
    ← hc'.equiv_symm_ι_apply b q]
  exact _root_.congrArg hc'.equiv.symm h

/-- A map defined compatibly on every topological simplex of `X`. -/
structure SimplexFamily (X : SSet.{u}) (Y : TopCat.{u}) where
  app :
    ∀ (n : SimplexCategory), X.obj (op n) →
      (SimplexCategory.toTop.{u}.obj n ⟶ Y)
  naturality :
    ∀ {m n : SimplexCategory} (f : m ⟶ n)
      (s : X.obj (op n)),
      app m (X.map f.op s) =
        SimplexCategory.toTop.map f ≫ app n s

namespace SimplexFamily

variable {X : SSet.{u}} {Y : TopCat.{u}}

theorem unit_app_app (X : SSet.{u})
    {n : SimplexCategory} (s : X.obj (op n)) :
    (sSetTopAdj.unit.app X).app (op n) s =
      ULift.up (realizeSimplexHom s) := by
  letI : SSet.toTop.{u}.IsLeftKanExtension
      (SSet.stdSimplex.{u}.leftKanExtensionUnit
        SimplexCategory.toTop.{u}) :=
    inferInstanceAs
      (SSet.toTop.{u}.IsLeftKanExtension SSet.toTopSimplex.inv)
  rw [show sSetTopAdj.{u} =
      Presheaf.uliftYonedaAdjunction.{0} SSet.toTop.{u}
        (SSet.stdSimplex.{u}.leftKanExtensionUnit
          SimplexCategory.toTop.{u}) from rfl]
  rw [Presheaf.uliftYonedaAdjunction_unit_app_app]
  rfl

/-- The compatible simplex family as an adjoint simplicial map. -/
noncomputable def toSSetHom (F : SimplexFamily X Y) :
    X ⟶ TopCat.toSSet.obj Y where
  app n s := ULift.up (F.app n.unop s)
  naturality := by
    intro m n f
    funext s
    exact _root_.congrArg ULift.up (F.naturality f.unop s)

/-- Descend a compatible simplex family to the genuine realization. -/
noncomputable def desc (F : SimplexFamily X Y) :
    SSet.toTop.obj X ⟶ Y :=
  (sSetTopAdj.homEquiv X Y).symm F.toSSetHom

theorem realizeSimplexHom_desc (F : SimplexFamily X Y)
    {n : SimplexCategory} (s : X.obj (op n)) :
    realizeSimplexHom s ≫ F.desc = F.app n s := by
  have h : sSetTopAdj.homEquiv X Y F.desc = F.toSSetHom :=
    (sSetTopAdj.homEquiv X Y).apply_symm_apply _
  rw [Adjunction.homEquiv_unit] at h
  have h₂ :
      (TopCat.toSSet.map F.desc).app (op n)
          ((sSetTopAdj.unit.app X).app (op n) s) =
        F.toSSetHom.app (op n) s :=
    congrFun (NatTrans.congr_app h (op n)) s
  rw [unit_app_app] at h₂
  exact _root_.congrArg ULift.down h₂

theorem desc_realizeSimplex (F : SimplexFamily X Y)
    {n : SimplexCategory} (s : X.obj (op n))
    (p : SimplexCategory.toTop.{u}.obj n) :
    F.desc (realizeSimplex s p) = (F.app n s).hom p :=
  congrFun (_root_.congrArg
    (fun g : SimplexCategory.toTop.{u}.obj n ⟶ Y =>
      (ConcreteCategory.hom g : _ → _))
    (F.realizeSimplexHom_desc s)) p

theorem desc_unique (F : SimplexFamily X Y)
    (g : SSet.toTop.obj X ⟶ Y)
    (hg : ∀ (n : SimplexCategory) (s : X.obj (op n)),
      realizeSimplexHom s ≫ g = F.app n s) :
    g = F.desc := by
  apply (sSetTopAdj.homEquiv X Y).injective
  rw [Adjunction.homEquiv_unit, Adjunction.homEquiv_unit]
  ext n s
  obtain ⟨n⟩ := n
  show
    (TopCat.toSSet.map g).app (op n)
        ((sSetTopAdj.unit.app X).app (op n) s) =
      (TopCat.toSSet.map F.desc).app (op n)
        ((sSetTopAdj.unit.app X).app (op n) s)
  rw [unit_app_app]
  exact _root_.congrArg ULift.up
    ((hg _ s).trans (F.realizeSimplexHom_desc s).symm)

end SimplexFamily

/-- A quotient-compatible family of open subsets of all topological
simplices. -/
structure OpenFamily (X : SSet.{u}) where
  set :
    ∀ (n : SimplexCategory), X.obj (op n) →
      Set (SimplexCategory.toTop.{u}.obj n)
  isOpen : ∀ n s, IsOpen (set n s)
  naturality :
    ∀ {m n : SimplexCategory} (f : m ⟶ n)
      (s : X.obj (op n)),
      set m (X.map f.op s) =
        (SimplexCategory.toTop.map f).hom ⁻¹' set n s

namespace OpenFamily

variable {X : SSet.{u}}

noncomputable def toSimplexFamily (U : OpenFamily X) :
    SimplexFamily X (TopCat.of (ULift.{u} Prop)) where
  app n s := TopCat.ofHom
    ⟨fun p => ULift.up (p ∈ U.set n s),
      continuous_uliftUp.comp (continuous_Prop.2 (U.isOpen n s))⟩
  naturality := by
    intro m n f s
    refine TopCat.hom_ext (ContinuousMap.ext fun p => ?_)
    exact _root_.congrArg ULift.up
      (propext (by rw [U.naturality f s]; exact Iff.rfl))

/-- The genuine quotient-saturated open subset descended from `U`. -/
noncomputable def descSet (U : OpenFamily X) :
    Set (SSet.toTop.obj X) :=
  {z | (U.toSimplexFamily.desc z).down}

theorem isOpen_descSet (U : OpenFamily X) :
    IsOpen U.descSet :=
  continuous_Prop.1
    (continuous_uliftDown.comp
      (U.toSimplexFamily.desc).hom.continuous)

theorem mem_descSet (U : OpenFamily X)
    {n : SimplexCategory} (s : X.obj (op n))
    (p : SimplexCategory.toTop.{u}.obj n) :
    realizeSimplex s p ∈ U.descSet ↔ p ∈ U.set n s := by
  show (U.toSimplexFamily.desc (realizeSimplex s p)).down ↔ _
  rw [U.toSimplexFamily.desc_realizeSimplex s p]
  exact Iff.rfl

/-! ## Computational-path certificate -/

noncomputable def descSetMembershipPath (U : OpenFamily X)
    {n : SimplexCategory} (s : X.obj (op n))
    (p : SimplexCategory.toTop.{u}.obj n) :
    Path
      (realizeSimplex s p ∈ U.descSet)
      (p ∈ U.set n s) :=
  Path.stepChain (propext (U.mem_descSet s p))

noncomputable def descSetMembershipCoherence (U : OpenFamily X)
    {n : SimplexCategory} (s : X.obj (op n))
    (p : SimplexCategory.toTop.{u}.obj n) :
    RwEq
      (Path.trans (descSetMembershipPath U s p)
        (Path.refl (p ∈ U.set n s)))
      (descSetMembershipPath U s p) :=
  rweq_cmpA_refl_right (descSetMembershipPath U s p)

end OpenFamily

end TopologicalNerve
end Path
end ComputationalPaths
